import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL(p,import.meta.url),'utf8');
const schema=read('../prisma/schema.prisma');
const access=read('../src/auth/access.guard.ts');
const auth=read('../src/auth/auth.service.ts');
const controller=read('../src/auth/auth.controller.ts');
const core=read('../src/core/core-read.controller.ts');
const importer=read('../src/migration/import.service.ts');
const main=read('../src/main.ts');
const admin=read('../scripts/create-admin.ts');
assert.match(schema,/enum SystemRole/);
assert.match(schema,/model UserCredentialToken/);
assert.match(schema,/model LoginRateLimit/);
assert.match(access,/Endpoint sem política de autorização explícita/);
assert.match(access,/evaluateAccess/);
assert.doesNotMatch(importer,/networkAdmin:\s*!!u\.allUnits/);
assert.match(importer,/networkAdmin:false/);
assert.match(importer,/u\.allUnits\?unitRows\.map/);
assert.equal(core.includes('legacyPayload'),false);
assert.match(core,/@RequirePermissions\('clients\.read'\)/);
assert.match(core,/DEC-004: cliente é cadastro de rede/);
assert.match(auth,/sha256\(token\)/);
assert.match(auth,/LOGIN_RATE_LIMIT_MAX/);
assert.match(auth,/argon2\.verify/);
assert.ok(auth.indexOf('argon2.verify') < auth.indexOf('passwordResetRequired'));
assert.match(controller,/@Get\('csrf'\)/);
assert.match(controller,/activation-token/);
assert.match(controller,/reset-token/);
assert.match(main,/SwaggerModule\.setup/);
assert.match(main,/OPENAPI_ENABLED/);
assert.match(admin,/SystemRole\.OWNER/);
assert.match(admin,/networkAdmin:true/);
console.log(JSON.stringify({ok:true,assertions:22,suite:'V98b security contract'}));
