import assert from 'node:assert/strict';
const {legacySystemRole,mapLegacyPermissions}=await import('../src/migration/legacy-permission-mapper.ts');
const reception=mapLegacyPermissions({role:'reception'});
assert.equal(reception.includes('agenda.read'),true);
assert.equal(reception.includes('agenda.manage'),true);
assert.equal(reception.includes('clients.read'),true);
assert.equal(reception.includes('finance.read'),false);
assert.equal(reception.includes('users.manage'),false);
const admin=mapLegacyPermissions({role:'admin',allUnits:true});
assert.equal(admin.includes('finance.read'),true);
assert.equal(admin.includes('stock.read'),true);
assert.equal(admin.includes('users.manage'),false);
assert.equal(admin.includes('migration.manage'),false);
assert.equal(legacySystemRole({role:'admin'}),'ADMINISTRATIVE');
assert.equal(legacySystemRole({role:'reception'}),'OPERATOR');
const custom=mapLegacyPermissions({role:'reception',permissionMode:'custom',permissions:{'page.clients':false,'page.finance':true}});
assert.equal(custom.includes('clients.read'),false);
assert.equal(custom.includes('finance.read'),true);
console.log(JSON.stringify({ok:true,assertions:13,suite:'V98b legacy permission mapping'}));
