const fs=require('fs'),vm=require('vm');
const html=fs.readFileSync(__dirname+'/../index.html','utf8');
const scripts=[...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);
const code=scripts.find(s=>s.includes("const V85_SCHEMA=85")); if(!code)throw new Error('V85 missing');
let tests=0;const ok=(v,m)=>{tests++;if(!v)throw new Error(m)};
let metricCalls=0, saves=0;
const rows=[
{bookingId:'b1',creatorId:'r1',creatorName:'Maria',creatorOrigin:'internal_booking',clientId:'c1',clientName:'A',createdDate:'2026-09-10',createdAt:'2026-09-10T10:00:00Z',appointmentDate:'2026-10-01',unitId:'u1',status:'Agendado',commercialPrice:32.5,price:40},
{bookingId:'b1',creatorId:'r1',creatorName:'Maria',creatorOrigin:'internal_booking',clientId:'c1',clientName:'A',createdDate:'2026-09-10',createdAt:'2026-09-10T10:00:00Z',appointmentDate:'2026-10-01',unitId:'u1',status:'Agendado',commercialPrice:32.5,price:40},
{bookingId:'b2',creatorId:'r1',creatorName:'Maria',creatorOrigin:'internal_booking',clientId:'c2',clientName:'B',createdDate:'2026-09-11',createdAt:'2026-09-11T10:00:00Z',appointmentDate:'2026-10-02',unitId:'u1',status:'Cancelado',commercialPrice:100,price:100},
{bookingId:'b3',creatorId:'r2',creatorName:'Ana',creatorOrigin:'internal_booking',clientId:'c3',clientName:'C',createdDate:'2026-09-12',createdAt:'2026-09-12T10:00:00Z',appointmentDate:'2026-10-03',unitId:'u2',status:'Faltou',commercialPrice:70,price:70},
{bookingId:'b4',creatorId:'',creatorName:'Agendamento online',creatorOrigin:'public_booking',clientId:'c4',clientName:'D',createdDate:'2026-09-13',createdAt:'2026-09-13T10:00:00Z',appointmentDate:'2026-10-04',unitId:'u1',status:'Agendado',commercialPrice:50,price:50}
];
const els=new Map();const el=id=>{if(!els.has(id))els.set(id,{id,value:'',innerHTML:'',outerHTML:'',querySelector(){return null},querySelectorAll(){return[]}});return els.get(id)};
const ctx={console,window:null,document:{getElementById:el},db:{schemaVersion:84,migrationHistory:[],units:[{id:'u1',name:'Big',active:true},{id:'u2',name:'Centro',active:true}],userAccounts:[{id:'r1',name:'Maria',role:'reception',active:true,unitIds:['u1']},{id:'r2',name:'Ana',role:'reception',active:true,unitIds:['u2']},{id:'r0',name:'Zero',role:'reception',active:true,unitIds:['u1']}],receptionBookingGoals:[]},Date,save:()=>saves++,setTimeout:f=>{try{f()}catch{}},escapeHtml:String,money:n=>'R$ '+Number(n).toFixed(2),formatDateBR:s=>s,localDateISO:()=> '2026-09-28',reportFilters:{from:'2026-09-01',to:'2026-09-30'},renderReportAgendaV52:()=>'<div id="oldReport">old</div>',renderAdmin:()=>{},adminPage:{innerHTML:''},modal:()=>{},closeModal:()=>{}};ctx.window=ctx;
ctx.__imperioV83={allRows:()=>rows,allowedUnitsV83:()=>ctx.db.units,metrics:rs=>{metricCalls++;let bids=new Set(rs.map(r=>r.bookingId)),clients=new Set(rs.map(r=>r.clientId));return {bookings:bids.size,services:rs.length,clients:clients.size,value:rs.reduce((s,r)=>s+r.commercialPrice,0),referenceValue:0,comboDiscount:0}}};
ctx.__imperioV84={goalMetrics:()=>({bookings:0,services:0,clients:0,value:0})};
vm.createContext(ctx);vm.runInContext(code,ctx);const api=ctx.__imperioV85;
ok(api.schema===85,'schema export');ok(ctx.db.schemaVersion===85,'schema migrated');ok(ctx.db.migrationHistory.filter(x=>x.id==='v85-reception-performance-dashboard').length===1,'migration once');let before=saves;ok(api.migrate()===false,'migration idempotent');ok(saves===before,'no save second migrate');
ctx.__v85Filters={createdFrom:'2026-09-01',createdTo:'2026-09-30',appointmentFrom:'',appointmentTo:'',creator:'all',status:'valid',unit:'all'};
let m=api.metric(api.filteredRows());ok(metricCalls>0,'V85 delegates canonical V83 metrics');ok(m.bookings===2,'valid bookings 2');ok(m.services===3,'valid services 3');ok(m.clients===2,'valid clients 2');ok(m.value===115,'valid commercial value 115');
let cs=api.creators();ok(cs.some(x=>x.key==='r0'),'zero receptionist shown');ok(cs.some(x=>x.key==='__public__'),'public shown separately');ok(api.lossCounts('r1').cancelled===1,'cancel distinct booking');ok(api.lossCounts('r1').missed===0,'no missed r1');ok(api.lossCounts('r2').missed===1,'missed r2');
ctx.__v85Filters.unit='u1';ok(api.baseRows().every(r=>r.unitId==='u1'),'unit filter');ctx.__v85Filters.unit='all';ctx.__v85Filters.creator='r1';ok(api.baseRows().every(r=>r.creatorId==='r1'),'creator filter');ctx.__v85Filters.creator='all';ctx.__v85Filters.status='Cancelado';ok(api.filteredRows().length===1&&api.filteredRows()[0].bookingId==='b2','status filter');ctx.__v85Filters.status='all';ctx.__v85Filters.createdFrom='2026-09-12';ok(api.baseRows().every(r=>r.createdDate>='2026-09-12'),'creation date filter');ctx.__v85Filters.createdFrom='';ctx.__v85Filters.appointmentTo='2026-10-02';ok(api.baseRows().every(r=>r.appointmentDate<='2026-10-02'),'appointment date filter');
ctx.__v85Filters={createdFrom:'2026-09-01',createdTo:'2026-09-30',appointmentFrom:'',appointmentTo:'',creator:'all',status:'valid',unit:'all'};let panel=api.panelHtml();ok((panel.match(/id="v85Performance"/g)||[]).length===1,'panel single id');ok(panel.includes('Rendimento dos agendamentos por usuário'),'panel visible title');let combined=ctx.renderReportAgendaV52({});ok(combined.indexOf('v85Performance')<combined.indexOf('oldReport'),'panel prepended to report');ok(!/1º lugar|2º lugar|ranking automático|score/i.test(panel),'no ranking');
console.log(JSON.stringify({ok:true,tests,metricCalls,users:cs.length}));
