const fs=require('fs'),vm=require('vm');
const html=fs.readFileSync(__dirname+'/../index.html','utf8');const scripts=[...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);
let tests=0;const ok=(v,m)=>{tests++;if(!v)throw new Error(m)};
const get=v=>scripts.find(s=>s.includes(v));
ok(scripts.length===60,'49 scripts');for(let i=0;i<scripts.length;i++){try{new vm.Script(scripts[i])}catch(e){throw new Error('syntax script '+(i+1)+': '+e.message)}tests++}
ok((html.match(/<script\b/gi)||[]).length===(html.match(/<\/script>/gi)||[]).length,'script tags balanced');
// V80 isolated: same client incompatibility + event hooks + physical advisory nonblocking
{
 const code=get('const V80_SCHEMA=80');let placementCalls=0,saves=0;const db={schemaVersion:79,migrationHistory:[],waitlistRequests:[{id:'w1',clientId:'c1',clientNameSnapshot:'C',unitId:'u1',serviceId:'s1',availabilityDate:'2026-10-03',availabilityStartTime:'10:00',availabilityEndTime:'11:00',professionalPreferenceMode:'any',status:'WAITING',createdAt:'2026-09-01T10:00:00Z'},{id:'w2',clientId:'c1',clientNameSnapshot:'C',unitId:'u1',serviceId:'s2',availabilityDate:'2026-10-03',availabilityStartTime:'10:00',availabilityEndTime:'11:00',professionalPreferenceMode:'any',status:'WAITING',createdAt:'2026-09-01T10:01:00Z'}],bookings:[],services:[{id:'s1',name:'S1'},{id:'s2',name:'S2'}],pros:[],units:[],categories:[]};
 const ctx={console,db,window:null,Date,structuredClone:global.structuredClone,save:()=>saves++,localDateISO:()=> '2026-09-28',timeToMin:t=>{let [h,m]=t.split(':').map(Number);return h*60+m},minToTime:m=>String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0'),availabilityEligiblePros:sid=>sid==='s1'?[{id:'p1',name:'P1'}]:[{id:'p2',name:'P2'}],availabilityServiceDuration:()=>60,availabilityPlacement:(p,s,d,t,u)=>{placementCalls++;return {proId:p,serviceId:s,start:'10:00',end:'11:00',startMin:600,endMin:660,duration:60}},availabilityClientCompatible:(as,pl)=>!as.some(a=>a.startMin<pl.endMin&&a.endMin>pl.startMin),normalizeBooking:x=>x,itemDuration:()=>60,toast:()=>{},document:{getElementById:()=>null},renderAgenda:()=>{},renderAdmin:()=>{},closeModal:()=>{},openReservation:()=>{},defaultReservationItem:()=>({}),renderReservationModal:()=>{},availabilityServicePrice:()=>40,saveExistingBooking:()=>{},saveBlockTime:()=>{},saveBlockEdit:()=>{},deleteBlock:()=>{},agendaDrop:()=>{},saveReservation:()=>{},v79SaveQueueRequest:()=>{},v79MarkQueueContacted:()=>{},finishBooking:()=>{},savePro:()=>{},togglePro:()=>{},saveService:()=>{},toggleService:()=>{},v77SaveWorkstation:()=>{}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(code,ctx);let a=ctx.__imperioV80.compute();ok(a.size===1,'same-client incompatible opportunity not double assigned');let before=placementCalls;ctx.finishBooking();ok(placementCalls>before,'public booking triggers reevaluation');before=placementCalls;ctx.savePro();ok(placementCalls>before,'professional update triggers reevaluation');before=placementCalls;ctx.saveService();ok(placementCalls>before,'service update triggers reevaluation');before=placementCalls;ctx.v77SaveWorkstation();ok(placementCalls>before,'workstation update refreshes physical advisory');ok(db.bookings.length===0,'opportunity engine no booking auto-created');
}
// V81 scale but no fitting service = full; no scale = not full; free placement = not full.
{
 const code=get('const V81_SCHEMA=81');let free=false;const db={schemaVersion:80,migrationHistory:[],units:[{id:'u1',name:'U'}],services:[{id:'s1',name:'S',active:true,duration:30}],pros:[{id:'p1',name:'P',active:true,units:['u1']}],bookings:[]};const ctx={console,db,window:null,Date,save:()=>{},localDateISO:()=> '2026-09-28',timeToMin:t=>{let [h,m]=t.split(':').map(Number);return h*60+m},minToTime:m=>String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0'),availabilityWorkWindow:()=>({start:'10:00',end:'10:20'}),availabilityEligiblePros:()=>[{id:'p1'}],availabilityServiceDuration:()=>30,availabilityPlacement:()=>free?{proId:'p1',serviceId:'s1',start:'10:00'}:null,agendaDate:'2026-09-29',document:{getElementById:()=>null,querySelector:()=>null,head:{appendChild:()=>{}},createElement:()=>({})},renderAgenda:()=>{},renderAdmin:()=>{},setTimeout:()=>{}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(code,ctx);let m=ctx.__imperioV81.dayModel('u1','2026-09-29');ok(m.configured&&m.full&&m.eligiblePairs===1&&m.checked===0,'no fitting duration counts full');ctx.availabilityWorkWindow=()=>null;m=ctx.__imperioV81.dayModel('u1','2026-09-29');ok(!m.configured&&!m.full,'no scale not full');ctx.availabilityWorkWindow=()=>({start:'10:00',end:'11:00'});free=true;m=ctx.__imperioV81.dayModel('u1','2026-09-29');ok(m.configured&&!m.full&&!!m.available,'real placement means not full');
}
// V82 migration canonical/idempotent + legacy reconciliation.
{
 const code=get('const V82_SCHEMA=82');let saves=0;const db={schemaVersion:81,migrationHistory:[],migrations:[{id:'v82-historical-fill-demand-trend',at:'2026-01-01T00:00:00Z'}]};const ctx={console,db,window:null,Date,save:()=>saves++,renderReportAgendaV52:()=>'',renderAdmin:()=>{},document:{}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(code,ctx);ok(db.migrationHistory.filter(x=>x.id==='v82-historical-fill-demand-trend').length===1,'V82 canonical migration history');ok(db.migrationHistory.find(x=>x.id==='v82-historical-fill-demand-trend').appliedAt==='2026-01-01T00:00:00Z','V82 legacy timestamp reconciled');let b=saves;ok(ctx.__imperioV82.schema===82,'V82 API');vm.runInContext(`__imperioV82`,ctx); // no action
 // execute ensure via reloading code; migration must not save second time
 vm.runInContext(code,ctx);ok(saves===b,'V82 reload idempotent no save');ok(db.migrations.length===1,'legacy marker preserved non-destructively');
}
// V86 migration and no new collections.
{
 const code=get('const V86_SCHEMA=86');let saves=0;const db={schemaVersion:85,migrationHistory:[],migrations:[{id:'v82-historical-fill-demand-trend',at:'2026-01-01T00:00:00Z'}]};const ctx={console,db,window:null,Date,save:()=>saves++,renderAdmin:()=>{},document:{getElementById:()=>null}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(code,ctx);ok(db.schemaVersion===86,'schema 86');ok(db.migrationHistory.some(x=>x.id==='v86-consolidation-sanitation-v80-v85'),'V86 migration marker');ok(db.migrationHistory.some(x=>x.id==='v82-historical-fill-demand-trend'),'V86 reconciles V82 marker');let b=saves;ok(ctx.__imperioV86.migrate()===false&&saves===b,'V86 idempotent');ok(ctx.__imperioV86.canonicalReceptionMetrics.includes('V83'),'canonical reception declared V83');ok(ctx.__imperioV86.canonicalPhysicalCapacity.includes('V77'),'canonical physical declared V77');
}
console.log(JSON.stringify({ok:true,tests,scripts:scripts.length}));
