const fs=require('fs'),vm=require('vm');
const html=fs.readFileSync(__dirname+'/../index.html','utf8');
const scripts=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);
class FixedDate extends Date{constructor(...a){super(...(a.length?a:['2026-09-28T18:30:00-03:00']))}static now(){return Date.parse('2026-09-28T18:30:00-03:00')}}
class MockStorage{constructor(raw){this.m=new Map(raw==null?[]:[['imperio-demo-v1',raw]]);this.writeCount=0}getItem(k){return this.m.has(k)?this.m.get(k):null}setItem(k,v){this.writeCount++;this.m.set(k,String(v))}removeItem(k){this.m.delete(k)}}
function el(id=''){return {id,value:'',checked:false,innerHTML:'',textContent:'',style:{},dataset:{},children:[],classList:{add(){},remove(){},toggle(){return false}},appendChild(){},remove(){},focus(){},click(){},querySelector(){return null},querySelectorAll(){return[]},insertAdjacentHTML(p,h){this.innerHTML+=h},addEventListener(){},removeEventListener(){},removeAttribute(){},setAttribute(){},getAttribute(){return null}}}
function run(raw){const els=new Map(),doc={body:el('body'),documentElement:el('html'),getElementById(id){if(!els.has(id))els.set(id,el(id));return els.get(id)},querySelector(){return null},querySelectorAll(){return[]},createElement:t=>el(t),addEventListener(){},removeEventListener(){}};const ls=new MockStorage(raw);const ctx={console,document:doc,localStorage:ls,sessionStorage:new MockStorage(),window:null,navigator:{clipboard:{writeText:async()=>{}}},location:{},history:{},Date:FixedDate,JSON,Math,Number,String,Array,Object,Map,Set,Intl,RegExp,Promise,structuredClone:global.structuredClone,setTimeout:f=>{try{f()}catch{}},clearTimeout(){},setInterval(){return 1},clearInterval(){},confirm:()=>true,prompt:()=>'',alert:()=>{},fetch:async()=>({ok:false,json:async()=>({})}),Blob:function(){},FileReader:function(){},URL:{createObjectURL:()=>'',revokeObjectURL(){}},event:{target:null}};ctx.window=ctx;vm.createContext(ctx);let errors=[];for(let i=0;i<scripts.length;i++){try{vm.runInContext(scripts[i],ctx,{filename:'s'+i+'.js'})}catch(e){errors.push(e.stack||String(e));break}}return {ctx,ls,doc,els,errors}}
function ev(r,c){return vm.runInContext(c,r.ctx)}
let tests=0;function ok(c,m){tests++;if(!c)throw new Error(m)}function eq(a,b,m){ok(JSON.stringify(a)===JSON.stringify(b),m+': '+JSON.stringify(a)+' != '+JSON.stringify(b))}
function db(){return {schemaVersion:88,migrationHistory:[{id:'v88-agenda-fill-trend'}],units:[{id:'u1',name:'U1',active:true}],categories:[{id:'c1',name:'Manicure'},{id:'c2',name:'Alongamento'},{id:'c3',name:'Cabelo'},{id:'c4',name:'Cílios'}],services:[{id:'s1',name:'Manicure',category:'c1',clientArea:'hands',mustFinishBeforeSameArea:false,active:true,price:45,duration:45,show:true,online:true,proRules:{}},{id:'s3',name:'Pedicure',category:'c1',clientArea:'feet',mustFinishBeforeSameArea:false,active:true,price:55,duration:50,show:true,online:true,proRules:{}},{id:'s2',name:'Manutenção',category:'c2',clientArea:'hands',mustFinishBeforeSameArea:true,active:true,price:145,duration:75,show:true,online:true,proRules:{}},{id:'s4',name:'Escova',category:'c3',clientArea:'hair',mustFinishBeforeSameArea:false,active:true,price:80,duration:60,show:true,online:true,proRules:{}}],pros:[],clients:[],bookings:[],workstations:[{id:'w1',unitId:'u1',name:'Mesa',allowedCategoryIds:['c1','c2'],active:true}],acquisitionSources:[],paymentMethods:[],financialAccounts:[],demoCashMovements:[],demoFinancialEntries:[],cashSessions:[],cashAudits:[],auditEvents:[],clientAppointments:[],clientCommands:[],demoProducts:[],demoPackageCatalog:[],clientCreditMovements:[],clientPackages:[],clientReturns:[],combos:[],financeCategories:[],companyEntities:[],financeGoals:[],stockProducts:[],stockBalances:[],stockPurchases:[],stockRequests:[],stockTransfers:[],stockMovements:[],stockInputCosts:[],stockFamilies:[],stockSubstitutions:[],commissionSettlements:[],commissionPayments:[],professionalCommissionAdjustments:[],tipMovements:[],remunerationRules:[],professionalDailyWork:[],clientReceivables:[],clientReceivablePayments:[],commissionEvents:[],tipDeductionRules:[],managementTasks:[],notificationAlertStates:{},notificationSettings:{},fiscalDocuments:[],fiscalSettings:{},reportSettings:{},commissionSettings:{},userAccounts:[{id:'adm',name:'Admin',username:'a',password:'x',role:'admin',active:true,allUnits:true,unitIds:[]}],systemSettings:{settingsVersion:1,formFields:{},optionSets:{}},communicationSettings:{whatsapp:{unitNumbers:{},templates:{}}},agendaFillSnapshots:[],agendaFillTrendSettings:{historyWindowDays:180,maxSamples:8,minSamples:4,thresholdPp:8}}}
let r=run(JSON.stringify(db()));ok(!r.errors.length,'runtime sem erro');ok(scripts.length===60,'53 scripts');ok(ev(r,'db.schemaVersion')===96,'schema 89');ok(ev(r,"db.migrationHistory.filter(x=>(typeof x==='string'?x:x.id)==='v89-structural-configurability-phase1').length")===1,'migration V89 única');ok(ev(r,'__imperioV89.schema')===89,'API V89');ok(ev(r,"__imperioV89.idPolicy==='stable_preserved'"),'IDs preservados');ok(ev(r,"__imperioV89.deletionPolicy==='deactivate_only'"),'sem exclusão destrutiva');
ok(ev(r,"__imperioV89.configurabilityRegistry.configurable.includes('service.categories')"),'registro formal de configurabilidade');
ok(ev(r,"__imperioV89.configurabilityRegistry.protectedSemantics.includes('booking.status')"),'semântica crítica protegida');
ok(ev(r,"db.categories.every(c=>c.active!==undefined&&Number.isFinite(Number(c.order))&&c.configVersion===1)"),'categorias normalizadas');eq(ev(r,"__imperioV89.categoryDefaults('c2')"),{clientArea:'hands',mustFinishBeforeSameArea:true},'defaults c2 inferidos por dados');ok(ev(r,"!('clientArea' in __imperioV89.categoryDefaults('c1'))"),'categoria mista não recebe área inventada');eq(ev(r,"__imperioV89.categoryDefaults('c3')"),{clientArea:'hair',mustFinishBeforeSameArea:false},'defaults cabelo pelos serviços existentes');
let beforeIds=ev(r,'db.categories.map(c=>c.id)');ev(r,"__imperioV89.updateCategory('c1',{name:'Unhas tradicionais',description:'Teste'})");eq(ev(r,'db.categories.map(c=>c.id)'),beforeIds,'renomear preserva IDs');ok(ev(r,"db.categories.find(c=>c.id==='c1').name==='Unhas tradicionais'"),'renomeia categoria');ok(ev(r,"db.services.filter(s=>s.category==='c1').length===2"),'serviços mantêm vínculo por ID');ok(ev(r,"db.workstations[0].allowedCategoryIds.includes('c1')"),'estação mantém vínculo por ID');
let cr=ev(r,"__imperioV89.createCategory({name:'Massagem',description:'Nova operação'})");ok(cr.ok,'cria categoria');let newId=cr.category.id;ok(ev(r,`db.categories.some(c=>c.id==='${newId}'&&c.active===true)`),'nova categoria ativa');ok(ev(r,`__imperioV89.categoryOptions('').includes('${newId}')`),'categoria ativa disponível para serviço');let dup=ev(r,"__imperioV89.createCategory({name:'massagem'})");ok(dup.ok===false,'nome duplicado bloqueado');
let togg=ev(r,`__imperioV89.toggleCategory('${newId}')`);ok(togg.ok&&togg.category.active===false,'desativa sem excluir');ok(ev(r,`db.categories.some(c=>c.id==='${newId}')`),'categoria desativada permanece');ok(!ev(r,`__imperioV89.categoryOptions('').includes('${newId}')`),'inativa fora de novos serviços');ok(ev(r,`__imperioV89.categoryOptions('${newId}').includes('${newId}')`),'inativa disponível para vínculo histórico atual');
// Parte 2: integrações e remoção de heurísticas por nome.
ok(ev(r,`defaultServiceClientArea({name:'Pedicure Premium',category:'${newId}'})==='none'`),'nome do serviço não comanda mais área operacional');
ok(ev(r,`defaultServiceLeadRule({name:'Alongamento XPTO',category:'${newId}'})===false`),'nome/categoria não comanda mais regra de sequência');
ev(r,`__imperioV89.toggleCategory('${newId}')`); // reativa
ok(ev(r,`__imperioV89.updateCategory('${newId}',{serviceDefaults:{clientArea:'face',mustFinishBeforeSameArea:true}}).ok`),'defaults explícitos configuráveis');
ok(ev(r,`defaultServiceClientArea({name:'Qualquer nome',category:'${newId}'})==='face'`),'área vem do metadado explícito');
ok(ev(r,`defaultServiceLeadRule({name:'Qualquer nome',category:'${newId}'})===true`),'sequência vem do metadado explícito');
ok(html.includes("cats=(db.categories||[]).filter")&&html.includes("services.some(s=>s.category===c.id)"),'Relatórios usam categorias dinâmicas do banco');
ok(html.includes("function v75catLabel(id,fallback=''){return fallback||db.categories.find(c=>c.id===id)?.name"),'DRE resolve categoria dinamicamente por ID');
ev(r,`db.workstations[0].allowedCategoryIds.push('${newId}')`);ok(ev(r,`__imperioV89.stationsFor('${newId}').length===1`),'capacidade física aceita categoria dinâmica por ID');
let cap=ev(r,`__imperioV77.evaluatePhysicalCapacity({unitId:'u1',date:'2026-09-29',demands:[{id:'d1',categoryId:'${newId}',startMin:600,endMin:660}]})`);ok(cap.configured&&cap.allocated===1&&!cap.hasConflict,'motor canônico de capacidade aloca categoria nova configurada');
let catStatus=ev(r,`__imperioV89.categoryIntegrationStatus('${newId}')`);ok(catStatus.ok&&catStatus.capacityUsesCategoryIds,'integração com capacidade reconhece categoria dinâmica');
ok(ev(r,`__imperioV89.stockCategoryOptions('').includes('${newId}')`),'estoque oferece categoria ativa dinamicamente');
let order0=ev(r,"__imperioV89.sortedCategories({includeInactive:true}).map(c=>c.id)");ev(r,"__imperioV89.moveCategory('c2',-1)");let order1=ev(r,"__imperioV89.sortedCategories({includeInactive:true}).map(c=>c.id)");ok(order0.join('|')!==order1.join('|'),'reordena sem trocar ID');
let integ=ev(r,'__imperioV89.integrity()');ok(integ.ok,'integridade válida');ev(r,"db.services.push({id:'orphan',category:'missing'})");ok(ev(r,'__imperioV89.integrity().orphanServices.length')===1,'detecta serviço órfão');ev(r,'db.services.pop()');
let financialBefore=ev(r,"JSON.stringify({cash:db.demoCashMovements,fin:db.demoFinancialEntries,com:db.commissionEvents,recv:db.clientReceivables})");ev(r,"__imperioV89.updateCategory('c3',{name:'Hair'})");let financialAfter=ev(r,"JSON.stringify({cash:db.demoCashMovements,fin:db.demoFinancialEntries,com:db.commissionEvents,recv:db.clientReceivables})");eq(financialAfter,financialBefore,'mudanças de categoria são financeiramente neutras');
ok(ev(r,"db.auditEvents.some(e=>e.entityType==='serviceCategory')"),'alterações auditadas');
let raw=r.ls.getItem('imperio-demo-v1'),r2=run(raw);ok(!r2.errors.length,'reabertura sem erro');ok(ev(r2,'db.schemaVersion')===96,'schema permanece 89');ok(ev(r2,"db.migrationHistory.filter(x=>(typeof x==='string'?x:x.id)==='v89-structural-configurability-phase1').length")===1,'migration idempotente');ok(r2.ls.writeCount===0,'reabertura limpa não regrava migration');
console.log(JSON.stringify({ok:true,tests,scripts:scripts.length,schema:89,feature:'structural_configurability_phase1'}));
