const fs=require('fs'),vm=require('vm');
const html=fs.readFileSync(__dirname+'/../index.html','utf8');
const scripts=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);
class MockStorage{constructor(raw){this.m=new Map(raw==null?[]:[['imperio-demo-v1',raw]]);this.writeCount=0}getItem(k){return this.m.has(k)?this.m.get(k):null}setItem(k,v){this.writeCount++;this.m.set(k,String(v))}removeItem(k){this.m.delete(k)}clear(){this.m.clear()}}
function element(id=''){return {id,value:'',checked:false,innerHTML:'',textContent:'',style:{},dataset:{},children:[],options:[],selectedIndex:0,className:'',src:'',href:'',files:[],disabled:false,firstChild:null,parentNode:null,classList:{add(){},remove(){},toggle(){return false},contains(){return false}},appendChild(x){this.children.push(x);x.parentNode=this;return x},insertBefore(x){this.children.unshift(x);x.parentNode=this;return x},remove(){},click(){},focus(){},select(){},insertAdjacentElement(){},insertAdjacentHTML(){},addEventListener(){},removeEventListener(){},querySelector(){return null},querySelectorAll(){return[]},closest(){return null},contains(){return false},setAttribute(){},getAttribute(){return null}}}
function run(raw){const els=new Map(),qsAll=new Map();const doc={body:element('body'),documentElement:element('html'),_qsAll:qsAll,getElementById(id){if(!els.has(id))els.set(id,element(id));return els.get(id)},querySelector(){return null},querySelectorAll(sel){return qsAll.get(sel)||[]},createElement(tag){return element(tag)},addEventListener(){},removeEventListener(){}};const ls=new MockStorage(raw),ss=new MockStorage(null);const ctx={console,localStorage:ls,sessionStorage:ss,document:doc,window:null,navigator:{clipboard:{writeText:async()=>{}}},location:{},history:{},setTimeout:(f)=>{try{f()}catch{}},clearTimeout(){},setInterval(){return 1},clearInterval(){},structuredClone:global.structuredClone,Date,JSON,Math,Number,String,Array,Object,Map,Set,Intl,RegExp,Promise,Blob:function(){},FileReader:function(){},URL:{createObjectURL:()=>'',revokeObjectURL(){}},confirm:()=>true,prompt:()=>'',alert:()=>{},fetch:async()=>({ok:false,json:async()=>({})}),event:{target:null}};ctx.window=ctx;vm.createContext(ctx);const errors=[];for(let i=0;i<scripts.length;i++){try{vm.runInContext(scripts[i],ctx,{filename:`script${i}.js`})}catch(e){errors.push(`script ${i}: ${e.stack||e}`);break}}return {ctx,ls,ss,els,doc,errors}}
function ev(ctx,code){return vm.runInContext(code,ctx)}
function assert(c,m){if(!c)throw new Error(m)}let tests=0;function ok(c,m){tests++;assert(c,m)}
function setup(r){for(const id of ['adminTabs','unitPicker','subbar','adminPage','loginUser','loginPass','modalHost','v73NewOption'])r.ctx[id]=r.doc.getElementById(id);r.doc.getElementById('unitPicker').value='u1';let admin=ev(r.ctx,"(db.userAccounts||[]).find(u=>u.role==='admin'&&u.active!==false)?.id||''");if(admin)ev(r.ctx,`__imperioV63.sessionSet(${JSON.stringify(admin)})`)}
function input(r,id,value='',checked=false){let e=r.doc.getElementById(id);e.value=String(value);e.checked=!!checked;return e}
let r=run(null);setup(r);
ok(!r.errors.length,'A runtime sem erros');
ok(scripts.length===50,'A 37 blocos JavaScript');
ok(ev(r.ctx,'db.schemaVersion')===87,'A schema 74');
ok(ev(r.ctx,"db.migrationHistory.filter(x=>(typeof x==='string'?x:x.id)==='v74-configurable-fields-options-finance').length")===1,'A migração V74 única');
ok(ev(r.ctx,"typeof __imperioV74==='object'&&__imperioV74.schema===74"),'A API V74 exposta');
ok(ev(r.ctx,'db.systemSettings.formConfigModulesVersion')===4,'A versão modular 4');
// Central completa.
ok(ev(r.ctx,"v74OpenFieldsSettings('finance')")===true,'B abre Financeiro');let h=r.doc.getElementById('adminPage').innerHTML;
ok(h.includes('Clientes')&&h.includes('Agenda')&&h.includes('Comandas')&&h.includes('Profissionais')&&h.includes('Estoque')&&h.includes('Financeiro'),'B seis módulos configuráveis');
ok(h.includes('Lançamento manual')&&h.includes('Contas financeiras')&&h.includes('CNPJs / empresas')&&h.includes('Conta Mensal · recebimento'),'B grupos financeiros renderizados');
ok(h.includes('Catálogos financeiros canônicos'),'B informa catálogos canônicos sem duplicar DRE/pagamentos');
// Proteções estruturais.
for(const k of ['entryDirection','entryStatus','entryDate','entryUnit','entryAccount','entryCategory','entryAmount','accountName','accountType','accountUnit','companyLegalName','companyUnit','monthlyPaymentDate','monthlyPaymentMethod','monthlyPaymentAccount','monthlyPaymentAmount'])ok(ev(r.ctx,`__imperioV74.isRequired('finance',${JSON.stringify(k)})`)===true,`C ${k} protegido/obrigatório`);
ok(ev(r.ctx,"v74SetFieldRequired('finance','entryAmount',false)")===false,'C não desativa valor financeiro');
ok(ev(r.ctx,"v74SetFieldRequired('finance','accountName',false)")===false,'C não desativa nome de conta');
// Opções técnicas protegidas.
for(const key of ['finance.entryDirection','finance.entryStatus','finance.accountType']){ok(ev(r.ctx,`__imperioV74.getSet(${JSON.stringify(key)}).lockedValues`)===true,`D ${key} protegido`);ok(ev(r.ctx,`__imperioV74.getSet(${JSON.stringify(key)}).allowAdd`)===false,`D ${key} não aceita valor arbitrário`)}
ok(ev(r.ctx,"__imperioV74.defaultValue('finance.entryStatus')")==='Efetivado','D status padrão Efetivado');
ok(ev(r.ctx,"__imperioV74.defaultValue('finance.accountType')")==='BANK','D nova conta padrão BANK');
let statusId=ev(r.ctx,"__imperioV74.getSet('finance.entryStatus').options.find(x=>x.value==='Previsto').id");ok(ev(r.ctx,`v73RenameOption('finance.entryStatus',${JSON.stringify(statusId)},'Agendado')`)===false,'D status técnico não renomeia');
// Lançamento manual: vencimento e descrição configuráveis.
for(const [id,val] of Object.entries({finEntryDirection:'expense',finEntryStatus:'Previsto',finEntryDate:'2026-09-28',finEntryDueDate:'',finEntryUnit:'u1',finEntryAccount:'fa1',finEntryCategory:'fc1',finEntryDesc:'',finEntryAmount:'100'}))input(r,id,val);
ok(ev(r.ctx,"v74SetFieldRequired('finance','entryDueDate',true)")===true,'E vencimento pode ser obrigatório');let v=ev(r.ctx,'__imperioV74.validateEntry()');ok(v.ok===false&&v.missing.some(x=>x.field==='entryDueDate'),'E vencimento vazio bloqueia');input(r,'finEntryDueDate','2026-10-10');v=ev(r.ctx,'__imperioV74.validateEntry()');ok(v.ok===true,'E vencimento preenchido libera');
ok(ev(r.ctx,"v74SetFieldRequired('finance','entryDescription',true)")===true,'E descrição pode ser obrigatória');v=ev(r.ctx,'__imperioV74.validateEntry()');ok(v.ok===false&&v.missing.some(x=>x.field==='entryDescription'),'E descrição vazia bloqueia');input(r,'finEntryDesc','Aluguel');v=ev(r.ctx,'__imperioV74.validateEntry()');ok(v.ok===true,'E descrição preenchida libera');
ok(ev(r.ctx,"v74SetFieldRequired('finance','entryDueDate',false)")===true,'E vencimento volta opcional');ok(ev(r.ctx,"v74SetFieldRequired('finance','entryDescription',false)")===true,'E descrição volta opcional');
// Conta financeira: empresa, instituição e formas aceitas configuráveis.
for(const [id,val] of Object.entries({finAccName:'Banco Teste',finAccType:'BANK',finAccUnit:'u1',finAccCompany:'',finAccInstitution:'',finAccInternal:'',finAccOpeningBalance:'0',finAccOpeningDate:'2026-09-28'}))input(r,id,val);r.doc._qsAll.set('.fin-acc-method:checked',[]);
ok(ev(r.ctx,"v74SetFieldRequired('finance','accountCompany',true)")===true,'F CNPJ da conta pode ser obrigatório');v=ev(r.ctx,'__imperioV74.validateAccount()');ok(v.ok===false&&v.missing.some(x=>x.field==='accountCompany'),'F conta sem empresa bloqueia quando configurado');input(r,'finAccCompany','co1');v=ev(r.ctx,'__imperioV74.validateAccount()');ok(v.ok===true,'F empresa preenchida libera');
ok(ev(r.ctx,"v74SetFieldRequired('finance','accountInstitution',true)")===true,'F instituição configurável');v=ev(r.ctx,'__imperioV74.validateAccount()');ok(v.ok===false&&v.missing.some(x=>x.field==='accountInstitution'),'F instituição vazia bloqueia');input(r,'finAccInstitution','Itaú');v=ev(r.ctx,'__imperioV74.validateAccount()');ok(v.ok===true,'F instituição preenchida libera');
ok(ev(r.ctx,"v74SetFieldRequired('finance','accountPaymentMethods',true)")===true,'F formas aceitas configuráveis como obrigatórias');v=ev(r.ctx,'__imperioV74.validateAccount()');ok(v.ok===false&&v.missing.some(x=>x.field==='accountPaymentMethods'),'F sem forma aceita bloqueia');let meth=element();meth.value='pm_pix';meth.checked=true;r.doc._qsAll.set('.fin-acc-method:checked',[meth]);v=ev(r.ctx,'__imperioV74.validateAccount()');ok(v.ok===true,'F forma aceita preenchida libera');
for(const k of ['accountCompany','accountInstitution','accountPaymentMethods'])ok(ev(r.ctx,`v74SetFieldRequired('finance',${JSON.stringify(k)},false)`)===true,`F ${k} volta opcional`);
// CNPJ / empresa: campos administrativos configuráveis.
for(const [id,val] of Object.entries({coLegalName:'Império Ltda',coTradeName:'Império',coCnpj:'',coUnit:'u1',coMunicipal:'',coTaxRegime:'',coCity:'',coState:''}))input(r,id,val);
ok(ev(r.ctx,"v74SetFieldRequired('finance','companyCnpj',true)")===true,'G CNPJ pode ser exigido pela gestão');v=ev(r.ctx,'__imperioV74.validateCompany()');ok(v.ok===false&&v.missing.some(x=>x.field==='companyCnpj'),'G CNPJ vazio bloqueia');input(r,'coCnpj','12.345.678/0001-95');v=ev(r.ctx,'__imperioV74.validateCompany()');ok(v.ok===true,'G configuração central considera CNPJ preenchido');
ok(ev(r.ctx,"v74SetFieldRequired('finance','companyMunicipalRegistration',true)")===true,'G inscrição municipal configurável');v=ev(r.ctx,'__imperioV74.validateCompany()');ok(v.ok===false&&v.missing.some(x=>x.field==='companyMunicipalRegistration'),'G IM vazia bloqueia');input(r,'coMunicipal','12345');v=ev(r.ctx,'__imperioV74.validateCompany()');ok(v.ok===true,'G IM preenchida libera');
// Conta Mensal: nota configurável; fatos econômicos não tocados.
for(const [id,val] of Object.entries({cmPayDate:'2026-09-28',cmPayMethod:'pm_pix',cmPayAccount:'fa1',cmPayAmount:'150',cmPayNote:''}))input(r,id,val);
ok(ev(r.ctx,"v74SetFieldRequired('finance','monthlyPaymentNote',true)")===true,'H observação Conta Mensal configurável');v=ev(r.ctx,'__imperioV74.validateMonthly()');ok(v.ok===false&&v.missing.some(x=>x.field==='monthlyPaymentNote'),'H observação vazia bloqueia');input(r,'cmPayNote','Pagamento setembro');v=ev(r.ctx,'__imperioV74.validateMonthly()');ok(v.ok===true,'H observação preenchida libera');ok(ev(r.ctx,"v74SetFieldRequired('finance','monthlyPaymentNote',false)")===true,'H observação volta opcional');
// Histórico financeiro não é reinterpretado pela migração/opções.
ev(r.ctx,"db.demoFinancialEntries.push({id:'hist74',unitId:'u1',date:'2025-01-01',amount:-99,nature:'Despesa histórica',category:'Categoria antiga',account:'Conta antiga',status:'Efetivado'});db.financialAccounts.push({id:'histAcc74',name:'Conta antiga',unitId:'u1',type:'BANK',active:false,openingBalance:100,openingBalanceDate:'2025-01-01',paymentMethodIds:[]})");let before=ev(r.ctx,"JSON.stringify({e:db.demoFinancialEntries.find(x=>x.id==='hist74'),a:db.financialAccounts.find(x=>x.id==='histAcc74')})");let bankId=ev(r.ctx,"__imperioV74.getSet('finance.accountType').options.find(x=>x.value==='BANK').id");ok(ev(r.ctx,`v73ToggleOption('finance.accountType',${JSON.stringify(bankId)})`)===true,'I tipo BANK pode sair de novos cadastros sem apagar fato');let after=ev(r.ctx,"JSON.stringify({e:db.demoFinancialEntries.find(x=>x.id==='hist74'),a:db.financialAccounts.find(x=>x.id==='histAcc74')})");ok(before===after,'I fato/conta histórica não reescritos');ok(ev(r.ctx,"__imperioV74.optionsHtml('finance.accountType','BANK').includes('histórico')"),'I valor inativo continua selecionável no histórico');
// Auditoria + idempotência.
ok(ev(r.ctx,"(db.auditEvents||[]).some(x=>x.module==='settings'&&x.action==='UPDATE_FIELD_REQUIRED')"),'J alterações de obrigatoriedade auditadas');
let w0=r.ls.writeCount;ok(ev(r.ctx,'__imperioV74.migrate()')===false,'K segunda migração não altera dados');ok(r.ls.writeCount===w0,'K segunda migração zero gravações');let raw=r.ls.getItem('imperio-demo-v1');let r2=run(raw);setup(r2);ok(!r2.errors.length,'K reinicialização sem erro');ok(ev(r2.ctx,'db.schemaVersion')===87,'K schema permanece 74');ok(ev(r2.ctx,"db.migrationHistory.filter(x=>(typeof x==='string'?x:x.id)==='v74-configurable-fields-options-finance').length")===1,'K migração V74 única após reinício');
console.log(JSON.stringify({ok:true,scripts:scripts.length,tests,finance:true,protectedFields:true,centralValidation:true,historicalPreservation:true,audit:true,idempotent:true}));
