const fs=require('fs'),vm=require('vm');
const html=fs.readFileSync(__dirname+'/../index.html','utf8');
const scripts=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);
class FixedDate extends Date{constructor(...a){super(...(a.length?a:['2026-09-28T10:00:00-03:00']))}static now(){return Date.parse('2026-09-28T10:00:00-03:00')}}
class MockStorage{constructor(raw){this.m=new Map(raw==null?[]:[['imperio-demo-v1',raw]]);this.writeCount=0}getItem(k){return this.m.has(k)?this.m.get(k):null}setItem(k,v){this.writeCount++;this.m.set(k,String(v))}removeItem(k){this.m.delete(k)}clear(){this.m.clear()}}
function element(id=''){return {id,value:'',checked:false,innerHTML:'',textContent:'',style:{},dataset:{},children:[],options:[],selectedIndex:0,className:'',src:'',href:'',files:[],disabled:false,firstChild:null,parentNode:null,classList:{add(){},remove(){},toggle(){return false},contains(){return false}},appendChild(x){this.children.push(x);x.parentNode=this;return x},insertBefore(x){this.children.unshift(x);x.parentNode=this;return x},remove(){},click(){},focus(){},select(){},insertAdjacentElement(){},insertAdjacentHTML(){},addEventListener(){},removeEventListener(){},querySelector(){return null},querySelectorAll(){return[]},closest(){return null},contains(){return false},setAttribute(){},getAttribute(){return null}}}
function run(raw){const els=new Map(),qsAll=new Map();const doc={body:element('body'),documentElement:element('html'),_qsAll:qsAll,getElementById(id){if(!els.has(id))els.set(id,element(id));return els.get(id)},querySelector(){return null},querySelectorAll(sel){return qsAll.get(sel)||[]},createElement(tag){return element(tag)},addEventListener(){},removeEventListener(){}};const ls=new MockStorage(raw),ss=new MockStorage(null);const ctx={console,localStorage:ls,sessionStorage:ss,document:doc,window:null,navigator:{clipboard:{writeText:async()=>{}}},location:{},history:{},setTimeout:(f)=>{try{f()}catch{}},clearTimeout(){},setInterval(){return 1},clearInterval(){},structuredClone:global.structuredClone,Date:FixedDate,JSON,Math,Number,String,Array,Object,Map,Set,Intl,RegExp,Promise,Blob:function(){},FileReader:function(){},URL:{createObjectURL:()=>'',revokeObjectURL(){}},confirm:()=>true,prompt:()=>'',alert:()=>{},fetch:async()=>({ok:false,json:async()=>({})}),event:{target:null}};ctx.window=ctx;vm.createContext(ctx);const errors=[];for(let i=0;i<scripts.length;i++){try{vm.runInContext(scripts[i],ctx,{filename:`script${i}.js`})}catch(e){errors.push(`script ${i}: ${e.stack||e}`);break}}return {ctx,ls,ss,els,doc,errors}}
function ev(ctx,code){return vm.runInContext(code,ctx)}
function assert(c,m){if(!c)throw new Error(m)}let tests=0;function ok(c,m){tests++;assert(c,m)}function moneyEq(a,b,m){ok(Math.abs(Number(a)-Number(b))<.011,`${m}: ${a} != ${b}`)}
function hist(){return ['v58-legacy-commission-unit-tip-money-hardening','v59-reports-services-stock','v60-reports-finance-dre','v61-finance-dre-stabilization','v62-reports-marketing','v63-settings-users-operators','v64-audit-core-critical-events','v65-executive-overview','v66-notifications-management-tasks','v67-custom-user-permissions','v68-fiscal-foundation','v69-nfse-national-direct','v70-agenda-operational-metrics','v71-configurable-fields-options-clients','v72-configurable-fields-options-agenda-commands','v73-configurable-fields-options-professionals-stock','v74-configurable-fields-options-finance'].map(id=>({id}))}
function baseDb(){return {schemaVersion:74,migrationHistory:hist(),units:[{id:'u1',name:'Unidade A',active:true},{id:'u2',name:'Unidade B',active:true}],categories:[{id:'cat1',name:'Categoria 1',active:true},{id:'cat2',name:'Categoria 2',active:true}],services:[{id:'s1',name:'Serviço A',category:'cat1',price:40,duration:60,active:true,proRules:{p1:{enabled:true,commission:0}}},{id:'s2',name:'Serviço B',category:'cat2',price:40,duration:60,active:true,proRules:{p2:{enabled:true,commission:0}}}],pros:[{id:'p1',name:'Pro 1',active:true,units:['u1','u2']},{id:'p2',name:'Pro 2',active:true,units:['u1','u2']}],clients:[{id:'c1',name:'Cliente 1',phone:'319'}],bookings:[],clientAppointments:[],clientCommands:[],commissionEvents:[],remunerationRules:[],tipMovements:[],tipDeductionRules:[],paymentMethods:[],financialAccounts:[],demoCashMovements:[],demoFinancialEntries:[],clientCreditMovements:[],clientReceivables:[],clientReceivablePayments:[],cashSessions:[],stockInputCosts:[],stockPurchases:[],stockMovements:[],stockTransfers:[],stockFamilies:[],stockSubstitutions:[],stockProducts:[],stockBalances:[],stockRequests:[],professionalDailyWork:[],commissionPayments:[],commissionAdjustments:[],commissionSettlements:[],professionalCommissionAdjustments:[],reportSettings:{inactiveDays:90,returnLateGraceDays:7,capacityProductivityFactor:95},combos:[],financeCategories:[],companyEntities:[],financeGoals:[],commissionSettings:{discountsReduceBase:true,directPaymentReducesSettlement:true,comboAllocation:'proportional'}}}
function command({id='cmd1',unit='u1',date='2026-09-10',lines,combo=[],partnership={enabled:false},total}){let serviceLines=lines.map((x,i)=>({lineId:x.lineId||`l${i+1}`,serviceId:x.serviceId,serviceName:x.serviceName||x.serviceId,categoryId:x.categoryId,categoryName:x.categoryName||x.categoryId,qty:1,gross:x.gross,manualDiscount:x.manual||0,netBeforeCombo:x.gross-(x.manual||0),comboDiscount:x.combo||0,netCommercial:x.net,professionalId:x.proId||'p1',professionalName:x.proId==='p2'?'Pro 2':'Pro 1',unitId:unit,unitName:unit==='u2'?'Unidade B':'Unidade A',commission:x.commission==null?null:{amount:x.commission,base:x.net,pct:x.net?x.commission/x.net*100:0}}));return {id,status:'Pago',date,unitId:unit,clientId:'c1',total:total??serviceLines.reduce((s,x)=>s+x.net,0),lines:serviceLines.map(x=>({id:x.lineId,type:'service',serviceId:x.serviceId,name:x.serviceName,professionalId:x.professionalId,professionalName:x.professionalName,qty:1,unitPrice:x.gross,discount:x.manualDiscount})),historySnapshot:{serviceLines,comboApplications:combo,partnership,unitId:unit,date},partnershipSnapshot:partnership,partnership}}
function F(unit='all'){return {from:'2026-09-01',to:'2026-09-30',unit}}
function cat(d,id){return d.categories.find(x=>x.category===id)}

// A. Runtime/version.
let r=run(JSON.stringify(baseDb()));ok(!r.errors.length,'A runtime');ok(scripts.length===50,'A 38 scripts');ok(ev(r.ctx,'db.schemaVersion')===87,'A schema75');ok(ev(r.ctx,"db.migrationHistory.filter(x=>(typeof x==='string'?x:x.id)==='v75-dre-combo-profitability-allocation').length")===1,'A migração única');

// Combo cenário 1: 40+40 => 65; combo não é dedução DRE.
{
 let d=baseDb();d.clientCommands=[command({lines:[{serviceId:'s1',serviceName:'Serviço A',categoryId:'cat1',gross:40,combo:7.5,net:32.5},{serviceId:'s2',serviceName:'Serviço B',categoryId:'cat2',gross:40,combo:7.5,net:32.5}],combo:[{name:'Combo',price:65,base:80,discount:15,picks:['l1','l2']}],total:65})];let x=run(JSON.stringify(d));ok(!x.errors.length,'B runtime');let dre=ev(x.ctx,`financeDreDataV40(${JSON.stringify(F())})`);moneyEq(dre.serviceGross,65,'B receita serviços realizada');moneyEq(dre.netRevenue,65,'B receita líquida');moneyEq(dre.comboCommercialDifference,15,'B diferença combo informativa');moneyEq(dre.comboDreDeduction,0,'B dedução combo zero');moneyEq(dre.discounts,0,'B descontos DRE zero');moneyEq(dre.categories.reduce((s,c)=>s+c.net,0),65,'B conservação receita categorias');
}
// Combo cenário 2: 45+35 => 65, distribuição soma exatamente 65.
{
 let d=baseDb();d.services[0].price=45;d.services[1].price=35;d.clientCommands=[command({lines:[{serviceId:'s1',serviceName:'Serviço A',categoryId:'cat1',gross:45,combo:8.44,net:36.56},{serviceId:'s2',serviceName:'Serviço B',categoryId:'cat2',gross:35,combo:6.56,net:28.44}],combo:[{name:'Combo',price:65,base:80,discount:15,picks:['l1','l2']}],total:65})];let x=run(JSON.stringify(d));let dre=ev(x.ctx,`financeDreDataV40(${JSON.stringify(F())})`);moneyEq(dre.netRevenue,65,'C net65');moneyEq(cat(dre,'cat1').net+cat(dre,'cat2').net,65,'C distribuição65');moneyEq(dre.serviceTableReference-dre.comboCommercialDifference,65,'C tabela menos diferença combo=preço comercial');
}
// Combo cenário 3: preço combo 65 + desconto manual adicional 5 => realizado 60.
{
 let d=baseDb();d.clientCommands=[command({lines:[{serviceId:'s1',serviceName:'Serviço A',categoryId:'cat1',gross:40,manual:5,combo:7.5,net:27.5},{serviceId:'s2',serviceName:'Serviço B',categoryId:'cat2',gross:40,manual:0,combo:7.5,net:32.5}],combo:[{name:'Combo',price:65,base:80,discount:15,picks:['l1','l2']}],total:60})];let x=run(JSON.stringify(d));let dre=ev(x.ctx,`financeDreDataV40(${JSON.stringify(F())})`);moneyEq(dre.serviceGross,65,'D preço comercial combo');moneyEq(dre.manualDiscountTotal,5,'D manual separado');moneyEq(dre.comboCommercialDifference,15,'D combo informativo');moneyEq(dre.discounts,5,'D apenas manual na dedução');moneyEq(dre.netRevenue,60,'D realizado60');
}
// Combo cenário 4: profissionais diferentes; serviços e comissões preservados.
{
 let d=baseDb();d.clientCommands=[command({lines:[{serviceId:'s1',serviceName:'Serviço A',categoryId:'cat1',gross:40,combo:7.5,net:32.5,proId:'p1',commission:10},{serviceId:'s2',serviceName:'Serviço B',categoryId:'cat2',gross:40,combo:7.5,net:32.5,proId:'p2',commission:20}],combo:[{name:'Combo',price:65,base:80,discount:15,picks:['l1','l2']}],total:65})];d.commissionEvents=[{id:'e1',commandId:'cmd1',lineId:'l1',date:'2026-09-10',unitId:'u1',professionalId:'p1',professionalName:'Pro 1',amount:10,base:32.5,pct:30.769},{id:'e2',commandId:'cmd1',lineId:'l2',date:'2026-09-10',unitId:'u1',professionalId:'p2',professionalName:'Pro 2',amount:20,base:32.5,pct:61.538}];let x=run(JSON.stringify(d));let dre=ev(x.ctx,`financeDreDataV40(${JSON.stringify(F())})`);moneyEq(dre.netRevenue,65,'E receita65');moneyEq(dre.commissions,30,'E comissão total');moneyEq(cat(dre,'cat1').commissions,10,'E comissão cat1');moneyEq(cat(dre,'cat2').commissions,20,'E comissão cat2');ok(Object.keys(cat(dre,'cat1').services).includes('Serviço A')&&Object.keys(cat(dre,'cat2').services).includes('Serviço B'),'E serviços separados');
}
// Rateio cenário A: 30/70 em 100; despesas 40 => 12/28.
{
 let d=baseDb();d.clientCommands=[command({id:'a1',lines:[{serviceId:'s1',serviceName:'Serviço A',categoryId:'cat1',gross:30000,net:30000}],total:30000}),command({id:'a2',lines:[{serviceId:'s2',serviceName:'Serviço B',categoryId:'cat2',gross:70000,net:70000}],total:70000})];d.demoFinancialEntries=[{id:'op',unitId:'u1',date:'2026-09-15',amount:-40000,nature:'Despesa operacional',category:'Aluguel',dreImpact:true,status:'Efetivado'}];let x=run(JSON.stringify(d));let dre=ev(x.ctx,`financeDreDataV40(${JSON.stringify(F('u1'))})`);moneyEq(dre.rateableExpenseTotal,40000,'F pool40');moneyEq(cat(dre,'cat1').operatingExpenseAllocated,12000,'F cat1 12');moneyEq(cat(dre,'cat2').operatingExpenseAllocated,28000,'F cat2 28');moneyEq(dre.rateableExpenseAllocatedTotal,40000,'F conservação40');moneyEq(dre.rateabilityConservationDiff,0,'F diff0');
}
// Rateio cenário B: multiunidade feito unidade por unidade.
{
 let d=baseDb();d.clientCommands=[command({id:'u1a',unit:'u1',lines:[{serviceId:'s1',serviceName:'Serviço A',categoryId:'cat1',gross:30000,net:30000}],total:30000}),command({id:'u1b',unit:'u1',lines:[{serviceId:'s2',serviceName:'Serviço B',categoryId:'cat2',gross:70000,net:70000}],total:70000}),command({id:'u2a',unit:'u2',lines:[{serviceId:'s1',serviceName:'Serviço A',categoryId:'cat1',gross:10000,net:10000}],total:10000}),command({id:'u2b',unit:'u2',lines:[{serviceId:'s2',serviceName:'Serviço B',categoryId:'cat2',gross:40000,net:40000}],total:40000})];d.demoFinancialEntries=[{id:'op1',unitId:'u1',date:'2026-09-15',amount:-40000,nature:'Despesa operacional',category:'Aluguel',dreImpact:true,status:'Efetivado'},{id:'op2',unitId:'u2',date:'2026-09-15',amount:-15000,nature:'Despesa operacional',category:'Aluguel',dreImpact:true,status:'Efetivado'}];let x=run(JSON.stringify(d));let a=ev(x.ctx,`financeDreDataV40(${JSON.stringify(F('u1'))})`),b=ev(x.ctx,`financeDreDataV40(${JSON.stringify(F('u2'))})`),all=ev(x.ctx,`financeDreDataV40(${JSON.stringify(F())})`);moneyEq(cat(a,'cat1').operatingExpenseAllocated,12000,'G u1 cat1');moneyEq(cat(b,'cat1').operatingExpenseAllocated,3000,'G u2 cat1');moneyEq(cat(all,'cat1').operatingExpenseAllocated,15000,'G consolidado cat1 soma unidades');moneyEq(cat(all,'cat2').operatingExpenseAllocated,40000,'G consolidado cat2 soma unidades');moneyEq(all.rateableExpenseAllocatedTotal,55000,'G total55');moneyEq(all.rateabilityConservationDiff,0,'G conservação');
}
// Rateio cenário C: zero base sem NaN/Infinity e sem coeficiente inventado.
{
 let d=baseDb();d.demoFinancialEntries=[{id:'op',unitId:'u1',date:'2026-09-15',amount:-1000,nature:'Despesa operacional',category:'Aluguel',dreImpact:true,status:'Efetivado'}];let x=run(JSON.stringify(d));let dre=ev(x.ctx,`financeDreDataV40(${JSON.stringify(F('u1'))})`);moneyEq(dre.rateableExpenseTotal,1000,'H pool');moneyEq(dre.rateableExpenseAllocatedTotal,0,'H allocated0');moneyEq(dre.unallocatedRateableExpense,1000,'H unallocated1000');ok(dre.rateabilityConservationDiff===null,'H diff null sem base');ok(!JSON.stringify(dre).includes('NaN')&&!JSON.stringify(dre).includes('Infinity'),'H sem NaN/Infinity');
}
// Rateio cenário D: combo entra na base por 65, não 80.
{
 let d=baseDb();d.clientCommands=[command({lines:[{serviceId:'s1',serviceName:'Serviço A',categoryId:'cat1',gross:40,combo:7.5,net:32.5},{serviceId:'s2',serviceName:'Serviço B',categoryId:'cat2',gross:40,combo:7.5,net:32.5}],combo:[{name:'Combo',price:65,base:80,discount:15,picks:['l1','l2']}],total:65})];d.demoFinancialEntries=[{id:'op',unitId:'u1',date:'2026-09-15',amount:-650,nature:'Despesa operacional',category:'Aluguel',dreImpact:true,status:'Efetivado'}];let x=run(JSON.stringify(d));let dre=ev(x.ctx,`financeDreDataV40(${JSON.stringify(F('u1'))})`);moneyEq(dre.rateableRevenueBase,65,'I base combo65');moneyEq(dre.categories.reduce((s,c)=>s+c.operatingExpenseAllocated,0),650,'I despesa conservada');
}
// Rateio cenário E: custo direto não reaparece no bolo de despesas operacionais.
{
 let d=baseDb();d.clientCommands=[command({lines:[{serviceId:'s1',serviceName:'Serviço A',categoryId:'cat1',gross:100,net:100,commission:10}],total:100})];d.commissionEvents=[{id:'e1',commandId:'cmd1',lineId:'l1',date:'2026-09-10',unitId:'u1',professionalId:'p1',professionalName:'Pro 1',amount:10,base:100,pct:10}];d.stockInputCosts=[{id:'in1',date:'2026-09-10',unitId:'u1',categoryId:'cat1',value:5}];d.demoFinancialEntries=[{id:'dupcomm',unitId:'u1',date:'2026-09-15',amount:-100,nature:'Comissões',category:'Comissões',dreImpact:true,rateableOperatingExpense:true,status:'Efetivado'},{id:'op',unitId:'u1',date:'2026-09-15',amount:-40,nature:'Despesa operacional',category:'Aluguel',dreImpact:true,status:'Efetivado'}];let x=run(JSON.stringify(d));let dre=ev(x.ctx,`financeDreDataV40(${JSON.stringify(F('u1'))})`),c=cat(dre,'cat1');moneyEq(c.commissions,10,'J comissão direta');moneyEq(c.inputs,5,'J insumo direto');moneyEq(dre.expenseTotal,140,'J DRE principal preserva despesas classificadas');moneyEq(dre.rateableExpenseTotal,40,'J pool exclui comissão já direta');moneyEq(c.operatingExpenseAllocated,40,'J somente op rateada');moneyEq(c.resultAfterAllocation,c.contribution-40,'J resultado após rateio');
}
// Modelo/parceria permanece redução separada; combo continua fora da dedução.
{
 let d=baseDb(),part={enabled:true,chargedValue:50,commissionBaseMode:'full'};d.clientCommands=[command({lines:[{serviceId:'s1',serviceName:'Serviço A',categoryId:'cat1',gross:40,combo:7.5,net:32.5},{serviceId:'s2',serviceName:'Serviço B',categoryId:'cat2',gross:40,combo:7.5,net:32.5}],combo:[{name:'Combo',price:65,base:80,discount:15,picks:['l1','l2']}],partnership:part,total:50})];let x=run(JSON.stringify(d));let dre=ev(x.ctx,`financeDreDataV40(${JSON.stringify(F())})`);moneyEq(dre.serviceGross,65,'K combo price65');moneyEq(dre.partnershipDiscount,15,'K parceria15');moneyEq(dre.comboCommercialDifference,15,'K combo diff15');moneyEq(dre.discounts,15,'K só parceria dedução');moneyEq(dre.netRevenue,50,'K realizado50');
}
// Conservação consolidada: resultado por unidades soma o consolidado principal.
{
 let d=baseDb();d.clientCommands=[command({id:'u1',unit:'u1',lines:[{serviceId:'s1',serviceName:'Serviço A',categoryId:'cat1',gross:100,net:100}],total:100}),command({id:'u2',unit:'u2',lines:[{serviceId:'s1',serviceName:'Serviço A',categoryId:'cat1',gross:50,net:50}],total:50})];d.demoFinancialEntries=[{id:'o1',unitId:'u1',date:'2026-09-10',amount:-20,nature:'Despesa operacional',category:'Aluguel',dreImpact:true},{id:'o2',unitId:'u2',date:'2026-09-10',amount:-10,nature:'Despesa operacional',category:'Aluguel',dreImpact:true}];let x=run(JSON.stringify(d));let a=ev(x.ctx,`financeDreDataV40(${JSON.stringify(F('u1'))})`),b=ev(x.ctx,`financeDreDataV40(${JSON.stringify(F('u2'))})`),all=ev(x.ctx,`financeDreDataV40(${JSON.stringify(F())})`);moneyEq(a.netRevenue+b.netRevenue,all.netRevenue,'L receita unidades=consolidado');moneyEq(a.expenseTotal+b.expenseTotal,all.expenseTotal,'L despesas unidades=consolidado');moneyEq(a.operatingResult+b.operatingResult,all.operatingResult,'L resultado unidades=consolidado');
}
// Render DRE: não pode trazer dedução "combos"; rateio e explicação devem aparecer.
{
 let d=baseDb();d.clientCommands=[command({lines:[{serviceId:'s1',serviceName:'Serviço A',categoryId:'cat1',gross:40,combo:7.5,net:32.5},{serviceId:'s2',serviceName:'Serviço B',categoryId:'cat2',gross:40,combo:7.5,net:32.5}],combo:[{name:'Combo',price:65,base:80,discount:15,picks:['l1','l2']}],total:65})];let x=run(JSON.stringify(d));x.doc.getElementById('dreFrom').value='2026-09-01';x.doc.getElementById('dreTo').value='2026-09-30';x.doc.getElementById('dreUnit').value='u1';x.ctx.financeDreBody=x.doc.getElementById('financeDreBody');ev(x.ctx,'renderFinanceDreBody()');let h=x.doc.getElementById('financeDreBody').innerHTML;ok(h.includes('Diferença comercial de combos')&&h.includes('fora da DRE'),'M combo informativo');ok(!h.includes('(−) Descontos e combos'),'M sem dedução combo antiga');ok(h.includes('Despesas operacionais rateadas')&&h.includes('Resultado após rateio'),'M rentabilidade rateada');
}
// Idempotência e nenhuma persistência de rateio.
{
 let d=baseDb();let x=run(JSON.stringify(d)),w=x.ls.writeCount;ok(ev(x.ctx,'__imperioV75.migrate()')===false,'N segunda migração sem mudança');ok(x.ls.writeCount===w,'N zero gravações segunda migração');ok(ev(x.ctx,"db.systemSettings?.dreRateio===undefined"),'N rateio não persistido');
}

// O. Relatório de Serviços preserva combo como redução comercial informativa e reconcilia receita com a DRE.
{
 let d=baseDb();d.clientCommands=[command({lines:[{serviceId:'s1',serviceName:'Serviço A',categoryId:'cat1',gross:40,combo:7.5,net:32.5},{serviceId:'s2',serviceName:'Serviço B',categoryId:'cat2',gross:40,combo:7.5,net:32.5}],combo:[{name:'Combo',price:65,base:80,discount:15,picks:['l1','l2']}],total:65})];let x=run(JSON.stringify(d));let f={from:'2026-09-01',to:'2026-09-30',unit:'u1',professional:'all',category:'all',service:'all',origin:'all',source:'all',combo:'all',partnership:'all',commercial:'all'};let m=ev(x.ctx,`__imperioV59Services.v59ServiceMetrics(${JSON.stringify(f)})`),dre=ev(x.ctx,`financeDreDataV40(${JSON.stringify(F('u1'))})`);moneyEq(m.revenue,65,'O Serviços receita real65');moneyEq(m.combo,15,'O Serviços mantém diferença combo15');moneyEq(m.revenue,dre.categories.reduce((s,c)=>s+c.net,0),'O Serviços reconcilia com DRE');
}
// P. Snapshot histórico de categoria prevalece sobre cadastro atual alterado.
{
 let d=baseDb();d.services.find(s=>s.id==='s1').category='cat2';d.clientCommands=[command({lines:[{serviceId:'s1',serviceName:'Serviço histórico',categoryId:'cat1',categoryName:'Categoria histórica',gross:100,net:100}],total:100})];let x=run(JSON.stringify(d));let dre=ev(x.ctx,`financeDreDataV40(${JSON.stringify(F('u1'))})`);ok(!!cat(dre,'cat1'),'P categoria snapshot presente');ok(!cat(dre,'cat2'),'P cadastro atual não reclassifica passado');moneyEq(cat(dre,'cat1').net,100,'P receita histórica categoria original');
}
// Q. Filtro de período exclui fatos fora do recorte, inclusive despesas rateáveis.
{
 let d=baseDb();d.clientCommands=[command({id:'in',date:'2026-09-10',lines:[{serviceId:'s1',serviceName:'Serviço A',categoryId:'cat1',gross:100,net:100}],total:100}),command({id:'out',date:'2026-08-10',lines:[{serviceId:'s2',serviceName:'Serviço B',categoryId:'cat2',gross:999,net:999}],total:999})];d.demoFinancialEntries=[{id:'ein',unitId:'u1',date:'2026-09-15',amount:-20,nature:'Aluguel',category:'Aluguel',dreImpact:true},{id:'eout',unitId:'u1',date:'2026-08-15',amount:-999,nature:'Aluguel',category:'Aluguel',dreImpact:true}];let x=run(JSON.stringify(d));let dre=ev(x.ctx,`financeDreDataV40(${JSON.stringify(F('u1'))})`);moneyEq(dre.netRevenue,100,'Q receita apenas período');moneyEq(dre.rateableExpenseTotal,20,'Q despesa rateável apenas período');
}
// R. CMV continua custo direto na DRE e não entra novamente no bolo de rateio operacional.
{
 let d=baseDb(),c=command({lines:[{serviceId:'s1',serviceName:'Serviço A',categoryId:'cat1',gross:100,net:100}],total:150});c.lines.push({id:'prod',type:'product',productId:'prod1',name:'Produto',qty:1,unitPrice:50,discount:0,stockCostSnapshot:20});c.productCmv=20;d.clientCommands=[c];d.demoFinancialEntries=[{id:'op',unitId:'u1',date:'2026-09-15',amount:-40,nature:'Aluguel',category:'Aluguel',dreImpact:true},{id:'cmvdup',unitId:'u1',date:'2026-09-15',amount:-20,nature:'CMV produto',category:'CMV',dreImpact:true}];let x=run(JSON.stringify(d));let dre=ev(x.ctx,`financeDreDataV40(${JSON.stringify(F('u1'))})`);moneyEq(dre.productCmv,20,'R CMV direto preservado');moneyEq(dre.productRevenue,50,'R receita produto preservada');moneyEq(dre.rateableExpenseTotal,40,'R CMV não rateado novamente');moneyEq(cat(dre,'cat1').operatingExpenseAllocated,40,'R somente despesa operacional alocada');
}
// S. Impostos/tributos, transferências e compras capitalizadas não entram na base rateável.
{
 let d=baseDb();d.clientCommands=[command({lines:[{serviceId:'s1',serviceName:'Serviço A',categoryId:'cat1',gross:100,net:100}],total:100})];d.demoFinancialEntries=[{id:'op',unitId:'u1',date:'2026-09-15',amount:-25,nature:'Aluguel',category:'Aluguel',dreImpact:true},{id:'tax',unitId:'u1',date:'2026-09-15',amount:-10,nature:'Imposto municipal',category:'Tributos',dreImpact:true},{id:'tr',unitId:'u1',date:'2026-09-15',amount:-30,nature:'Transferência interna',category:'Transferência',dreImpact:false},{id:'stock',unitId:'u1',date:'2026-09-15',amount:-50,nature:'Compra de estoque',category:'Estoque / Fornecedor',dreImpact:false}];let x=run(JSON.stringify(d));let dre=ev(x.ctx,`financeDreDataV40(${JSON.stringify(F('u1'))})`);moneyEq(dre.rateableExpenseTotal,25,'S somente operacional rateável');
}

console.log(JSON.stringify({ok:true,scripts:scripts.length,tests,combo:true,allocation:true,multiunit:true,zeroSafe:true,noDoubleAllocation:true,conservation:true,idempotent:true}));
