const fs=require('fs'),vm=require('vm');
const html=fs.readFileSync(__dirname+'/../index.html','utf8');
const scripts=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);
class FixedDate extends Date{constructor(...a){super(...(a.length?a:['2026-09-27T18:00:00-03:00']))}static now(){return Date.parse('2026-09-27T18:00:00-03:00')}}
class MockStorage{constructor(raw){this.m=new Map(raw==null?[]:[['imperio-demo-v1',raw]]);this.writeCount=0}getItem(k){return this.m.has(k)?this.m.get(k):null}setItem(k,v){this.writeCount++;this.m.set(k,String(v))}removeItem(k){this.m.delete(k)}clear(){this.m.clear()}}
function element(id=''){
 return {id,value:'',checked:false,innerHTML:'',textContent:'',style:{},dataset:{},children:[],options:[],selectedIndex:0,className:'',src:'',href:'',files:[],disabled:false,
 classList:{add(){},remove(){},toggle(){return false},contains(){return false}},appendChild(x){this.children.push(x);return x},remove(){},click(){},focus(){},select(){},insertAdjacentElement(){},insertAdjacentHTML(){},addEventListener(){},removeEventListener(){},querySelector(){return null},querySelectorAll(){return[]},closest(){return null},contains(){return false},setAttribute(){},getAttribute(){return null}};
}
function run(raw){
 const els=new Map();
 const doc={body:element('body'),documentElement:element('html'),getElementById(id){if(!els.has(id))els.set(id,element(id));return els.get(id)},querySelector(){return null},querySelectorAll(){return[]},createElement(tag){return element(tag)},addEventListener(){},removeEventListener(){}};
 const ls=new MockStorage(raw);
 let toasts=[];
 const ctx={console,localStorage:ls,document:doc,window:null,navigator:{clipboard:{writeText:async()=>{}}},location:{},history:{},
 setTimeout:(f)=>{try{f()}catch{}},clearTimeout(){},setInterval(){return 1},clearInterval(){},structuredClone:global.structuredClone,Date:FixedDate,JSON,Math,Number,String,Array,Object,Map,Set,Intl,RegExp,Promise,Blob:function(){},FileReader:function(){},URL:{createObjectURL:()=>'',revokeObjectURL(){}},confirm:()=>true,prompt:()=>'',alert:()=>{},fetch:async()=>({ok:false,json:async()=>({})})};
 ctx.window=ctx;vm.createContext(ctx);ctx.__testToasts=toasts;
 const errors=[];
 for(let i=0;i<scripts.length;i++){try{vm.runInContext(scripts[i],ctx,{filename:`script${i}.js`})}catch(e){errors.push(`script ${i}: ${e.stack||e}`);break}}
 try{vm.runInContext(`toast=function(m){__testToasts.push(String(m))}`,ctx)}catch{}
 try{vm.runInContext(`if(window.__imperioV63){let a=(db.userAccounts||[]).find(u=>u.role==='admin'&&u.active!==false);if(a)__imperioV63.sessionSet(a.id)}`,ctx)}catch{}
 return {ctx,ls,els,errors,toasts};
}
function assert(c,m){if(!c)throw new Error(m)}
function ev(ctx,code){return vm.runInContext(code,ctx)}


function baseDb(){return {schemaVersion:58,migrationHistory:[{id:'v58-legacy-commission-unit-tip-money-hardening'}],units:[{id:'u1',name:'Big Shopping',active:true},{id:'u2',name:'Shopping Contagem',active:true},{id:'u3',name:'Centro de Contagem',active:true}],categories:[{id:'cat1',name:'Categoria A'},{id:'cat2',name:'Categoria B'}],services:[{id:'s1',name:'Serviço A',category:'cat1',price:100,duration:60,active:true,proRules:{p1:{enabled:true,commission:30}}},{id:'s2',name:'Manicure',category:'cat1',price:40,duration:45,active:true,proRules:{}},{id:'s3',name:'Pedicure',category:'cat1',price:40,duration:45,active:true,proRules:{}}],pros:[{id:'p1',name:'Pro 1',active:true,units:['u1']}],clients:[{id:'c1',name:'Cliente 1',phone:'319',origin:'Presencial',source:'Instagram'}],bookings:[],clientAppointments:[],clientCommands:[],commissionEvents:[],remunerationRules:[],tipMovements:[],tipDeductionRules:[{id:'tiprule_default_8_v1',percent:8,validFrom:'0001-01-01',validTo:'',unitId:'',active:true}],paymentMethods:[],financialAccounts:[],demoCashMovements:[],demoFinancialEntries:[],clientCreditMovements:[],clientReceivables:[],clientReceivablePayments:[],cashSessions:[],stockInputCosts:[],stockPurchases:[],stockMovements:[],stockTransfers:[],stockFamilies:[],stockSubstitutions:[],stockProducts:[],stockBalances:[],stockRequests:[],professionalDailyWork:[],commissionPayments:[],commissionAdjustments:[],commissionSettlements:[],reportSettings:{inactiveDays:90,returnLateGraceDays:7,capacityProductivityFactor:95},combos:[],financeCategories:[],companyEntities:[],financeGoals:[]}}



const F=(from='2026-09-01',to='2026-09-30',unit='all')=>({from,to,unit,professional:'all',category:'all',service:'all',origin:'all',source:'all',commercial:'all',combo:'all',partnership:'all'});
let tests=0; function ok(c,m){tests++; assert(c,m)}
function moneyEq(a,b,m){ok(Math.abs(Number(a)-Number(b))<.011,`${m}: ${a} != ${b}`)}

// A. saveFinanceAccount consolidado + aliases sem reescrever fatos históricos.
{
 let d=baseDb();d.schemaVersion=60;d.migrationHistory=[{id:'v60-reports-finance-dre'}];d.companyEntities=[{id:'co1',unitId:'u1',name:'Empresa U1'}];d.paymentMethods=[{id:'pm_card',name:'Cartão'}];d.financialAccounts=[{id:'a1',name:'Conta Antiga',previousNames:[],unitId:'u1',companyEntityId:'',type:'BANK',active:true,details:{institution:'Old','internalCode':'OLD'},openingBalance:0,openingBalanceDate:'',paymentMethodIds:[],feeRules:{}}];d.demoFinancialEntries=[{id:'hist',unitId:'u1',date:'2026-09-02',amount:10,status:'Efetivado',account:'Conta Antiga',nature:'Receita manual'}];
 let r=run(JSON.stringify(d));ok(!r.errors.length,'A runtime');
 const set=(id,val,checked)=>{let e=r.ctx.document.getElementById(id);if(val!==undefined)e.value=val;if(checked!==undefined)e.checked=checked};
 set('finAccName','Conta Nova');set('finAccUnit','u1');set('finAccCompany','co1');set('finAccType','BANK');set('finAccActive','',true);set('finAccInstitution','Banco X');set('finAccInternal','INT-9');set('finAccOpeningBalance','1000');set('finAccOpeningDate','2026-09-01');
 ev(r.ctx,`document.querySelectorAll=function(sel){return sel==='.fin-acc-method:checked'?[{value:'pm_card'}]:[]};document.querySelector=function(sel){if(sel.includes('fin-rule-percent'))return {value:'3'};if(sel.includes('fin-rule-fixed'))return {value:'1.25'};if(sel.includes('fin-rule-days'))return {value:'30'};return null};renderFinanceAccounts=function(){};closeModal=function(){}`);
 ev(r.ctx,`saveFinanceAccount('a1')`);let a=ev(r.ctx,`db.financialAccounts[0]`);ok(a.name==='Conta Nova','A name');ok(a.previousNames.includes('Conta Antiga'),'A alias');ok(a.companyEntityId==='co1','A company');moneyEq(a.openingBalance,1000,'A opening');ok(a.openingBalanceDate==='2026-09-01','A opening date');ok(a.details.institution==='Banco X'&&a.details.internalCode==='INT-9','A details');ok(a.paymentMethodIds[0]==='pm_card'&&a.feeRules.pm_card.settlementDays===30,'A fee rule');ok(ev(r.ctx,`db.demoFinancialEntries[0].account`)==='Conta Antiga','A historical name preserved');
}

// B. Opening balance + movements; date before base unknown.
{
 let d=baseDb();d.schemaVersion=60;d.migrationHistory=[{id:'v60-reports-finance-dre'}];d.financialAccounts=[{id:'bank',name:'Banco',unitId:'u1',type:'BANK',active:true,openingBalance:1000,openingBalanceDate:'2026-09-01',paymentMethodIds:[],feeRules:{}}];d.demoFinancialEntries=[{id:'e1',unitId:'u1',date:'2026-09-10',amount:500,status:'Efetivado',accountId:'bank',account:'Banco',nature:'Receita manual'},{id:'e2',unitId:'u1',date:'2026-09-20',amount:-200,status:'Efetivado',accountId:'bank',account:'Banco',nature:'Despesa manual'}];let r=run(JSON.stringify(d));ok(!r.errors.length,'B runtime');let pos=ev(r.ctx,`financeAccountPosition(db.financialAccounts[0],'2026-09-30')`);moneyEq(pos.total,1300,'B balance');let pre=ev(r.ctx,`financeAccountPosition(db.financialAccounts[0],'2026-08-31')`);ok(pre.known===false&&pre.total===null,'B pre-base unknown');
}

// C. Manual CASH fact mirrored physically: finance only once; drawer still sees mirror.
{
 let d=baseDb();d.schemaVersion=60;d.migrationHistory=[{id:'v60-reports-finance-dre'}];d.financialAccounts=[{id:'cash',name:'Caixa',unitId:'u1',type:'CASH',active:true,openingBalance:0,openingBalanceDate:'2026-09-01',paymentMethodIds:[],feeRules:{}}];d.cashSessions=[{id:'cs',unitId:'u1',date:'2026-09-10',status:'closed',openingAmount:0,closureHistory:[{id:'cl',revision:1,movementIds:['mir'],closedAt:'2026-09-10T20:00:00Z'}],lastClosureId:'cl',closedMovementIds:['mir']}];d.demoFinancialEntries=[{id:'fe',unitId:'u1',date:'2026-09-10',amount:100,status:'Efetivado',accountId:'cash',account:'Caixa',nature:'Receita manual',sourceType:'manual_finance_entry'}];d.demoCashMovements=[{id:'mir',unitId:'u1',date:'2026-09-10',amount:100,paymentMethod:'Dinheiro',accountId:'cash',account:'Caixa',type:'Receita manual',cashSessionId:'cs',financialEntryId:'fe',financialMirror:true,sourceType:'financial_entry'}];let r=run(JSON.stringify(d));ok(!r.errors.length,'C runtime');let sum=ev(r.ctx,`financeOperationalLedgerEntries().reduce((s,e)=>s+Number(e.amount||0),0)`);moneyEq(sum,100,'C finance once');moneyEq(ev(r.ctx,`financeClosedCashRows().reduce((s,e)=>s+Number(e.amount||0),0)`),0,'C mirror excluded closure');moneyEq(ev(r.ctx,`cashTotals(db.cashSessions[0].unitId,db.cashSessions[0].date).physicalExpected`),100,'C drawer mirror');
}

// D. Supply affects CASH balance, not revenue / DRE.
{
 let d=baseDb();d.schemaVersion=60;d.migrationHistory=[{id:'v60-reports-finance-dre'}];d.financialAccounts=[{id:'cash',name:'Caixa',unitId:'u1',type:'CASH',active:true,openingBalance:0,openingBalanceDate:'2026-09-01',paymentMethodIds:[],feeRules:{}}];d.demoCashMovements=[{id:'sup',unitId:'u1',date:'2026-09-10',amount:200,paymentMethod:'Dinheiro',accountId:'cash',account:'Caixa',type:'Suprimento',sourceType:'cash_supply'}];let r=run(JSON.stringify(d));ok(!r.errors.length,'D runtime');let snap=ev(r.ctx,`__imperioV61.v61AccountSnapshot(db.financialAccounts[0],'2026-09-30')`);moneyEq(snap.balanceAtCutoff,200,'D cash balance');moneyEq(ev(r.ctx,`financeOperationalLedgerEntries().reduce((s,e)=>s+Number(e.amount||0),0)`),0,'D supply ledger revenue');let dre=ev(r.ctx,`financeDreDataV40(${JSON.stringify(F())})`);moneyEq(dre.expenseTotal||0,0,'D supply DRE');
}

// E. Internal transfer creates paired entries, source/destination balances and zero consolidated result.
{
 let d=baseDb();d.schemaVersion=60;d.migrationHistory=[{id:'v60-reports-finance-dre'}];d.financialAccounts=[{id:'cash',name:'Caixa Big',unitId:'u1',type:'CASH',active:true,openingBalance:1000,openingBalanceDate:'2026-09-01',paymentMethodIds:[],feeRules:{}},{id:'bank',name:'Banco Big',unitId:'u1',type:'BANK',active:true,openingBalance:0,openingBalanceDate:'2026-09-01',paymentMethodIds:[],feeRules:{}}];d.cashSessions=[{id:'cs',unitId:'u1',date:'2026-09-27',status:'open',openingAmount:1000}];d.cashAudits=[];d.professionalCommissionAdjustments=[];let r=run(JSON.stringify(d));ok(!r.errors.length,'E runtime');r.ctx.document.getElementById('unitPicker').value='u1';ev(r.ctx,`renderCash=function(){};closeModal=function(){}`);r.ctx.document.getElementById('cashAdjAmount').value='500';r.ctx.document.getElementById('cashAdjNature').value='transfer';r.ctx.document.getElementById('cashAdjTransferAccount').value='bank';r.ctx.document.getElementById('cashAdjTransferDest').value='';r.ctx.document.getElementById('cashAdjReason').value='Depósito';ev(r.ctx,`saveCashAdjustment('Sangria')`);let pair=ev(r.ctx,`db.demoFinancialEntries.filter(x=>x.sourceType==='internal_transfer')`);ok(pair.length===2,'E pair count');ok(pair[0].transferId&&pair[0].transferId===pair[1].transferId,'E same transferId');moneyEq(pair.reduce((s,e)=>s+e.amount,0),0,'E net');moneyEq(ev(r.ctx,`financeAccountPosition(db.financialAccounts[0],'2026-09-30').total`),500,'E cash account');moneyEq(ev(r.ctx,`financeAccountPosition(db.financialAccounts[1],'2026-09-30').total`),500,'E bank account');let dre=ev(r.ctx,`financeDreDataV40(${JSON.stringify(F())})`);moneyEq(dre.expenseTotal||0,0,'E DRE zero');
}

// F. Processor gross / fee / known net; not labelled as bank-available.
{
 let d=baseDb();d.schemaVersion=60;d.migrationHistory=[{id:'v60-reports-finance-dre'}];d.financialAccounts=[{id:'proc',name:'Stone',unitId:'u1',type:'PROCESSOR',active:true,openingBalance:0,openingBalanceDate:'2026-09-01',paymentMethodIds:['pm_card'],feeRules:{pm_card:{percent:3,fixed:0,settlementDays:30}}}];d.paymentMethods=[{id:'pm_card',name:'Cartão'}];d.cashSessions=[{id:'cs',unitId:'u1',date:'2026-09-10',status:'closed',openingAmount:0,closureHistory:[{id:'cl',revision:1,movementIds:['card'],closedAt:'2026-09-10T20:00:00Z'}],lastClosureId:'cl',closedMovementIds:['card']}];d.demoCashMovements=[{id:'card',unitId:'u1',date:'2026-09-10',amount:200,grossAmount:200,processorFee:6,paymentMethod:'Cartão',paymentMethodId:'pm_card',accountId:'proc',account:'Stone',type:'Recebimento de comanda',cashSessionId:'cs',settlementReliability:'snapshot',expectedSettlementDate:'2026-10-10'}];let r=run(JSON.stringify(d));ok(!r.errors.length,'F runtime');let pos=ev(r.ctx,`financeAccountPosition(db.financialAccounts[0],'2026-09-30')`);moneyEq(pos.processedGross,200,'F gross');moneyEq(pos.fees,6,'F fee');moneyEq(pos.processorNetKnown,194,'F net');moneyEq(pos.receivable,194,'F receivable');moneyEq(pos.available,0,'F available unconfirmed');
}

// G. Finance KPI nomenclature: net after fees.
{
 let d=baseDb();d.schemaVersion=60;d.migrationHistory=[{id:'v60-reports-finance-dre'}];d.financialAccounts=[{id:'proc',name:'Stone',unitId:'u1',type:'PROCESSOR',active:true,paymentMethodIds:[],feeRules:{}},{id:'bank',name:'Banco',unitId:'u1',type:'BANK',active:true,paymentMethodIds:[],feeRules:{}}];d.cashSessions=[{id:'cs',unitId:'u1',date:'2026-09-10',status:'closed',closureHistory:[{id:'cl',revision:1,movementIds:['r'],closedAt:'x'}],lastClosureId:'cl',closedMovementIds:['r']}];d.demoCashMovements=[{id:'r',unitId:'u1',date:'2026-09-10',amount:500,grossAmount:500,processorFee:6,paymentMethod:'Cartão',accountId:'proc',account:'Stone',type:'Recebimento de comanda',cashSessionId:'cs'}];d.demoFinancialEntries=[{id:'out',unitId:'u1',date:'2026-09-12',amount:-50,status:'Efetivado',accountId:'bank',account:'Banco',nature:'Despesa manual'}];let r=run(JSON.stringify(d));ok(!r.errors.length,'G runtime');let m=ev(r.ctx,`__imperioV61.v61FinanceMetrics(${JSON.stringify(F())})`);moneyEq(m.incoming,500,'G in');moneyEq(m.outgoing,50,'G out');moneyEq(m.fees,6,'G fees');moneyEq(m.netBeforeFees,450,'G before fees');moneyEq(m.netAfterFees,444,'G after fees');moneyEq(m.net,444,'G canonical net');
}

// H. Processor settlement snapshot freezes rule; legacy movement remains unknown.
{
 let d=baseDb();d.schemaVersion=60;d.migrationHistory=[{id:'v60-reports-finance-dre'}];d.paymentMethods=[{id:'pm_card',name:'Cartão'}];d.financialAccounts=[{id:'proc',name:'Stone',unitId:'u1',type:'PROCESSOR',active:true,paymentMethodIds:['pm_card'],feeRules:{pm_card:{percent:3,fixed:0,settlementDays:30}}}];d.demoCashMovements=[{id:'legacy',unitId:'u1',date:'2026-08-01',amount:100,processorFee:3,paymentMethod:'Cartão',accountId:'proc',account:'Stone',type:'Recebimento de comanda'}];let r=run(JSON.stringify(d));ok(!r.errors.length,'H runtime');ok(ev(r.ctx,`db.demoCashMovements.find(x=>x.id==='legacy').settlementReliability`)==='unknown','H legacy unknown');ev(r.ctx,`db.demoCashMovements.push({id:'new',unitId:'u1',date:'2026-09-01',amount:200,processorFee:6,paymentMethod:'Cartão',accountId:'proc',account:'Stone'});__imperioV61.v61CaptureSettlementSnapshot(db.demoCashMovements.find(x=>x.id==='new'))`);let n=ev(r.ctx,`db.demoCashMovements.find(x=>x.id==='new')`);ok(n.settlementDaysSnapshot===30&&n.expectedSettlementDate==='2026-10-01','H snapshot date');ev(r.ctx,`db.financialAccounts[0].feeRules.pm_card.settlementDays=2`);let n2=ev(r.ctx,`db.demoCashMovements.find(x=>x.id==='new')`);ok(n2.settlementDaysSnapshot===30&&n2.expectedSettlementDate==='2026-10-01','H future rule stable');
}

// I. Payables date model: obligation, due, payment.
{
 let d=baseDb();d.schemaVersion=60;d.migrationHistory=[{id:'v60-reports-finance-dre'}];d.demoFinancialEntries=[{id:'p',unitId:'u1',amount:-100,status:'Efetivado',sourceType:'stock_purchase',obligationDate:'2026-09-01',competenceDate:'2026-09-01',dueDate:'2026-09-30',paidDate:'2026-10-05',date:'2026-10-05',dreImpact:false}];let r=run(JSON.stringify(d));ok(!r.errors.length,'I runtime');let a=ev(r.ctx,`__imperioV61.v61Payables(${JSON.stringify(F('2026-09-01','2026-09-15'))})`);ok(a.length===1&&!a[0].overdue,'I 15 open not overdue');let b=ev(r.ctx,`__imperioV61.v61Payables(${JSON.stringify(F('2026-09-01','2026-09-30'))})`);ok(b.length===1&&!b[0].overdue,'I 30 open');let c=ev(r.ctx,`__imperioV61.v61Payables(${JSON.stringify(F('2026-09-01','2026-10-01'))})`);ok(c.length===1&&c[0].overdue,'I Oct1 overdue');let e=ev(r.ctx,`__imperioV61.v61Payables(${JSON.stringify(F('2026-09-01','2026-10-05'))})`);ok(e.length===0,'I paid cutoff');
}

// J. Manual predicted entry preserves obligation date separately from due date.
{
 let d=baseDb();d.schemaVersion=60;d.migrationHistory=[{id:'v60-reports-finance-dre'}];d.financeCategories=[{id:'fc',name:'Aluguel',dre:true}];d.financialAccounts=[{id:'bank',name:'Banco',unitId:'u1',type:'BANK',active:true,paymentMethodIds:[],feeRules:{}}];let r=run(JSON.stringify(d));ok(!r.errors.length,'J runtime');const set=(id,v)=>r.ctx.document.getElementById(id).value=v;set('finEntryDirection','expense');set('finEntryAmount','500');set('finEntryUnit','u1');set('finEntryAccount','bank');set('finEntryCategory','fc');set('finEntryStatus','Previsto');set('finEntryDate','2026-09-20');set('finEntryDueDate','2026-10-05');set('finEntryDesc','Aluguel setembro');ev(r.ctx,`renderFinance=function(){};closeModal=function(){};saveFinanceEntry()`);let e=ev(r.ctx,`db.demoFinancialEntries.find(x=>x.sourceType==='manual_finance_entry')`);ok(e.obligationDate==='2026-09-20'&&e.competenceDate==='2026-09-20','J obligation');ok(e.dueDate==='2026-10-05'&&e.paidDate==='','J due/paid');
}

// K. Conta Mensal Big received in Centro/processor: economic vs treasury unit + frozen settlement.
{
 let d=baseDb();d.schemaVersion=60;d.migrationHistory=[{id:'v60-reports-finance-dre'}];d.paymentMethods=[{id:'pm_card',name:'Cartão'}];d.financialAccounts=[{id:'proc3',name:'Stone Centro',unitId:'u3',type:'PROCESSOR',active:true,paymentMethodIds:['pm_card'],feeRules:{pm_card:{percent:3,fixed:0,settlementDays:30}}}];d.clients=[{id:'c1',name:'Cliente',phone:'1'}];d.clientReceivables=[{id:'rec',clientId:'c1',clientName:'Cliente',commandId:'cmd',unitId:'u1',date:'2026-09-01',dueDate:'2026-09-30',originalAmount:100,balance:100,status:'Em aberto'}];d.cashSessions=[{id:'cs3',unitId:'u3',date:'2026-09-15',status:'open',openingAmount:0}];let r=run(JSON.stringify(d));ok(!r.errors.length,'K runtime');const set=(id,v)=>r.ctx.document.getElementById(id).value=v;set('cmPayAmount','100');set('cmPayDate','2026-09-15');set('cmPayMethod','pm_card');set('cmPayAccount','proc3');set('cmPayNote','');ev(r.ctx,`openClient=function(){};closeModal=function(){};saveClientMonthlySettlement('c1')`);let pay=ev(r.ctx,`db.clientReceivablePayments[0]`),cash=ev(r.ctx,`db.demoCashMovements.find(x=>x.sourceType==='client_receivable_settlement')`);ok(pay.receivingUnitId==='u3'&&pay.allocationByUnit.some(x=>x.unitId==='u1'&&x.amount===100),'K unit separation');ok(cash.unitId==='u3'&&cash.allocationByUnit.some(x=>x.unitId==='u1'&&x.amount===100),'K cash units');ok(pay.settlementDaysSnapshot===30&&pay.expectedSettlementDate==='2026-10-15'&&pay.settlementReliability==='snapshot','K settlement snapshot');
}

// L. Inactive account and inactive unit remain visible historically; consolidated reconciles.
{
 let d=baseDb();d.schemaVersion=60;d.migrationHistory=[{id:'v60-reports-finance-dre'}];d.units=[{id:'u1',name:'Big',active:false},{id:'u2',name:'Centro',active:true},{id:'u3',name:'Outro',active:true}];d.financialAccounts=[{id:'old',name:'Banco Antigo',unitId:'u1',type:'BANK',active:false,openingBalance:0,openingBalanceDate:'2026-09-01',paymentMethodIds:[],feeRules:{}}];d.demoFinancialEntries=[{id:'f',unitId:'u1',date:'2026-09-10',amount:50,status:'Efetivado',accountId:'old',account:'Banco Antigo',nature:'Receita manual'}];d.clientCommands=[{id:'cmd',status:'Pago',date:'2026-09-10',unitId:'u1',clientId:'c1',lines:[{id:'l',type:'service',serviceId:'s1',name:'Serviço A',professionalId:'p1',qty:1,unitPrice:100}],historySnapshot:{serviceLines:[{lineId:'l',serviceId:'s1',serviceName:'Serviço A',categoryId:'cat1',categoryName:'Categoria A',qty:1,gross:100,manualDiscount:0,comboDiscount:0,netCommercial:100,professionalId:'p1',unitId:'u1'}],comboApplications:[],partnership:{enabled:false}}}];let r=run(JSON.stringify(d));ok(!r.errors.length,'L runtime');let st=ev(r.ctx,`__imperioV61.v61FinanceState(${JSON.stringify(F())})`);ok(st.finance.accounts.some(x=>x.id==='old'&&x.inactiveCurrently),'L inactive account');ok(st.units.some(x=>x.unit?.id==='u1'&&x.unit?.active===false),'L inactive unit');let all=ev(r.ctx,`financeDreDataV40(${JSON.stringify(F())}).netRevenue`),u1=ev(r.ctx,`financeDreDataV40(${JSON.stringify(F('2026-09-01','2026-09-30','u1'))}).netRevenue`);moneyEq(all,u1,'L consolidated');
}

// M. Professional obligation: September commission unpaid at cutoff, October payment settles without extra DRE cost.
{
 let d=baseDb();d.schemaVersion=60;d.migrationHistory=[{id:'v60-reports-finance-dre'}];d.pros=[{id:'p1',name:'Pro 1',active:true,units:['u1']}];d.commissionEvents=[{id:'ce',commandId:'cmd',lineId:'l',date:'2026-09-10',unitId:'u1',professionalId:'p1',professionalName:'Pro 1',serviceId:'s1',amount:50,base:100,pct:50,historicalReliability:'reliable'}];d.commissionPayments=[{id:'cp',professionalId:'p1',unitId:'u1',amount:50,paidDate:'2026-10-05',periodFrom:'2026-09-01',periodTo:'2026-09-30',allocations:[{unitId:'u1',amount:50}]}];d.clientCommands=[{id:'cmd',status:'Pago',date:'2026-09-10',unitId:'u1',clientId:'c1',lines:[{id:'l',type:'service',serviceId:'s1',name:'Serviço A',professionalId:'p1',qty:1,unitPrice:100}],historySnapshot:{serviceLines:[{lineId:'l',serviceId:'s1',serviceName:'Serviço A',categoryId:'cat1',categoryName:'Categoria A',qty:1,gross:100,manualDiscount:0,comboDiscount:0,netCommercial:100,professionalId:'p1',unitId:'u1',commission:{amount:50,base:100,pct:50}}],comboApplications:[],partnership:{enabled:false}}}];let r=run(JSON.stringify(d));ok(!r.errors.length,'M runtime');let ob=ev(r.ctx,`__imperioV61.v61ProfessionalObligations(${JSON.stringify(F())})`);ok(ob.length>=1,'M obligation exists');moneyEq(ob.reduce((s,x)=>s+Number(x.balance||0),0),50,'M Sep balance');let dre=ev(r.ctx,`financeDreDataV40(${JSON.stringify(F())})`);moneyEq(dre.commissions,50,'M DRE commission once');
}

// N. Stock purchase capitalized payment never becomes operating expense.
{
 let d=baseDb();d.schemaVersion=60;d.migrationHistory=[{id:'v60-reports-finance-dre'}];d.demoFinancialEntries=[{id:'sp',unitId:'u1',date:'2026-09-20',obligationDate:'2026-09-01',dueDate:'2026-09-15',paidDate:'2026-09-20',amount:-1000,status:'Efetivado',sourceType:'stock_purchase',dreImpact:false,nature:'Compra de estoque a pagar'}];let r=run(JSON.stringify(d));ok(!r.errors.length,'N runtime');let dre=ev(r.ctx,`financeDreDataV40(${JSON.stringify(F())})`);moneyEq(dre.expenseTotal||0,0,'N stock payment DRE zero');
}

// O. Cash physical: opening 100 + client 300 + supply 200 - expense 50 = 550; supply not revenue.
{
 let d=baseDb();d.schemaVersion=60;d.migrationHistory=[{id:'v60-reports-finance-dre'}];d.financialAccounts=[{id:'cash',name:'Caixa',unitId:'u1',type:'CASH',active:true,openingBalance:100,openingBalanceDate:'2026-09-01',paymentMethodIds:[],feeRules:{}}];d.cashSessions=[{id:'cs',unitId:'u1',date:'2026-09-10',status:'closed',openingAmount:100,closureHistory:[{id:'cl',revision:1,movementIds:['sale','sup','out'],closedAt:'x'}],lastClosureId:'cl',closedMovementIds:['sale','sup','out']}];d.demoCashMovements=[{id:'sale',unitId:'u1',date:'2026-09-10',amount:300,paymentMethod:'Dinheiro',accountId:'cash',account:'Caixa',type:'Recebimento de comanda',cashSessionId:'cs'},{id:'sup',unitId:'u1',date:'2026-09-10',amount:200,paymentMethod:'Dinheiro',accountId:'cash',account:'Caixa',type:'Suprimento',sourceType:'cash_supply',cashSessionId:'cs'},{id:'out',unitId:'u1',date:'2026-09-10',amount:-50,paymentMethod:'Dinheiro',accountId:'cash',account:'Caixa',type:'Sangria · Despesa',cashSessionId:'cs'}];d.demoFinancialEntries=[{id:'exp',unitId:'u1',date:'2026-09-10',amount:-50,status:'Efetivado',accountId:'cash',account:'Caixa',nature:'Despesa operacional',dreImpact:true,sourceType:'cash_adjustment_expense'}];let r=run(JSON.stringify(d));ok(!r.errors.length,'O runtime');moneyEq(ev(r.ctx,`cashTotals(db.cashSessions[0].unitId,db.cashSessions[0].date).physicalExpected`),550,'O physical');let fm=ev(r.ctx,`__imperioV61.v61FinanceMetrics(${JSON.stringify(F())})`);moneyEq(fm.incoming,300,'O supply not revenue');
}

// P. Monthly payment canonical: one financial fact after closure, never 2x.
{
 let d=baseDb();d.schemaVersion=60;d.migrationHistory=[{id:'v60-reports-finance-dre'}];d.financialAccounts=[{id:'cash',name:'Caixa',unitId:'u1',type:'CASH',active:true,paymentMethodIds:[],feeRules:{}}];d.cashSessions=[{id:'cs',unitId:'u1',date:'2026-09-10',status:'closed',closureHistory:[{id:'cl',revision:1,movementIds:['cm'],closedAt:'x'}],lastClosureId:'cl',closedMovementIds:['cm']}];d.clientReceivables=[{id:'rec',clientId:'c1',unitId:'u1',date:'2026-09-01',originalAmount:225,balance:0,status:'Quitado'}];d.clientReceivablePayments=[{id:'pay',clientId:'c1',date:'2026-09-10',amount:225,cashMovementId:'cm',allocations:[{receivableId:'rec',unitId:'u1',amount:225}]}];d.demoCashMovements=[{id:'cm',unitId:'u1',date:'2026-09-10',amount:225,paymentMethod:'Dinheiro',accountId:'cash',account:'Caixa',type:'Recebimento conta mensal',cashSessionId:'cs',sourceType:'client_receivable_settlement',sourceId:'pay',revenueRecognition:false}];d.demoFinancialEntries=[{id:'legacydup',unitId:'u1',date:'2026-09-10',amount:225,accountId:'cash',account:'Caixa',nature:'Recebimento de conta mensal',sourceType:'client_receivable_settlement',sourceId:'pay',excludedFromOperationalLedger:true}];let r=run(JSON.stringify(d));ok(!r.errors.length,'P runtime');moneyEq(ev(r.ctx,`financeOperationalLedgerEntries().reduce((s,e)=>s+Number(e.amount||0),0)`),225,'P monthly once');
}


// Q. Fluxo real saveFinanceEntry em CASH: espelho físico + um único fato financeiro após fechamento.
{
 let d=baseDb();d.schemaVersion=60;d.migrationHistory=[{id:'v60-reports-finance-dre'}];d.financeCategories=[{id:'fc',name:'Outros',dre:true}];d.financialAccounts=[{id:'cash',name:'Caixa',unitId:'u1',type:'CASH',active:true,openingBalance:0,openingBalanceDate:'2026-09-01',paymentMethodIds:[],feeRules:{}}];let r=run(JSON.stringify(d));ok(!r.errors.length,'Q runtime');let today=ev(r.ctx,'localDateISO()');ev(r.ctx,`db.cashSessions=[{id:'cs',unitId:'u1',date:'${today}',status:'open',openingAmount:0,closureHistory:[]}];renderFinance=function(){};closeModal=function(){}`);const set=(id,v)=>r.ctx.document.getElementById(id).value=v;set('finEntryDirection','income');set('finEntryAmount','100');set('finEntryUnit','u1');set('finEntryAccount','cash');set('finEntryCategory','fc');set('finEntryStatus','Efetivado');set('finEntryDate',today);set('finEntryDueDate','');set('finEntryDesc','Receita manual caixa');ev(r.ctx,'saveFinanceEntry()');let fe=ev(r.ctx,`db.demoFinancialEntries.find(x=>x.sourceType==='manual_finance_entry')`),mir=ev(r.ctx,`db.demoCashMovements.find(x=>x.financialEntryId===db.demoFinancialEntries.find(e=>e.sourceType==='manual_finance_entry')?.id)`);ok(!!fe&&!!mir,'Q fact+mirror');moneyEq(ev(r.ctx,`cashTotals('u1','${today}').physicalExpected`),100,'Q physical');ev(r.ctx,`db.cashSessions[0].status='closed';db.cashSessions[0].closureHistory=[{id:'cl',revision:1,movementIds:[db.demoCashMovements[0].id],closedAt:new Date().toISOString()}];db.cashSessions[0].lastClosureId='cl';db.cashSessions[0].closedMovementIds=[db.demoCashMovements[0].id]`);moneyEq(ev(r.ctx,`financeOperationalLedgerEntries().reduce((s,e)=>s+Number(e.amount||0),0)`),100,'Q finance once');
}

// R. Fluxo real Conta Mensal após fechamento: R$225 financeiro, não R$450.
{
 let d=baseDb();d.schemaVersion=60;d.migrationHistory=[{id:'v60-reports-finance-dre'}];d.paymentMethods=[{id:'pm_cash',name:'Dinheiro'}];d.financialAccounts=[{id:'cash',name:'Caixa',unitId:'u1',type:'CASH',active:true,paymentMethodIds:['pm_cash'],feeRules:{}}];d.clients=[{id:'c1',name:'Cliente',phone:'1'}];d.clientReceivables=[{id:'rec',clientId:'c1',clientName:'Cliente',commandId:'cmd',unitId:'u1',date:'2026-09-01',dueDate:'2026-09-30',originalAmount:225,balance:225,status:'Em aberto'}];d.cashSessions=[{id:'cs',unitId:'u1',date:'2026-09-15',status:'open',openingAmount:0,closureHistory:[]}];let r=run(JSON.stringify(d));ok(!r.errors.length,'R runtime');const set=(id,v)=>r.ctx.document.getElementById(id).value=v;set('cmPayAmount','225');set('cmPayDate','2026-09-15');set('cmPayMethod','pm_cash');set('cmPayAccount','cash');set('cmPayNote','');ev(r.ctx,`openClient=function(){};closeModal=function(){};saveClientMonthlySettlement('c1')`);let cm=ev(r.ctx,`db.demoCashMovements.find(x=>x.sourceType==='client_receivable_settlement')`);ok(!!cm,'R cash fact');ok(ev(r.ctx,`db.demoFinancialEntries.filter(x=>x.sourceType==='client_receivable_settlement').length`)===0,'R no duplicate entry');ev(r.ctx,`db.cashSessions[0].status='closed';db.cashSessions[0].closureHistory=[{id:'cl',revision:1,movementIds:[db.demoCashMovements.find(x=>x.sourceType==='client_receivable_settlement').id],closedAt:new Date().toISOString()}];db.cashSessions[0].lastClosureId='cl';db.cashSessions[0].closedMovementIds=[db.demoCashMovements.find(x=>x.sourceType==='client_receivable_settlement').id]`);moneyEq(ev(r.ctx,`financeOperationalLedgerEntries().reduce((s,e)=>s+Number(e.amount||0),0)`),225,'R monthly once');moneyEq(ev(r.ctx,`db.clientReceivables[0].balance`),0,'R receivable zero');
}


// S. DOM simulado: nomenclatura V61 e entidade histórica inativa continuam visíveis nos filtros.
{
 let d=baseDb();d.schemaVersion=60;d.migrationHistory=[{id:'v60-reports-finance-dre'}];d.units=[{id:'u1',name:'Big Shopping',active:false},{id:'u2',name:'Centro',active:true},{id:'u3',name:'Outro',active:true}];d.clientCommands=[{id:'cmd',status:'Pago',date:'2026-09-10',unitId:'u1',clientId:'c1',lines:[{id:'l',type:'service',serviceId:'s1',name:'Serviço A',professionalId:'p1',qty:1,unitPrice:100}],historySnapshot:{serviceLines:[{lineId:'l',serviceId:'s1',serviceName:'Serviço A',categoryId:'cat1',categoryName:'Categoria A',qty:1,gross:100,manualDiscount:0,comboDiscount:0,netCommercial:100,professionalId:'p1',unitId:'u1'}],comboApplications:[],partnership:{enabled:false}}}];let r=run(JSON.stringify(d));ok(!r.errors.length,'S runtime');ev(r.ctx,`subbar=document.getElementById('subbar');adminPage=document.getElementById('adminPage');setReportsTab('finance')`);let h=ev(r.ctx,`adminPage.innerHTML`);ok(h.includes('Conta Mensal a receber'),'S client AR label');ok(h.includes('Recebíveis de adquirentes'),'S processor label');ok(h.includes('Fechamentos referentes ao período'),'S cash label');ok(h.includes('Big Shopping — inativa'),'S inactive filter');
}


// T. Multiunidade explícito: receita econômica no Big; tesouraria no Centro; consolidado sem duplicação.
{
 let d=baseDb();d.schemaVersion=60;d.migrationHistory=[{id:'v60-reports-finance-dre'}];d.financialAccounts=[{id:'proc3',name:'Stone Centro',unitId:'u3',type:'PROCESSOR',active:true,openingBalance:0,openingBalanceDate:'2026-09-01',paymentMethodIds:['pm_card'],feeRules:{pm_card:{percent:0,fixed:0,settlementDays:30}}}];d.paymentMethods=[{id:'pm_card',name:'Cartão'}];d.clientCommands=[{id:'cmd',status:'Pago',date:'2026-09-10',unitId:'u1',clientId:'c1',lines:[{id:'l',type:'service',serviceId:'s1',name:'Serviço A',professionalId:'p1',qty:1,unitPrice:100}],historySnapshot:{serviceLines:[{lineId:'l',serviceId:'s1',serviceName:'Serviço A',categoryId:'cat1',categoryName:'Categoria A',qty:1,gross:100,manualDiscount:0,comboDiscount:0,netCommercial:100,professionalId:'p1',unitId:'u1'}],comboApplications:[],partnership:{enabled:false}}}];d.cashSessions=[{id:'cs3',unitId:'u3',date:'2026-09-15',status:'closed',closureHistory:[{id:'cl',revision:1,movementIds:['pay'],closedAt:'x'}],lastClosureId:'cl',closedMovementIds:['pay']}];d.demoCashMovements=[{id:'pay',unitId:'u3',receivingUnitId:'u3',date:'2026-09-15',amount:100,grossAmount:100,processorFee:0,paymentMethod:'Cartão',paymentMethodId:'pm_card',accountId:'proc3',financialAccountId:'proc3',account:'Stone Centro',type:'Recebimento conta mensal',cashSessionId:'cs3',allocationByUnit:[{unitId:'u1',amount:100}],settlementReliability:'snapshot',expectedSettlementDate:'2026-10-15'}];let r=run(JSON.stringify(d));ok(!r.errors.length,'T runtime');let dreBig=ev(r.ctx,`financeDreDataV40(${JSON.stringify(F('2026-09-01','2026-09-30','u1'))})`),finBig=ev(r.ctx,`__imperioV61.v61FinanceMetrics(${JSON.stringify(F('2026-09-01','2026-09-30','u1'))})`),finCentro=ev(r.ctx,`__imperioV61.v61FinanceMetrics(${JSON.stringify(F('2026-09-01','2026-09-30','u3'))})`),dreAll=ev(r.ctx,`financeDreDataV40(${JSON.stringify(F())})`),finAll=ev(r.ctx,`__imperioV61.v61FinanceMetrics(${JSON.stringify(F())})`);moneyEq(dreBig.netRevenue,100,'T DRE Big');moneyEq(finBig.incoming,0,'T treasury Big zero');moneyEq(finCentro.incoming,100,'T treasury Centro');moneyEq(dreAll.netRevenue,100,'T consolidated DRE');moneyEq(finAll.incoming,100,'T consolidated finance');
}

console.log(JSON.stringify({ok:true,scripts:scripts.length,tests,stage1:true,stage2:true,stage3:true}));
