const fs=require('fs'),vm=require('vm');
const html=fs.readFileSync(__dirname+'/../index.html','utf8');
const scripts=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);
class MockStorage{constructor(raw){this.m=new Map(raw==null?[]:[['imperio-demo-v1',raw]]);this.writeCount=0}getItem(k){return this.m.has(k)?this.m.get(k):null}setItem(k,v){this.writeCount++;this.m.set(k,String(v))}removeItem(k){this.m.delete(k)}clear(){this.m.clear()}}
function element(id=''){return {id,value:'',checked:false,innerHTML:'',textContent:'',style:{},dataset:{},children:[],options:[],selectedIndex:0,className:'',src:'',href:'',files:[],disabled:false,classList:{add(){},remove(){},toggle(){return false},contains(){return false}},appendChild(x){this.children.push(x);return x},remove(){},click(){},focus(){},select(){},insertAdjacentElement(){},insertAdjacentHTML(){},addEventListener(){},removeEventListener(){},querySelector(){return null},querySelectorAll(){return[]},closest(){return null},contains(){return false},setAttribute(){},getAttribute(){return null}}}
function run(raw){const els=new Map();const doc={body:element('body'),documentElement:element('html'),getElementById(id){if(!els.has(id))els.set(id,element(id));return els.get(id)},querySelector(){return null},querySelectorAll(){return[]},createElement(tag){return element(tag)},addEventListener(){},removeEventListener(){}};const ls=new MockStorage(raw);const ctx={console,localStorage:ls,document:doc,window:null,navigator:{clipboard:{writeText:async()=>{}}},location:{},history:{},setTimeout:(f)=>{try{f()}catch{}},clearTimeout(){},setInterval(){return 1},clearInterval(){},structuredClone:global.structuredClone,Date,JSON,Math,Number,String,Array,Object,Map,Set,Intl,RegExp,Promise,Blob:function(){},FileReader:function(){},URL:{createObjectURL:()=>'',revokeObjectURL(){}},confirm:()=>true,prompt:()=>'',alert:()=>{},fetch:async()=>({ok:false,json:async()=>({})})};ctx.window=ctx;vm.createContext(ctx);const errors=[];for(let i=0;i<scripts.length;i++){try{vm.runInContext(scripts[i],ctx,{filename:`script${i}.js`})}catch(e){errors.push(`script ${i}: ${e.stack||e}`);break}}try{vm.runInContext(`/*AUTO_ADMIN_V67*/if(window.__imperioV63){let a=(db.userAccounts||[]).find(u=>u.role==='admin'&&u.active!==false);if(a)__imperioV63.sessionSet(a.id)}`,ctx)}catch{};return {ctx,ls,els,errors}}
function ev(ctx,code){return vm.runInContext(code,ctx)}
function assert(c,m){if(!c)throw new Error(m)}
let tests=0;function ok(c,m){tests++;assert(c,m)}
function near(a,b,m){tests++;assert(Math.abs(Number(a)-Number(b))<0.011,`${m}: ${a} != ${b}`)}
function F(from='2026-09-01',to='2026-10-15'){return {from,to,unit:'all',professional:'all',category:'all',service:'all',origin:'all',source:'all',commercial:'all',combo:'all',partnership:'all'}}
function baseDb(){return {schemaVersion:61,migrationHistory:[{id:'v61-finance-dre-stabilization',version:61}],units:[{id:'u1',name:'Big Shopping',active:true},{id:'u2',name:'Shopping Contagem',active:true},{id:'u3',name:'Centro de Contagem',active:true}],categories:[{id:'cat1',name:'Unhas',active:true}],services:[{id:'s1',name:'Serviço Teste',category:'cat1',price:100,duration:60,active:true,proRules:{p1:{enabled:true,commission:30}}}],pros:[{id:'p1',name:'Profissional 1',active:true,units:['u1','u2','u3'],services:['s1']}],clients:[
{id:'c1',name:'Cliente Instagram',phone:'1',source:'Instagram',origin:'Presencial',registrationUnit:'u1',createdAt:'2026-09-01'},
{id:'c2',name:'Cliente Indicação',phone:'2',source:'Indicação',origin:'WhatsApp',registrationUnit:'u2',createdAt:'2026-09-02'},
{id:'c3',name:'Cliente Sem Atribuição',phone:'3',source:'',origin:'',registrationUnit:'u1',createdAt:'2026-09-03'},
{id:'c4',name:'Cliente Google Antiga',phone:'4',source:'Google',origin:'Telefone',registrationUnit:'u3',createdAt:'2026-08-15'},
{id:'c5',name:'Cadastro Google sem visita',phone:'5',source:'Google',origin:'Site / Agendamento online',registrationUnit:'u1',createdAt:'2026-09-10'}],bookings:[],clientAppointments:[],clientCommands:[],commissionEvents:[],remunerationRules:[],tipMovements:[],tipDeductionRules:[{id:'tiprule_default_8_v1',percent:8,validFrom:'0001-01-01',validTo:'',unitId:'',active:true}],paymentMethods:[],financialAccounts:[],demoCashMovements:[],demoFinancialEntries:[],clientCreditMovements:[],clientReceivables:[],clientReceivablePayments:[],cashSessions:[],stockInputCosts:[],stockPurchases:[],stockMovements:[],stockTransfers:[],stockFamilies:[],stockSubstitutions:[],stockProducts:[],stockBalances:[],stockRequests:[],professionalDailyWork:[],commissionPayments:[],commissionAdjustments:[],commissionSettlements:[],reportSettings:{inactiveDays:90,returnLateGraceDays:7,capacityProductivityFactor:95},combos:[],financeCategories:[],companyEntities:[],financeGoals:[]}}
function command(id,clientId,date,unitId,value){return {id,clientId,date,unitId,status:'Pago',total:value,lines:[{id:`${id}-l1`,type:'service',serviceId:'s1',name:'Serviço Teste',professionalId:'p1',qty:1,unitPrice:value}],historySnapshot:{serviceLines:[{lineId:`${id}-l1`,serviceId:'s1',serviceName:'Serviço Teste',categoryId:'cat1',categoryName:'Unhas',qty:1,unitPrice:value,gross:value,manualDiscount:0,comboDiscount:0,netCommercial:value,professionalId:'p1',professionalName:'Profissional 1',unitId}],comboApplications:[],partnership:{enabled:false}}}}
function marketingDb(){let d=baseDb();d.clientCommands=[command('c1a','c1','2026-09-05','u1',100),command('c1b','c1','2026-09-20','u1',80),command('c2a','c2','2026-09-10','u2',200),command('c3a','c3','2026-09-15','u1',50),command('c3b','c3','2026-09-25','u1',50),command('c4a','c4','2026-08-20','u3',120),command('c4b','c4','2026-09-12','u3',90)];return d}

// Regressão V62 executada sobre V64 + 27 scripts.
let d=marketingDb();let r=run(JSON.stringify(d));ok(!r.errors.length,'A runtime sem erros');ok(scripts.length===40,'A 31 blocos JavaScript no pacote V66');ok(ev(r.ctx,'db.schemaVersion')===77,'A schema final 68 preservando V62');ok(ev(r.ctx,"db.migrationHistory.some(x=>x.id==='v62-reports-marketing')"),'A migration registrada');ok(ev(r.ctx,'db.marketingSettings.attributionSnapshotVersion')===1,'A snapshot version');

// B. Backfill conservador: aproveita dados existentes e preserva vazio.
ok(ev(r.ctx,"db.clients.find(c=>c.id==='c1').marketingAttributionSnapshot.source")==='Instagram','B Instagram importado preservado');ok(ev(r.ctx,"db.clients.find(c=>c.id==='c1').marketingAttributionSnapshot.historicalReliability")==='legacy_current_profile','B legado marcado');ok(ev(r.ctx,"db.clients.find(c=>c.id==='c3').marketingAttributionSnapshot.source")==='','B vazio permanece vazio');ok(ev(r.ctx,"db.clients.find(c=>c.id==='c5').marketingAttributionSnapshot===undefined"),'B sem primeira visita não cria snapshot');

// C. Métricas da primeira visita no período selecionado.
let state=ev(r.ctx,`__imperioV62.v62MarketingState(__imperioV62.getReportData(),${JSON.stringify(F())})`);ok(state.first.registrations===4,'C quatro cadastros');ok(state.first.clients===3,'C três clientes conquistadas');ok(state.first.converted===3,'C três cadastros convertidos');near(state.first.conversion,75,'C conversão 75%');near(state.first.revenue,350,'C receita primeira visita');near(state.first.ticket,350/3,'C ticket primeira visita');ok(state.first.returned===2,'C duas retornaram');near(state.first.retention,200/3,'C retenção da coorte');

// D. Duas dimensões conceituais permanecem separadas.
let ig=state.first.source.find(x=>x.label==='Instagram'),pr=state.first.origin.find(x=>x.label==='Presencial');ok(!!ig&&ig.acquired===1&&ig.revenue===100,'D grupo Como conheceu');ok(!!pr&&pr.acquired===1&&pr.revenue===100,'D grupo Origem');ok(state.first.source.some(x=>x.label==='Não especificado'),'D não especificado no relatório');ok(state.first.origin.some(x=>x.label==='Não especificado'),'D origem não especificada');

// E. Visitas posteriores e faturamento do período + acumulado secundário.
ok(state.postMetrics.clients===3,'E três clientes recorrentes no período');ok(state.postMetrics.visits===3,'E três visitas posteriores');near(state.postMetrics.revenue,220,'E receita posterior');near(state.postMetrics.ticket,220/3,'E ticket posterior');near(state.postMetrics.frequency,1,'E frequência');near(state.postMetrics.valuePerClient,220/3,'E valor por cliente');near(state.postMetrics.lifetime,490,'E acumulado secundário');near(state.postMetrics.retention30,200/3,'E retenção 30d coorte madura');ok(state.postMetrics.mature30===3,'E três maduras 30d');

// F. Agrupamento pós-primeira visita por atribuição original.
let pg=state.postMetrics.source.find(x=>x.label==='Google'),pi=state.postMetrics.source.find(x=>x.label==='Instagram');ok(!!pg&&pg.clients===1&&pg.revenue===90,'F Google posterior');ok(!!pi&&pi.clients===1&&pi.revenue===80,'F Instagram posterior');

// G. Qualidade dos dados.
ok(state.quality.total===4,'G base qualidade');ok(state.quality.missingSource===1,'G sem Como conheceu');ok(state.quality.missingOrigin===1,'G sem origem');near(state.quality.completePct,75,'G atribuição completa');

// H. Alterar cadastro atual não reescreve atribuição histórica congelada.
ev(r.ctx,"db.clients.find(c=>c.id==='c1').source='Google'");let fInstagram=F();fInstagram.source='Instagram';let snapFiltered=ev(r.ctx,`__imperioV62.v62MarketingState(__imperioV62.getReportData(),${JSON.stringify(fInstagram)})`);ok(snapFiltered.first.clients===1,'H filtro usa snapshot histórico');near(snapFiltered.first.revenue,100,'H receita continua Instagram');ok(ev(r.ctx,"db.clients.find(c=>c.id==='c1').marketingAttributionSnapshot.source")==='Instagram','H snapshot imutável');

// I. Cliente importada depois da migração: congelar valor anterior antes da edição.
ev(r.ctx,`db.clients.push({id:'c6',name:'Importada IA',phone:'6',source:'IA',origin:'Importação',registrationUnit:'u1',createdAt:'2026-07-01'});db.clientCommands.push(${JSON.stringify(command('c6a','c6','2026-07-10','u1',70))})`);let prep=ev(r.ctx,"__imperioV62.v62PrepareClientEdit('c6')");ev(r.ctx,"db.clients.find(c=>c.id==='c6').source='Google'");ok(ev(r.ctx,'__imperioV62.v62AfterClientEdit('+JSON.stringify(prep)+')')===true,'I congelamento pré-edição');ok(ev(r.ctx,"db.clients.find(c=>c.id==='c6').marketingAttributionSnapshot.source")==='IA','I preservou IA importada');

// J. Primeiro atendimento novo pode ser marcado como snapshot confiável na finalização.
ev(r.ctx,`db.clients.push({id:'c7',name:'Nova',phone:'7',source:'Instagram',origin:'Presencial',registrationUnit:'u2',createdAt:'2026-10-01'});db.clientCommands.push(${JSON.stringify(command('c7a','c7','2026-10-05','u2',110))})`);ok(ev(r.ctx,"__imperioV62.v62AfterFinalization('c7a')")===true,'J snapshot pós-finalização');ok(ev(r.ctx,"db.clients.find(c=>c.id==='c7').marketingAttributionSnapshot.historicalReliability")==='reliable','J snapshot confiável');ok(ev(r.ctx,"db.clients.find(c=>c.id==='c7').marketingAttributionSnapshot.captureReason")==='first_visit_finalization','J motivo finalização');

// K. DOM simulado: Marketing ativo, duas visões, Auditoria ainda bloqueada, CAC/ROAS indisponíveis.
ev(r.ctx,"subbar=document.getElementById('subbar');adminPage=document.getElementById('adminPage');setReportsTab('marketing')");let h=ev(r.ctx,'adminPage.innerHTML');ok(h.includes('V62 · Marketing'),'K versão V62');ok(h.includes('Primeira visita')&&h.includes('Visitas posteriores'),'K duas visões');ok(h.includes('Dados de investimento ainda não disponíveis'),'K CAC ROAS não inventados');ok(!h.includes('Marketing · em breve'),'K Marketing ativo');ok(!h.includes('Auditoria · em breve'),'K Auditoria ativa V64');ev(r.ctx,"v62SetMarketingView('post')");h=ev(r.ctx,'adminPage.innerHTML');ok(h.includes('Receita pós-1ª visita'),'K visão posterior renderizada');

// L. Idempotência da migração: usar uma base limpa, migrá-la uma vez e reinicializar sem mutações pós-migração.
let rid1=run(JSON.stringify(marketingDb()));ok(!rid1.errors.length,'L primeira inicialização limpa sem erro');let raw=rid1.ls.getItem('imperio-demo-v1');let rid2=run(raw);ok(!rid2.errors.length,'L segunda inicialização limpa sem erro');ok(rid2.ls.writeCount===0,'L migração idempotente sem nova gravação');ok(ev(rid2.ctx,'db.schemaVersion')===77,'L schema permanece 68');

console.log(JSON.stringify({ok:true,scripts:scripts.length,tests,v62RegressionOnV65:true,firstVisit:true,postVisits:true,snapshots:true,idempotent:true}));
