const fs=require('fs'),vm=require('vm');
const html=fs.readFileSync(__dirname+'/../index.html','utf8');
const scripts=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);
class MockStorage{constructor(raw){this.m=new Map(raw==null?[]:[['imperio-demo-v1',raw]]);this.writeCount=0}getItem(k){return this.m.has(k)?this.m.get(k):null}setItem(k,v){this.writeCount++;this.m.set(k,String(v))}removeItem(k){this.m.delete(k)}clear(){this.m.clear()}}
function element(id=''){return {id,value:'',checked:false,innerHTML:'',textContent:'',style:{},dataset:{},children:[],options:[],selectedIndex:0,className:'',src:'',href:'',files:[],disabled:false,firstChild:null,parentNode:null,classList:{add(){},remove(){},toggle(){return false},contains(){return false}},appendChild(x){this.children.push(x);return x},insertBefore(x){this.children.unshift(x);return x},remove(){},click(){},focus(){},select(){},insertAdjacentElement(){},insertAdjacentHTML(){},addEventListener(){},removeEventListener(){},querySelector(){return null},querySelectorAll(){return[]},closest(){return null},contains(){return false},setAttribute(){},getAttribute(){return null}}}
function run(raw){const els=new Map(),qsAll=new Map();const doc={body:element('body'),documentElement:element('html'),_qsAll:qsAll,getElementById(id){if(!els.has(id))els.set(id,element(id));return els.get(id)},querySelector(){return null},querySelectorAll(sel){return qsAll.get(sel)||[]},createElement(tag){return element(tag)},addEventListener(){},removeEventListener(){}};const ls=new MockStorage(raw),ss=new MockStorage(null);const ctx={console,localStorage:ls,sessionStorage:ss,document:doc,window:null,navigator:{clipboard:{writeText:async()=>{}}},location:{},history:{},setTimeout:(f)=>{try{f()}catch{}},clearTimeout(){},setInterval(){return 1},clearInterval(){},structuredClone:global.structuredClone,Date,JSON,Math,Number,String,Array,Object,Map,Set,Intl,RegExp,Promise,Blob:function(){},FileReader:function(){},URL:{createObjectURL:()=>'',revokeObjectURL(){}},confirm:()=>true,prompt:()=>'',alert:()=>{},fetch:async()=>({ok:false,json:async()=>({})}),event:{target:null}};ctx.window=ctx;vm.createContext(ctx);const errors=[];for(let i=0;i<scripts.length;i++){try{vm.runInContext(scripts[i],ctx,{filename:`script${i}.js`})}catch(e){errors.push(`script ${i}: ${e.stack||e}`);break}}try{vm.runInContext(`/*AUTO_ADMIN_V67*/if(window.__imperioV63){let a=(db.userAccounts||[]).find(u=>u.role==='admin'&&u.active!==false);if(a)__imperioV63.sessionSet(a.id)}`,ctx)}catch{};return {ctx,ls,ss,els,doc,errors}}
function ev(ctx,code){return vm.runInContext(code,ctx)}
function assert(c,m){if(!c)throw new Error(m)}
let tests=0;function ok(c,m){tests++;assert(c,m)}
function setup(r){for(const id of ['adminTabs','unitPicker','subbar','adminPage','loginUser','loginPass','modalHost'])r.ctx[id]=r.doc.getElementById(id);r.doc.getElementById('unitPicker').value='u1'}
function baseDb(){return {schemaVersion:63,migrationHistory:[{id:'v58-legacy-commission-unit-tip-money-hardening',version:58},{id:'v59-reports-services-stock',version:59},{id:'v60-reports-finance-dre',version:60},{id:'v61-finance-dre-stabilization',version:61},{id:'v62-reports-marketing',version:62},{id:'v63-settings-users-operators',version:63}],units:[{id:'u1',name:'Big Shopping',active:true},{id:'u2',name:'Shopping Contagem',active:true},{id:'u3',name:'Centro de Contagem',active:true}],categories:[{id:'cat1',name:'Unhas',active:true}],acquisitionSources:[],services:[{id:'s1',name:'Serviço',category:'cat1',price:100,duration:60,active:true,proRules:{p1:{enabled:true,commission:30}}}],pros:[{id:'p1',name:'Profissional 1',active:true,units:['u1'],services:['s1'],online:true}],clients:[{id:'c1',name:'Cliente 1',phone:'319',origin:'Presencial',source:'Instagram'}],bookings:[],paymentMethods:[{id:'pm_pix',name:'Pix'}],financialAccounts:[{id:'bank',name:'Banco',unitId:'u1',type:'BANK',active:true,openingBalance:0,openingBalanceDate:'2026-09-01',paymentMethodIds:['pm_pix'],feeRules:{}}],demoCashMovements:[],demoFinancialEntries:[],cashSessions:[],cashAudits:[{id:'legacy_ca1',unitId:'u1',date:'2026-09-20',action:'Fechamento',user:'Recepção Antiga',at:'2026-09-20T20:00:00.000Z',note:'Fechamento histórico'}],professionalCommissionAdjustments:[],tipMovements:[],clientAppointments:[],clientCommands:[],demoProducts:[],demoPackageCatalog:[],clientCreditMovements:[],clientPackages:[],clientReturns:[],combos:[],financeCategories:[{id:'fc1',name:'Outros',dre:true}],companyEntities:[],financeGoals:[],stockProducts:[{id:'sp1',sku:'SKU1',name:'Produto 1',type:'INPUT',group:'Insumos',unit:'un',active:true,defaultCost:10,allocations:{}}],stockBalances:[{productId:'sp1',locationId:'u1',qty:10,avgCost:10,minQty:0}],stockPurchases:[],stockRequests:[],stockTransfers:[],stockMovements:[],stockInputCosts:[],stockFamilies:[],stockSubstitutions:[],commissionSettlements:[],commissionPayments:[],remunerationRules:[],professionalDailyWork:[],clientReceivables:[],clientReceivablePayments:[],commissionEvents:[],tipDeductionRules:[],reportSettings:{inactiveDays:90,returnLateGraceDays:7,capacityProductivityFactor:95},marketingSettings:{attributionSnapshotVersion:1},storageMeta:{dataMode:'real',createdAt:'2026-09-27T00:00:00.000Z',storageSafetyVersion:1},userAccounts:[{id:'uadmin',name:'Administrador Teste',username:'admin',password:'segredo',role:'admin',active:true,allUnits:true,unitIds:[]}],systemSettings:{settingsVersion:1},communicationSettings:{whatsapp:{mode:'manual_link',version:1,unitNumbers:{},templates:{confirmation:'Olá {{cliente}}',reminder:'Lembrete',reactivation:'Volte',monthly_receivable:'Saldo'}}}}}
function setUserForm(r,{name,login,password='',role='reception',active=true,units=['u1']}){r.doc.getElementById('v63UserName').value=name;r.doc.getElementById('v63UserLogin').value=login;r.doc.getElementById('v63UserPassword').value=password;r.doc.getElementById('v63UserRole').value=role;r.doc.getElementById('v63UserActive').checked=active;r.doc.getElementById('v63UserAllUnits').checked=false;const checks=['u1','u2','u3'].map(id=>{let e=element('chk_'+id);e.value=id;e.checked=units.includes(id);return e});r.doc._qsAll.set('.v63-user-unit:checked',checks.filter(x=>x.checked));r.doc._qsAll.set('.v63-user-unit',checks)}

let r=run(JSON.stringify(baseDb()));setup(r);ok(!r.errors.length,'A runtime sem erros');ok(scripts.length===42,'A 31 scripts');ok(ev(r.ctx,'db.schemaVersion')===79,'A schema 68');ok(ev(r.ctx,"db.migrationHistory.some(x=>(typeof x==='string'?x:x.id)==='v64-audit-core-critical-events')"),'A migration V64');ok(ev(r.ctx,'Array.isArray(db.auditEvents)'),'A coleção auditEvents');ok(ev(r.ctx,'db.auditEvents.length')===0,'A não retrocriou eventos canônicos');ok(ev(r.ctx,"IMPERIO_ARRAY_COLLECTIONS.includes('auditEvents')"),'A coleção protegida pela persistência');
let cleanMigratedRaw=r.ls.getItem('imperio-demo-v1');
ok(ev(r.ctx,"String(saveService).includes('persistEvent')"),'A wrapper cadastro serviço ativo');ok(ev(r.ctx,"String(savePro).includes('invalidate')")&&html.includes("wrapCollectionSave('savePro','pros'"),'A cadeia cadastro profissional/auditoria preservada sob wrapper V78');ok(ev(r.ctx,"(String(saveClient).includes('persistEvent')||String(saveClient).includes('auditClient'))"),'A wrapper cadastro cliente ativo');

// Legado registrado só aparece se já existia de fato.
ok(ev(r.ctx,"__imperioV64.allEvents().some(x=>x.id==='legacy_cash:legacy_ca1'&&x.reliability==='legacy_recorded')"),'B cashAudit legado visível');ok(ev(r.ctx,"__imperioV64.allEvents().filter(x=>x.reliability==='legacy_recorded').length")===1,'B sem legado inventado');

// Identidade de sessão e sanitização.
ev(r.ctx,"__imperioV63.sessionSet('uadmin')");let e0=ev(r.ctx,"__imperioV64.persistEvent({module:'settings',action:'TEST',actionLabel:'Teste',entityType:'userAccount',entityId:'uadmin',before:{name:'A',password:'old'},after:{name:'B',password:'new'}})");ok(e0.actorUserId==='uadmin'&&e0.actorName==='Administrador Teste','C actor identificado');ok(!JSON.stringify(e0).includes('old')&&!JSON.stringify(e0).includes('new'),'C senha não gravada na auditoria');ok(e0.changedFields.some(x=>x.field==='name'),'C diff de campo');

// Usuários via handler real V63.
setUserForm(r,{name:'Juliana',login:'juliana',password:'1234',units:['u1']});let n0=ev(r.ctx,'db.auditEvents.length');ok(ev(r.ctx,"v63SaveUser('')")===true,'D cria usuário');let opId=ev(r.ctx,"db.userAccounts.find(x=>x.username==='juliana').id");ok(ev(r.ctx,'db.auditEvents.length')>=n0+1,'D evento de usuário criado');let ue=ev(r.ctx,"db.auditEvents.find(x=>x.action==='CREATE_USER'&&x.entityId==='"+opId+"')");ok(!!ue&&ue.action==='CREATE_USER'&&ue.entityId===opId,'D ação CREATE_USER');ok(!JSON.stringify(ue).includes('1234'),'D senha ausente do evento');ok(ev(r.ctx,"db.auditEvents.some(x=>x.action==='UPDATE_PERMISSIONS'&&x.entityId==='"+opId+"')"),'D permissões também auditadas');ok(ev(r.ctx,"v63ToggleUser('"+opId+"')")===true,'D inativa operador');ok(ev(r.ctx,"db.auditEvents.at(-1).action")==='DEACTIVATE_USER','D evento inativação');

// Comunicação/WhatsApp.
r.doc.getElementById('v63Wa_u1').value='5531999999999';r.doc.getElementById('v63Wa_u2').value='';r.doc.getElementById('v63Wa_u3').value='';r.doc.getElementById('v63Tpl_confirmation').value='Confirmado {{cliente}}';r.doc.getElementById('v63Tpl_reminder').value='Lembrete';r.doc.getElementById('v63Tpl_reactivation').value='Volte';r.doc.getElementById('v63Tpl_monthly_receivable').value='Saldo {{valor}}';ok(ev(r.ctx,'v63SaveCommunication()')===true,'E comunicação salva');ok(ev(r.ctx,"db.auditEvents.at(-1).action")==='UPDATE_COMMUNICATION','E audit comunicação');

// Caixa: abrir, fechar, reabrir e suprimento, com vínculo ao cashAudit legado específico do próprio evento.
ev(r.ctx,"renderCash=function(){};closeModal=function(){};cashDate='2026-09-27'");r.doc.getElementById('cashOpeningAmount').value='100';ev(r.ctx,'saveOpenCashSession()');let sid=ev(r.ctx,'db.cashSessions.at(-1).id');ok(ev(r.ctx,"db.auditEvents.at(-1).action")==='OPEN','F abertura auditada');ok(ev(r.ctx,"db.auditEvents.at(-1).metadata.cashAuditId")!=='','F vínculo cashAudit');r.doc.getElementById('cashCounted').value='100';r.doc.getElementById('cashCloseNote').value='Conferido';ev(r.ctx,'saveCloseCash()');ok(ev(r.ctx,"db.auditEvents.at(-1).action")==='CLOSE','F fechamento auditado');r.doc.getElementById('cashReopenReason').value='Correção de lançamento';ev(r.ctx,`saveReopenCash('${sid}')`);ok(ev(r.ctx,"db.auditEvents.at(-1).action")==='REOPEN','F reabertura auditada');ok(ev(r.ctx,"db.auditEvents.at(-1).reason")==='Correção de lançamento','F motivo reabertura');r.doc.getElementById('cashAdjAmount').value='50';r.doc.getElementById('cashAdjReason').value='Reforço de troco';ev(r.ctx,"saveCashAdjustment('Suprimento')");ok(ev(r.ctx,"db.auditEvents.at(-1).action")==='SUPPLY','F suprimento auditado');
r.doc.getElementById('cashAdjAmount').value='30';r.doc.getElementById('cashAdjReason').value='Envio ao banco';r.doc.getElementById('cashAdjNature').value='transfer';r.doc.getElementById('cashAdjTransferAccount').value='bank';r.doc.getElementById('cashAdjTransferDest').value='';ev(r.ctx,"saveCashAdjustment('Sangria')");let te=ev(r.ctx,'db.auditEvents.at(-1)');ok(te.action==='TRANSFER','F transferência interna auditada como transferência');ok(te.after.destinationAccountId==='bank'&&!!te.after.transferId,'F transferência preserva destino e transferId');

// Financeiro manual.
r.doc.getElementById('finEntryDirection').value='expense';r.doc.getElementById('finEntryAmount').value='80';r.doc.getElementById('finEntryUnit').value='u1';r.doc.getElementById('finEntryAccount').value='bank';r.doc.getElementById('finEntryCategory').value='fc1';r.doc.getElementById('finEntryStatus').value='Efetivado';r.doc.getElementById('finEntryDate').value='2026-09-27';r.doc.getElementById('finEntryDueDate').value='';r.doc.getElementById('finEntryDesc').value='Despesa teste';ev(r.ctx,'renderFinance=function(){};closeModal=function(){};saveFinanceEntry()');ok(ev(r.ctx,"db.auditEvents.at(-1).action")==='CREATE_ENTRY','G lançamento financeiro auditado');ok(ev(r.ctx,"db.auditEvents.at(-1).reason")==='Despesa teste','G descrição preservada como motivo/origem');

// Comanda: alteração de desconto/preço em item.
ev(r.ctx,`db.clientCommands.push({id:'cmd1',clientId:'c1',unitId:'u1',date:'2026-09-27',status:'Aberta',lines:[{id:'ln1',type:'service',serviceId:'s1',name:'Serviço',qty:1,unitPrice:100,discount:0,professionalId:'p1',professionalName:'Profissional 1'}]});openCommand=function(){}`);r.doc.getElementById('cmdEditPrice').value='95';r.doc.getElementById('cmdEditDiscount').value='10';r.ctx.cmdEditPrice=r.doc.getElementById('cmdEditPrice');r.ctx.cmdEditDiscount=r.doc.getElementById('cmdEditDiscount');ev(r.ctx,"saveCommandLineEdit('cmd1','ln1')");let ce=ev(r.ctx,'db.auditEvents.at(-1)');ok(ce.action==='EDIT_LINE','H edição de item auditada');ok(ce.severity==='critical','H desconto é ação sensível');ok(ce.changedFields.some(x=>x.field==='discount'),'H diff desconto');

// Comissão: acerto com ajuste positivo real.
ev(r.ctx,"db.professionalCommissionAdjustments.push({id:'adj1',type:'Ajuste positivo',date:'2026-09-27',unitId:'u1',professionalId:'p1',amount:120,note:'Correção',status:'Aberto'});commissionUnit='u1';commissionFrom='2026-09-01';commissionTo='2026-09-30';renderCommissionCenter=function(){};closeModal=function(){}");r.doc.getElementById('comSettleDate').value='2026-09-27';r.doc.getElementById('comSettleAccount').value='bank';r.doc.getElementById('comSettleMethod').value='Pix';r.doc.getElementById('comSettleAmount').value='120';r.doc.getElementById('comSettleNote').value='Acerto setembro';ev(r.ctx,"openCommissionReceipt=function(){};saveCommissionSettlement('p1')");let se=ev(r.ctx,'db.auditEvents.at(-1)');ok(se.action==='PAYMENT','I pagamento auditado');ok(se.entityType==='commissionPayment','I entidade pagamento');ok(Number(se.after.total)===120,'I valor pagamento');

// Comissão: ajuste e regra de remuneração versionada.
r.doc.getElementById('comAdjAmount').value='25';r.doc.getElementById('comAdjType').value='Ajuste positivo';r.doc.getElementById('comAdjUnit').value='u1';r.doc.getElementById('comAdjDate').value='2026-09-28';r.doc.getElementById('comAdjNote').value='Bônus técnico';ev(r.ctx,"openCommissionProfessional=function(){};saveCommissionAdjustment('p1')");let ae=ev(r.ctx,'db.auditEvents.at(-1)');ok(ae.action==='ADJUSTMENT','I2 ajuste de comissão auditado');ok(ae.reason==='Bônus técnico','I2 motivo ajuste');
r.doc.getElementById('rrUnit').value='u1';r.doc.getElementById('rrModel').value='guarantee';r.doc.getElementById('rrAmount').value='2000';r.doc.getElementById('rrFrequency').value='monthly';r.doc.getElementById('rrStart').value='2026-10-01';r.doc.getElementById('rrEnd').value='';r.doc.getElementById('rrActive').checked=true;r.doc.getElementById('rrNote').value='Garantia inicial';ev(r.ctx,"openRemunerationRules=function(){};saveRemunerationRule('p1','')");let re=ev(r.ctx,'db.auditEvents.at(-1)');ok(re.action==='REMUNERATION_RULE_CHANGE','I2 remuneração auditada');ok(re.after.rules.some(x=>x.model==='guarantee'&&Number(x.amount)===2000),'I2 regra congelada no evento');

// Estoque: cadastro/custo de SKU e inventário com motivo.
for(const [id,v] of Object.entries({spName:'Produto Auditoria',spSku:'AUD1',spFamily:'',spBrand:'Marca',spPackQty:'1',spBaseUnit:'un',spType:'RESALE',spGroup:'Revenda',spUnit:'un',spCost:'15',spSale:'30',spMin:'2',spSupplier:'Fornecedor',spActive:'1'}))r.doc.getElementById(id).value=v;ev(r.ctx,"renderStockProducts=function(){};saveStockProduct('sp_audit',false)");let pe=ev(r.ctx,'db.auditEvents.at(-1)');ok(pe.action==='PRODUCT_CREATE','J produto/SKU criado auditado');r.doc.getElementById('spCost').value='18';ev(r.ctx,"saveStockProduct('sp_audit',true)");pe=ev(r.ctx,'db.auditEvents.at(-1)');ok(pe.action==='PRODUCT_UPDATE'&&pe.severity==='critical','J alteração de custo auditada como sensível');

// Estoque: inventário com motivo.
let tr=element('tr');tr.dataset.pid='sp1';let inp=element('input');inp.value='8';tr.querySelector=(sel)=>sel==='input'?inp:null;r.doc._qsAll.set('#stockInventoryBody tbody tr',[tr]);r.doc.getElementById('stockInvLocation').value='u1';r.doc.getElementById('stockInvReason').value='Contagem física';ev(r.ctx,'renderStockInventory=function(){};applyStockInventory()');let ie=ev(r.ctx,'db.auditEvents.at(-1)');ok(ie.action==='INVENTORY_ADJUSTMENT','J inventário auditado');ok(ie.reason==='Contagem física','J motivo inventário');ok(ie.severity==='critical','J inventário sensível');

// Relatório: ativo, restrito a admin e detalhamento.
ev(r.ctx,"setReportsTab('audit')");ok(r.doc.getElementById('adminPage').innerHTML.includes('Auditoria'),'K Auditoria renderizada');ok(r.doc.getElementById('adminPage').innerHTML.includes('Linha do tempo'),'K linha do tempo');ok(ev(r.ctx,'__imperioV64.canViewAudit()')===true,'K admin pode ver');let filtered=ev(r.ctx,'__imperioV64.filteredEvents()');ok(filtered.length>0,'K filtros retornam eventos');ok(r.doc.getElementById('adminPage').innerHTML.includes("setReportsTab('audit')\">Auditoria")&&!r.doc.getElementById('adminPage').innerHTML.includes('Auditoria · em breve'),'K aba Auditoria ativa');

// Usuário não-admin não vê conteúdo de Auditoria.
ev(r.ctx,`db.userAccounts.find(x=>x.id==='${opId}').active=true;__imperioV63.sessionSet('${opId}')`);ok(ev(r.ctx,'__imperioV64.canViewAudit()')===false,'L não-admin bloqueado');ok(ev(r.ctx,"setReportsTab('audit')")===false,'L acesso direto à subaba bloqueado pela V68');

// Idempotência: a mesma base V64 reinicia sem nova gravação.
ev(r.ctx,"__imperioV63.sessionSet('uadmin')");let r2=run(cleanMigratedRaw);setup(r2);ok(!r2.errors.length,'M segunda inicialização sem erro');ok(r2.ls.writeCount===0,'M zero novas gravações');ok(ev(r2.ctx,'db.schemaVersion')===79,'M schema 68');ok(ev(r2.ctx,"db.migrationHistory.filter(x=>(typeof x==='string'?x:x.id)==='v64-audit-core-critical-events').length")===1,'M migration única');

console.log(JSON.stringify({ok:true,scripts:scripts.length,tests,audit:true,legacyPolicy:true,actor:true,cash:true,finance:true,commands:true,commission:true,stock:true,settings:true,idempotent:true}));
