const fs=require('fs'),vm=require('vm');
const html=fs.readFileSync(__dirname+'/../index.html','utf8');
const scripts=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);
class FixedDate extends Date{constructor(...a){super(...(a.length?a:['2026-09-28T11:30:00-03:00']))}static now(){return Date.parse('2026-09-28T11:30:00-03:00')}}
class MockStorage{constructor(raw){this.m=new Map(raw==null?[]:[['imperio-demo-v1',raw]]);this.writeCount=0}getItem(k){return this.m.has(k)?this.m.get(k):null}setItem(k,v){this.writeCount++;this.m.set(k,String(v))}removeItem(k){this.m.delete(k)}clear(){this.m.clear()}}
function element(id=''){return {id,value:'',checked:false,innerHTML:'',outerHTML:'',textContent:'',style:{},dataset:{},children:[],options:[],selectedIndex:0,className:'',src:'',href:'',files:[],disabled:false,firstChild:null,parentNode:null,classList:{add(){},remove(){},toggle(){return false},contains(){return false}},appendChild(x){this.children.push(x);x.parentNode=this;return x},insertBefore(x){this.children.unshift(x);x.parentNode=this;return x},remove(){},click(){},focus(){},select(){},insertAdjacentElement(){},insertAdjacentHTML(pos,h){this.innerHTML+=h},addEventListener(){},removeEventListener(){},querySelector(){return null},querySelectorAll(){return[]},closest(){return null},contains(){return false},setAttribute(){},getAttribute(){return null}}}
function run(raw){const els=new Map(),qsAll=new Map();const doc={body:element('body'),documentElement:element('html'),_qsAll:qsAll,getElementById(id){if(!els.has(id))els.set(id,element(id));return els.get(id)},querySelector(){return null},querySelectorAll(sel){return qsAll.get(sel)||[]},createElement(tag){return element(tag)},addEventListener(){},removeEventListener(){}};const ls=new MockStorage(raw),ss=new MockStorage(null);const opened=[];const ctx={console,localStorage:ls,sessionStorage:ss,document:doc,window:null,navigator:{clipboard:{writeText:async()=>{}}},location:{},history:{},setTimeout:(f)=>{try{f()}catch{}},clearTimeout(){},setInterval(){return 1},clearInterval(){},structuredClone:global.structuredClone,Date:FixedDate,JSON,Math,Number,String,Array,Object,Map,Set,Intl,RegExp,Promise,Blob:function(){},FileReader:function(){},URL:{createObjectURL:()=>'',revokeObjectURL(){}},confirm:()=>true,prompt:()=>'',alert:()=>{},fetch:async()=>({ok:false,json:async()=>({})}),event:{target:null},open:(url)=>{opened.push(url);return null}};ctx.window=ctx;vm.createContext(ctx);const errors=[];for(let i=0;i<scripts.length;i++){try{vm.runInContext(scripts[i],ctx,{filename:`script${i}.js`})}catch(e){errors.push(`script ${i}: ${e.stack||e}`);break}}return {ctx,ls,ss,els,doc,errors,opened}}
function ev(ctx,code){return vm.runInContext(code,ctx)}
function assert(c,m){if(!c)throw new Error(m)}let tests=0;function ok(c,m){tests++;assert(c,m)}function eq(a,b,m){ok(JSON.stringify(a)===JSON.stringify(b),`${m}: ${JSON.stringify(a)} != ${JSON.stringify(b)}`)}
function hist(){return ['v58-legacy-commission-unit-tip-money-hardening','v59-reports-services-stock','v60-reports-finance-dre','v61-finance-dre-stabilization','v62-reports-marketing','v63-settings-users-operators','v64-audit-core-critical-events','v65-executive-overview','v66-notifications-management-tasks','v67-custom-user-permissions','v68-fiscal-foundation','v69-nfse-national-direct','v70-agenda-operational-metrics','v71-configurable-fields-options-clients','v72-configurable-fields-options-agenda-commands','v73-configurable-fields-options-professionals-stock','v74-configurable-fields-options-finance','v75-dre-combo-profitability-allocation','v76-fiscal-payments-booking-authorship','v77-workstations-physical-capacity','v78-physical-capacity-alerts'].map(id=>({id}))}
function sch(start='09:00',end='20:00'){let x={};for(let i=0;i<7;i++)x['u1-'+i]={work:true,start,end},x['u2-'+i]={work:true,start,end};return x}
function baseDb(){return {schemaVersion:78,migrationHistory:hist(),units:[{id:'u1',name:'Big Shopping',active:true,show:true,online:true},{id:'u2',name:'Shopping Contagem',active:true,show:true,online:true}],categories:[{id:'c_man',name:'Manicure',active:true},{id:'c_long',name:'Alongamento',active:true}],services:[{id:'s_man',name:'Manicure',category:'c_man',price:40,duration:40,active:true,show:true,online:true,proRules:{}},{id:'s_long',name:'Alongamento',category:'c_long',price:120,duration:60,active:true,show:true,online:true,proRules:{}}],pros:[{id:'p1',name:'Ana',active:true,show:true,online:true,units:['u1'],services:['s_man','s_long'],schedule:sch()},{id:'p2',name:'Camila',active:true,show:true,online:true,units:['u1'],services:['s_man'],schedule:sch()},{id:'p3',name:'Bia',active:true,show:true,online:true,units:['u2'],services:['s_man'],schedule:sch()}],clients:[{id:'cl1',name:'Juliana',phone:'31999999999',cpf:'',source:'Instagram',origin:'Presencial',registrationUnit:'u1'},{id:'cl2',name:'Marina',phone:'31888888888',cpf:'',source:'Google',origin:'Presencial',registrationUnit:'u1'}],bookings:[],clientAppointments:[],clientCommands:[],paymentMethods:[],financialAccounts:[],demoCashMovements:[],demoFinancialEntries:[],cashSessions:[],cashAudits:[],auditEvents:[],clientCreditMovements:[],clientReceivables:[],clientReceivablePayments:[],commissionEvents:[],remunerationRules:[],tipMovements:[],tipDeductionRules:[],demoProducts:[],demoPackageCatalog:[],clientPackages:[],clientReturns:[],combos:[],financeCategories:[],companyEntities:[],financeGoals:[],stockProducts:[],stockBalances:[],stockPurchases:[],stockRequests:[],stockTransfers:[],stockMovements:[],stockInputCosts:[],stockFamilies:[],stockSubstitutions:[],commissionSettlements:[],commissionPayments:[],commissionAdjustments:[],professionalCommissionAdjustments:[],professionalDailyWork:[],managementTasks:[],notificationAlertStates:{},notificationSettings:{},fiscalDocuments:[],fiscalSettings:{},reportSettings:{inactiveDays:90,returnLateGraceDays:7,capacityProductivityFactor:95},commissionSettings:{discountsReduceBase:true,directPaymentReducesSettlement:true,comboAllocation:'proportional'},storageMeta:{dataMode:'real',createdAt:'2026-09-01T00:00:00.000Z',storageSafetyVersion:1},userAccounts:[{id:'usr_admin',name:'Admin',username:'admin',password:'x',role:'admin',active:true,allUnits:true,unitIds:[]},{id:'usr_mgr',name:'Gerente Big',username:'mgr',password:'x',role:'manager',active:true,allUnits:false,unitIds:['u1']},{id:'usr_mgr2',name:'Gerente Contagem',username:'mgr2',password:'x',role:'manager',active:true,allUnits:false,unitIds:['u2']}],systemSettings:{settingsVersion:1,formFields:{},optionSets:{}},communicationSettings:{whatsapp:{mode:'manual_link',version:1,unitNumbers:{},templates:{confirmation:'',reminder:'',reactivation:'',monthly_receivable:''}}},workstations:[{id:'ws1',unitId:'u1',name:'Mesa 1',allowedCategoryIds:['c_man'],active:true,createdAt:'x',updatedAt:'x'}]}}
function setup(r,user='usr_mgr'){for(const id of ['adminTabs','unitPicker','subbar','adminPage','loginUser','loginPass','modalHost','rDate','rStatus','rNotes','v79Unit','v79Service','v79Date','v79Start','v79End','v79ProMode','v79PreferredPro','v79Notes'])r.ctx[id]=r.doc.getElementById(id);r.doc.getElementById('unitPicker').value='u1';r.ctx.unitPicker=r.doc.getElementById('unitPicker');r.ctx.page='agenda';r.ctx.agendaDate='2026-10-03';r.doc.getElementById('rDate').value='2026-10-03';r.doc.getElementById('rStatus').value='Agendado';r.doc.getElementById('rNotes').value='';ev(r.ctx,`__imperioV63.sessionSet('${user}')`)}
function form(r,{client='cl1',service='s_man',unit='u1',date='2026-10-03',start='13:00',end='18:00',mode='any',pro='',notes=''}={}){r.ctx.__v79QueueDraft={clientId:client};r.doc.getElementById('v79Unit').value=unit;r.doc.getElementById('v79Service').value=service;r.doc.getElementById('v79Date').value=date;r.doc.getElementById('v79Start').value=start;r.doc.getElementById('v79End').value=end;r.doc.getElementById('v79ProMode').value=mode;r.doc.getElementById('v79PreferredPro').value=pro;r.doc.getElementById('v79Notes').value=notes}
let r=run(JSON.stringify(baseDb()));setup(r);
ok(!r.errors.length,'runtime sem erro');ok(scripts.length===43,'42 scripts');ok(ev(r.ctx,'db.schemaVersion')===80,'schema 80');ok(ev(r.ctx,"db.migrationHistory.filter(x=>(typeof x==='string'?x:x.id)==='v79-waitlist-operational-foundation').length")===1,'migração V79 única');ok(ev(r.ctx,"Array.isArray(db.waitlistRequests)&&db.waitlistRequests.length===0"),'migração inicia fila vazia');ok(ev(r.ctx,"typeof evaluatePhysicalCapacity==='function'&&typeof __imperioV78.physicalAlerts==='function'"),'fase 0 preserva capacidade/alertas V78');
// C1 BÁSICO
let b0=ev(r.ctx,'db.bookings.length'),cap0=JSON.stringify(ev(r.ctx,"__imperioV77.evaluatePhysicalCapacityDay({unitId:'u1',date:'2026-10-03'})"));form(r);ok(ev(r.ctx,"__imperioV79.saveRequest('')")===true,'C1 salva solicitação básica');let q1=ev(r.ctx,'db.waitlistRequests[0]');ok(q1.status==='WAITING'&&q1.clientId==='cl1'&&q1.serviceId==='s_man'&&q1.unitId==='u1','C1 Aguardando vaga com entidades canônicas');ok(ev(r.ctx,'db.bookings.length')===b0,'C1 não cria ocupação/agendamento');eq(JSON.stringify(ev(r.ctx,"__imperioV77.evaluatePhysicalCapacityDay({unitId:'u1',date:'2026-10-03'})")),cap0,'C1 não altera capacidade física');
// C2 PREFERÊNCIA
form(r,{client:'cl2',mode:'preferred',pro:'p1'});ok(ev(r.ctx,"__imperioV79.saveRequest('')")===true,'C2 salva preferência');let q2=ev(r.ctx,'db.waitlistRequests[1]');ok(q2.professionalPreferenceMode==='preferred'&&q2.preferredProfessionalId==='p1','C2 preferência não vira exigência');
// C3 EXIGÊNCIA
form(r,{client:'cl2',date:'2026-10-04',mode:'required',pro:'p1'});ok(ev(r.ctx,"__imperioV79.saveRequest('')")===true,'C3 salva exigência');let q3=ev(r.ctx,'db.waitlistRequests[2]');ok(q3.professionalPreferenceMode==='required'&&q3.preferredProfessionalId==='p1','C3 somente profissional explícita');
// C4 JANELA INVÁLIDA
let qn=ev(r.ctx,'db.waitlistRequests.length');form(r,{date:'2026-10-05',start:'13:00',end:'12:00'});ok(ev(r.ctx,"__imperioV79.saveRequest('')")===false&&ev(r.ctx,'db.waitlistRequests.length')===qn,'C4 fim antes do início não salva');form(r,{date:'2026-10-05',start:'13:00',end:'13:00'});ok(ev(r.ctx,"__imperioV79.saveRequest('')")===false,'C4 fim igual ao início também inválido');
// C5 MULTIUNIDADE
r.ctx.foreign={id:'foreign',clientId:'cl1',unitId:'u2',serviceId:'s_man',availabilityDate:'2026-10-03',availabilityStartTime:'10:00',availabilityEndTime:'12:00',professionalPreferenceMode:'any',status:'WAITING',createdAt:'x'};ev(r.ctx,'db.waitlistRequests.push(foreign)');ok(ev(r.ctx,"__imperioV79.visible(db.waitlistRequests.find(x=>x.id==='foreign'))")===false,'C5 unidade fora do escopo não fica visível');ok(!ev(r.ctx,"__imperioV79.activeRequests().some(x=>x.id==='foreign')"),'C5 não contamina fila do gestor Big');
// C6 EXPIRAÇÃO
r.ctx.past={id:'past',clientId:'cl1',unitId:'u1',serviceId:'s_man',availabilityDate:'2026-09-20',availabilityStartTime:'10:00',availabilityEndTime:'12:00',professionalPreferenceMode:'any',status:'WAITING',createdAt:'x'};ev(r.ctx,'db.waitlistRequests.push(past)');ok(ev(r.ctx,"__imperioV79.effectiveStatus(db.waitlistRequests.find(x=>x.id==='past'))")==='EXPIRED','C6 passada é tratada como Expirada');ok(ev(r.ctx,"db.waitlistRequests.find(x=>x.id==='past').status")==='WAITING','C6 expiração derivada não apaga/regrava histórico');
// C7 REMOÇÃO
let lenBefore=ev(r.ctx,'db.waitlistRequests.length');ok(ev(r.ctx,`__imperioV79.changeStatus('${q1.id}','REMOVED')`)===true,'C7 remoção por status');ok(ev(r.ctx,`db.waitlistRequests.find(x=>x.id==='${q1.id}').status`)==='REMOVED'&&ev(r.ctx,'db.waitlistRequests.length')===lenBefore,'C7 registro preservado');
// C8 CONTATO
ok(ev(r.ctx,`__imperioV79.markContacted('${q2.id}')`)===true,'C8 marca contato');let q2c=ev(r.ctx,`db.waitlistRequests.find(x=>x.id==='${q2.id}')`);ok(q2c.status==='CONTACTED'&&!!q2c.contactedAt&&q2c.contactedByUserId==='usr_mgr','C8 contato guarda data/autoria');ok(ev(r.ctx,`__imperioV79.changeStatus('${q2.id}','INVALID_STATUS')`)===false,'C8 status inválido é rejeitado');
// C9 AGENDAR via fluxo canônico
form(r,{client:'cl1',date:'2026-10-06',start:'13:00',end:'18:00',mode:'preferred',pro:'p1'});ok(ev(r.ctx,"__imperioV79.saveRequest('')")===true,'C9 solicitação para agendar');let qb=ev(r.ctx,'db.waitlistRequests[db.waitlistRequests.length-1]'),beforeBookings=ev(r.ctx,'db.bookings.length');ok(ev(r.ctx,`__imperioV79.beginBooking('${qb.id}')`)===true,'C9 abre fluxo normal da Agenda');r.doc.getElementById('rDate').value='2026-10-06';r.doc.getElementById('rStatus').value='Agendado';ok(ev(r.ctx,'saveReservation()')!==false,'C9 salva via saveReservation canônico');let qb2=ev(r.ctx,`db.waitlistRequests.find(x=>x.id==='${qb.id}')`);ok(ev(r.ctx,'db.bookings.length')===beforeBookings+1&&qb2.status==='BOOKED'&&!!qb2.appointmentId,'C9 só após booking real vira Agendado e recebe appointmentId');ok(ev(r.ctx,`db.bookings.some(x=>x.id==='${qb2.appointmentId}'&&x.createdByUserId==='usr_mgr')`),'C9 autoria do agendamento V76 preservada');
// C10 CANCELAR FORMULÁRIO
form(r,{client:'cl1',date:'2026-10-07',start:'14:00',end:'17:00'});ok(ev(r.ctx,"__imperioV79.saveRequest('')")===true,'C10 cria solicitação ativa');let qc=ev(r.ctx,'db.waitlistRequests[db.waitlistRequests.length-1]');ok(ev(r.ctx,`__imperioV79.beginBooking('${qc.id}')`)===true,'C10 abre Agenda');ev(r.ctx,'closeModal()');ok(ev(r.ctx,`db.waitlistRequests.find(x=>x.id==='${qc.id}').status`)==='WAITING','C10 fechar sem salvar não marca Agendado');
// C11 DUPLICIDADE
let d={clientId:'cl1',serviceId:'s_man',unitId:'u1',availabilityDate:'2026-10-07',availabilityStartTime:'14:00',availabilityEndTime:'17:00'};r.ctx.dd=d;ok(!!ev(r.ctx,"__imperioV79.duplicateOf(dd,'')"),'C11 detecta possível duplicidade sem apagar/bloquear rigidamente');
// C12 CAPACIDADE: 10 solicitações não viram demanda
let physBefore=JSON.stringify(ev(r.ctx,"__imperioV77.evaluatePhysicalCapacityDay({unitId:'u1',date:'2026-10-08'})")),bkBefore=ev(r.ctx,'db.bookings.length');for(let i=0;i<10;i++){form(r,{client:i%2?'cl1':'cl2',date:'2026-10-08',start:'09:00',end:'19:00',notes:'fila '+i});ev(r.ctx,"__imperioV79.saveRequest('')")}let physAfter=JSON.stringify(ev(r.ctx,"__imperioV77.evaluatePhysicalCapacityDay({unitId:'u1',date:'2026-10-08'})"));ok(ev(r.ctx,'db.bookings.length')===bkBefore,'C12 dez pessoas na fila não ocupam Agenda');eq(physAfter,physBefore,'C12 fila não entra na capacidade física');
// C13 FINANCEIRO neutro
let fBefore=ev(r.ctx,"JSON.stringify({cash:db.demoCashMovements.length,fin:db.demoFinancialEntries.length,rec:db.clientReceivables.length,pay:db.clientReceivablePayments.length,comm:db.commissionEvents.length,cmd:db.clientCommands.length})");form(r,{client:'cl2',date:'2026-10-09',start:'10:00',end:'12:00'});ok(ev(r.ctx,"__imperioV79.saveRequest('')")===true,'C13 adiciona cliente à fila');let fAfter=ev(r.ctx,"JSON.stringify({cash:db.demoCashMovements.length,fin:db.demoFinancialEntries.length,rec:db.clientReceivables.length,pay:db.clientReceivablePayments.length,comm:db.commissionEvents.length,cmd:db.clientCommands.length})");eq(fAfter,fBefore,'C13 zero efeito financeiro/econômico');
// Requisito adicional: exigência não pode ser satisfeita por outra profissional ao vincular.
let reqRequired={id:'rqreq',clientId:'cl1',unitId:'u1',serviceId:'s_man',availabilityDate:'2026-10-10',availabilityStartTime:'13:00',availabilityEndTime:'18:00',professionalPreferenceMode:'required',preferredProfessionalId:'p1',status:'WAITING'};let wrongBooking={id:'wrong',clientId:'cl1',unit:'u1',date:'2026-10-10',status:'Agendado',items:[{serviceId:'s_man',pro:'p2',time:'14:00',duration:40}]};r.ctx.reqRequired=reqRequired;r.ctx.wrongBooking=wrongBooking;ok(ev(r.ctx,'__imperioV79.bookingMatchesRequest(reqRequired,wrongBooking)')===false,'preferência obrigatória não aceita outra profissional');wrongBooking.items[0].pro='p1';ok(ev(r.ctx,'__imperioV79.bookingMatchesRequest(reqRequired,wrongBooking)')===true,'profissional obrigatória correta satisfaz solicitação');
// Auditoria canônica recebeu eventos da fila.
ok(ev(r.ctx,"db.auditEvents.some(x=>x.entityType==='waitlistRequest'&&x.action==='CREATE_WAITLIST')"),'criação integrada à Auditoria V64');ok(ev(r.ctx,"db.auditEvents.some(x=>x.entityType==='waitlistRequest'&&x.action==='WAITLIST_TO_BOOKING')"),'transformação em booking auditada');
// C14 LEGADO: banco anterior não inventa solicitações.
let legacy=run(JSON.stringify(baseDb()));setup(legacy);ok(!legacy.errors.length,'C14 banco legado inicializa');ok(ev(legacy.ctx,'db.waitlistRequests.length')===0,'C14 fila começa vazia sem backfill');ok(ev(legacy.ctx,'db.bookings.length')===0,'C14 bookings não viram solicitações');
// Migração idempotente.
let writes=r.ls.writeCount;ok(ev(r.ctx,'__imperioV79.migrate()')===false,'migração V79 segunda execução no-op');ok(r.ls.writeCount===writes,'migração idempotente sem escrita');
console.log(JSON.stringify({ok:true,scripts:scripts.length,tests,basic:true,preference:true,required:true,invalidWindow:true,multiunit:true,expiration:true,removal:true,contact:true,booking:true,cancelForm:true,duplicate:true,capacityNeutral:true,financialNeutral:true,legacy:true,audit:true,idempotent:true}));
