const fs=require('fs'),vm=require('vm');
const html=fs.readFileSync(__dirname+'/../index.html','utf8');
const scripts=[...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);
const code=scripts.find(s=>s.includes("const SCHEMA=93")&&s.includes('v93-reception-goals-performance-consolidation'));
if(!code)throw new Error('Bloco V93 não encontrado');
let tests=0;function ok(v,m){tests++;if(!v)throw new Error(m)}function eq(a,b,m){tests++;if(JSON.stringify(a)!==JSON.stringify(b))throw new Error(m+'\n'+JSON.stringify(a)+' != '+JSON.stringify(b))}
const allRows=[
 {bookingId:'b1',creatorId:'r1',createdDate:'2026-09-20',appointmentDate:'2026-09-28',unitId:'u1',status:'Agendado',clientId:'c1',clientName:'C1',commercialPrice:100},
 {bookingId:'b2',creatorId:'r1',createdDate:'2026-09-21',appointmentDate:'2026-09-28',unitId:'u1',status:'Confirmado',clientId:'c2',clientName:'C2',commercialPrice:50},
 {bookingId:'b3',creatorId:'r1',createdDate:'2026-09-22',appointmentDate:'2026-09-28',unitId:'u1',status:'Cancelado',clientId:'c3',clientName:'C3',commercialPrice:90},
 {bookingId:'b4',creatorId:'r1',createdDate:'2026-09-23',appointmentDate:'2026-09-28',unitId:'u1',status:'Faltou',clientId:'c4',clientName:'C4',commercialPrice:80},
 {bookingId:'p1',creatorId:'r1',createdDate:'2026-09-05',appointmentDate:'2026-09-14',unitId:'u1',status:'Agendado',clientId:'c5',clientName:'C5',commercialPrice:75},
 {bookingId:'p2',creatorId:'r1',createdDate:'2026-09-06',appointmentDate:'2026-09-14',unitId:'u1',status:'Confirmado',clientId:'c6',clientName:'C6',commercialPrice:25},
 {bookingId:'x1',creatorId:'r2',createdDate:'2026-09-20',appointmentDate:'2026-09-28',unitId:'u1',status:'Agendado',clientId:'c7',clientName:'C7',commercialPrice:300}
];
let filter={createdFrom:'2026-09-15',createdTo:'2026-09-28',appointmentFrom:'',appointmentTo:'',creator:'r1',status:'valid',unit:'u1'};
function metric(rows){return {bookings:new Set(rows.map(r=>r.bookingId)).size,services:rows.length,clients:new Set(rows.map(r=>r.clientId||`name:${r.clientName}`)).size,value:rows.reduce((s,r)=>s+Number(r.commercialPrice||0),0)}}
function filtered(){return allRows.filter(r=>r.createdDate>=filter.createdFrom&&r.createdDate<=filter.createdTo&&(filter.unit==='all'||r.unitId===filter.unit)&&(filter.creator==='all'||r.creatorId===filter.creator)&&(filter.status!=='valid'||!['Cancelado','Faltou'].includes(r.status)))}
const goal={id:'g1',receptionUserId:'r1',receptionUserNameSnapshot:'Recepção 1',unitIds:['u1'],unitNamesSnapshot:['Big'],periodFrom:'2026-09-01',periodTo:'2026-09-30',targetValue:500,targetServices:10,targetClients:8,status:'ACTIVE'};
let saves=0,trend={available:true,state:'ahead',deltaPp:12.5,sampleCount:6,minSamples:4};
const ctx={console,Date,setTimeout:()=>0,clearTimeout:()=>{},confirm:()=>true};ctx.window=ctx;ctx.document={getElementById:()=>null};
ctx.escapeHtml=s=>String(s);ctx.money=n=>'R$ '+Number(n).toFixed(2);ctx.formatDateBR=s=>String(s);ctx.db={schemaVersion:92,migrationHistory:[],receptionBookingGoals:[goal],units:[{id:'u1',name:'Big',active:true}],demoCashMovements:[{id:'c',amount:10}],demoFinancialEntries:[{id:'f',amount:20}],commissionEvents:[{id:'e',amount:5}]};
ctx.save=()=>{saves++};ctx.__imperioV85={state:()=>filter,rows:()=>allRows,filteredRows:filtered,metric};ctx.__imperioV83={allRows:()=>allRows,metrics:metric};ctx.__imperioV84={allowedUnits:()=>ctx.db.units,goalMetrics:g=>metric(allRows.filter(r=>r.creatorId===g.receptionUserId&&r.createdDate>=g.periodFrom&&r.createdDate<=g.periodTo&&g.unitIds.includes(r.unitId)&&!['Cancelado','Faltou'].includes(r.status))),goalTimeState:()=> 'Em andamento'};ctx.__imperioV88={trendFor:()=>trend};
vm.createContext(ctx);vm.runInContext(code,ctx);const api=ctx.__imperioV93;
ok(api.schema===93,'API schema 93');ok(ctx.db.schemaVersion===93,'schema migrado');ok(ctx.db.migrationHistory.filter(x=>x.id==='v93-reception-goals-performance-consolidation').length===1,'migration única');ok(saves===1,'migration grava uma vez');let sv=saves;ok(api.migrate()===false,'migration idempotente');ok(saves===sv,'segunda migration sem save');
ok(api.financialImpact==='none','sem impacto financeiro');ok(api.businessRulesChanged===false,'sem regra de negócio nova');eq(api.canonicalSources,{results:'V83/V85',goals:'V84',historicalReference:'V88'},'fontes canônicas declaradas');
let cur=api.currentResult();ok(cur.metrics.bookings===2,'resultado atual reservas válidas');ok(cur.metrics.services===2,'resultado atual serviços');ok(cur.metrics.clients===2,'resultado clientes únicos');ok(cur.metrics.value===150,'resultado valor comercial');
let pp=api.previousPeriod();eq({from:pp.from,to:pp.to,days:pp.days},{from:'2026-09-01',to:'2026-09-14',days:14},'período anterior mesma duração');let prev=api.previousRows();ok(prev.length===2,'linhas do período anterior');let tc=api.temporalComparison();ok(tc.current.value===150&&tc.previous.value===100,'comparação valor');ok(tc.current.bookings===2&&tc.previous.bookings===2,'comparação bookings');ok(tc.deltas.value.available&&tc.deltas.value.value===50,'delta percentual valor');ok(tc.deltas.bookings.value===0,'delta reservas zero');let dz=api.delta(10,0);ok(!dz.available&&dz.label==='sem base anterior','zero anterior não gera percentual enganoso');
let gc=api.goalContext();ok(gc.status==='single','meta única identificada');ok(gc.goal.id==='g1','meta correta');ok(gc.metrics.value===250,'meta usa métrica V84 do período completo');filter.creator='all';ok(api.goalContext().status==='none','sem mistura de metas com todos usuários');filter.creator='r1';ctx.db.receptionBookingGoals.push({...goal,id:'g2',periodFrom:'2026-09-15',periodTo:'2026-10-15'});ok(api.goalContext().status==='multiple','múltiplas metas explicitadas');ctx.db.receptionBookingGoals=[goal];
let hr=api.historicalReference();ok(!hr.available&&hr.reason==='select_single_day','referência exige dia/unidade');filter.appointmentFrom='2026-09-28';filter.appointmentTo='2026-09-28';hr=api.historicalReference();ok(hr.available,'referência V88 disponível');ok(hr.label==='Acima do ritmo histórico','referência descritiva');ok(hr.deltaPp===12.5&&hr.sampleCount===6,'dados V88 preservados');trend={available:false,state:'insufficient_history',sampleCount:2,minSamples:4};hr=api.historicalReference();ok(!hr.available&&hr.reason==='insufficient','histórico insuficiente explícito');ok(hr.message.includes('2/4'),'amostras insuficientes mostradas');
trend={available:true,state:'within',deltaPp:1,sampleCount:6,minSamples:4};let ph=api.panelHtml();for(const text of ['Resultado atual','Meta operacional','Referência histórica','Evolução temporal','resultado ≠ meta ≠ referência histórica'])ok(ph.includes(text),'painel contém '+text);ok(ph.includes('não representa receita')||ph.includes('não reconhece receita'),'valor não confundido com receita');ok(ph.includes('não cria pontuação ou ranking'),'sem ranking');
let labelNode={textContent:'Meta do dia'},metaNode={textContent:'base comparável',attrs:{},setAttribute(k,v){this.attrs[k]=v}},cardNode={title:'',querySelector(sel){return sel==='.label'?labelNode:sel==='.meta'?metaNode:null}},rootNode={querySelectorAll(){return [cardNode]}};ctx.document.getElementById=id=>id==='v70AgendaOps'?rootNode:null;ok(api.patchAgendaSemantics()===true,'patch semântico da Agenda aplicado');ok(labelNode.textContent==='Referência histórica','Meta do dia renomeada como referência histórica');ok(/Não é meta comercial/.test(cardNode.title),'tooltip separa referência de meta');ok(metaNode.attrs['data-v93-reference']==='historical','marcador de referência histórica');
let finBefore=JSON.stringify({cash:ctx.db.demoCashMovements,fin:ctx.db.demoFinancialEntries,commission:ctx.db.commissionEvents});api.currentResult();api.temporalComparison();api.goalContext();api.historicalReference();let finAfter=JSON.stringify({cash:ctx.db.demoCashMovements,fin:ctx.db.demoFinancialEntries,commission:ctx.db.commissionEvents});ok(finBefore===finAfter,'consultas não alteram financeiro');
console.log(JSON.stringify({ok:true,tests,schema:ctx.db.schemaVersion,currentValue:cur.metrics.value,previousValue:tc.previous.value,goalValue:gc.metrics.value}));
