import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';

export const COLLECTION_ID_FIELDS = Object.freeze({
  units:'id',categories:'id',acquisitionSources:'id',services:'id',pros:'id',clients:'id',bookings:'id',paymentMethods:'id',financialAccounts:'id',
  demoCashMovements:'id',demoFinancialEntries:'id',cashSessions:'id',cashAudits:'id',professionalCommissionAdjustments:'id',tipMovements:'id',
  clientAppointments:'id',clientCommands:'id',demoProducts:'id',demoPackageCatalog:'id',clientCreditMovements:'id',clientPackages:'id',clientReturns:'id',
  combos:'id',financeCategories:'id',companyEntities:'id',financeGoals:'id',stockProducts:'id',stockPurchases:'id',stockRequests:'id',stockTransfers:'id',
  stockMovements:'id',stockInputCosts:'id',stockFamilies:'id',stockSubstitutions:'id',commissionSettlements:'id',commissionPayments:'id',remunerationRules:'id',
  clientReceivables:'id',clientReceivablePayments:'id',commissionEvents:'id',tipDeductionRules:'id',migrationHistory:'id',syncOutbox:'id',syncConflicts:'id',
  auditEvents:'id',waitlistRequests:'id',waitlistOpportunities:'id',fiscalDocuments:'id',receptionBookingGoals:'id',agendaFillSnapshots:'id',userAccounts:'id'
});
const COLLECTION_COMPOSITE_KEYS = Object.freeze({
  stockBalances: row => `${String(row?.locationId||'')}|${String(row?.productId||'')}`,
  professionalDailyWork: row => `${String(row?.professionalId||'')}|${String(row?.unitId||'')}|${String(row?.date||'')}`,
});
const RECONCILE_OBJECT_EXCLUDES=new Set(['storageMeta','cutoverManifest','professionalObligationSnapshot']);
export function fnv1a32(input){let h=0x811c9dc5>>>0;for(let i=0;i<input.length;i++){h^=input.charCodeAt(i);h=Math.imul(h,0x01000193)>>>0}return h.toString(16).padStart(8,'0')}
export function legacyDataHash(value){return `fnv1a32:${fnv1a32(JSON.stringify(value))}`;}
export function sha256DataHash(value){return `sha256:${createHash('sha256').update(JSON.stringify(value)).digest('hex')}`;}
function stable(value){if(Array.isArray(value))return value.map(stable);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(k=>[k,stable(value[k])]));return value}
export function semanticHash(value){return `sha256:${createHash('sha256').update(JSON.stringify(stable(value))).digest('hex')}`;}
export function normalizePhone(v){const digits=String(v||'').replace(/\D/g,'');if(!digits)return '';if(digits.startsWith('55')&&digits.length>=12)return `+${digits}`;if(digits.length===10||digits.length===11)return `+55${digits}`;return `+${digits}`;}
function normalizeText(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
export function validateExport(env){const errors=[],warnings=[];if(!env||typeof env!=='object')return {ok:false,errors:['Envelope inválido'],warnings};if(env.format!=='imperio-central-migration')errors.push('Formato incompatível');if(!env.instanceId)errors.push('instanceId ausente');if(!Number.isInteger(Number(env.revision)))errors.push('revision inválida');if(!env.data||typeof env.data!=='object')errors.push('data ausente');const hashOk=env.data&&(env.dataHash===legacyDataHash(env.data)||env.dataHash===sha256DataHash(env.data));if(!hashOk)errors.push('Hash divergente');if(String(env.dataHash||'').startsWith('fnv1a32:'))warnings.push('Hash legado FNV-1a');const mode=env.data?.storageMeta?.dataMode;if(mode==='demo')errors.push('Export em modo demo');else if(!mode)warnings.push('storageMeta.dataMode ausente');return {ok:errors.length===0,errors,warnings,mode,canonicalHash:env.data?sha256DataHash(env.data):null};}
function rowMap(rows,keyer){const m=new Map();for(const row of rows||[]){const id=typeof keyer==='function'?keyer(row):String(row?.[keyer]||'');if(id)m.set(id,row)}return m}
function compareKeyed(name,keyer,exports){const maps=exports.map(x=>rowMap(Array.isArray(x.env.data?.[name])?x.env.data[name]:[],keyer));const all=new Set(maps.flatMap(m=>[...m.keys()]));const exclusive=[],conflicts=[];for(const id of [...all].sort()){const present=maps.map((m,i)=>m.has(id)?i:-1).filter(i=>i>=0);if(present.length!==maps.length){exclusive.push({id,presentIn:present.map(i=>exports[i].label),missingIn:exports.filter((_,i)=>!maps[i].has(id)).map(x=>x.label)});continue}const hashes=maps.map(m=>semanticHash(m.get(id)));if(new Set(hashes).size>1)conflicts.push({id,hashes:Object.fromEntries(exports.map((x,i)=>[x.label,hashes[i]]))});}return {collection:name,counts:Object.fromEntries(exports.map((x,i)=>[x.label,maps[i].size])),equal:exclusive.length===0&&conflicts.length===0,exclusive,conflicts};}
function compareUnkeyedSections(exports,known){const results=[];const keys=new Set(exports.flatMap(x=>Object.keys(x.env.data||{})));for(const key of [...keys].sort()){if(known.has(key)||RECONCILE_OBJECT_EXCLUDES.has(key))continue;const vals=exports.map(x=>x.env.data?.[key]);if(vals.every(v=>v===undefined))continue;if(vals.every(v=>Array.isArray(v))&&vals.every(v=>v.every(r=>r&&typeof r==='object'&&r.id))){results.push(compareKeyed(key,'id',exports));continue}const hashes=vals.map(v=>semanticHash(v));if(new Set(hashes).size>1)results.push({collection:key,counts:Object.fromEntries(exports.map((x,i)=>[x.label,Array.isArray(vals[i])?vals[i].length:(vals[i]===undefined?0:1)])),equal:false,exclusive:[],conflicts:[{id:'__section__',hashes:Object.fromEntries(exports.map((x,i)=>[x.label,hashes[i]]))}]});}return results;}
export function reconcileExports(inputs){if(!Array.isArray(inputs)||inputs.length<2)throw new Error('Informe pelo menos 2 exports');const exports=inputs.map((x,i)=>({label:x.label||`export_${i+1}`,env:x.env||x,validation:validateExport(x.env||x)}));const invalid=exports.filter(x=>!x.validation.ok);const report={format:'imperio-v98a-reconciliation',generatedAt:new Date().toISOString(),eligible:invalid.length===0,exports:exports.map(x=>({label:x.label,instanceId:x.env.instanceId,revision:x.env.revision,generatedAt:x.env.generatedAt||null,dataMode:x.validation.mode||null,canonicalHash:x.validation.canonicalHash,errors:x.validation.errors,warnings:x.validation.warnings})),collections:[],probableClientDuplicates:[],blockers:[]};if(invalid.length){report.blockers.push(...invalid.map(x=>`EXPORT_INVALID:${x.label}`));report.approvedForCanonicalBuild=false;return report}const specs={...COLLECTION_ID_FIELDS,...COLLECTION_COMPOSITE_KEYS};for(const [name,keyer] of Object.entries(specs))report.collections.push(compareKeyed(name,keyer,exports));report.collections.push(...compareUnkeyedSections(exports,new Set(Object.keys(specs))));const clients=[];exports.forEach((x,ix)=>(Array.isArray(x.env.data?.clients)?x.env.data.clients:[]).forEach(c=>clients.push({export:x.label,id:String(c.id||''),phone:normalizePhone(c.phone),name:normalizeText(c.name),rawName:c.name})));const byPhone=new Map();for(const c of clients){if(!c.phone)continue;if(!byPhone.has(c.phone))byPhone.set(c.phone,[]);byPhone.get(c.phone).push(c)}for(const [phone,rows] of byPhone){const ids=new Set(rows.map(r=>r.id));if(ids.size>1){const names=new Set(rows.map(r=>r.name));report.probableClientDuplicates.push({phone,classification:names.size===1?'strong_candidate':'ambiguous_shared_phone',records:rows});}}const summary={exclusive:0,conflicts:0};for(const c of report.collections){summary.exclusive+=c.exclusive.length;summary.conflicts+=c.conflicts.length;}report.summary=summary;if(summary.conflicts)report.blockers.push(`CONFLICTS:${summary.conflicts}`);if(report.probableClientDuplicates.length)report.blockers.push(`CLIENT_DUPLICATES:${report.probableClientDuplicates.length}`);report.approvedForCanonicalBuild=report.eligible&&summary.conflicts===0&&report.probableClientDuplicates.length===0&&report.blockers.length===0;return report;}
function parseArgs(argv){const inputs=[],rest=[...argv];let out='';while(rest.length){const a=rest.shift();if(a==='--out')out=rest.shift();else if(a)inputs.push(a)}return {inputs,out}}
if(process.argv[1]===fileURLToPath(import.meta.url)){const {inputs,out}=parseArgs(process.argv.slice(2));if(inputs.length<2){console.error('Uso: node tools/reconcile-exports.mjs exportA.json exportB.json [exportC.json] --out relatorio.json');process.exit(2)}const loaded=inputs.map(f=>({label:path.basename(f),env:JSON.parse(fs.readFileSync(f,'utf8'))}));const report=reconcileExports(loaded);const text=JSON.stringify(report,null,2);if(out)fs.writeFileSync(out,text);else console.log(text);process.exitCode=report.eligible?0:1;}
