const fs=require('fs'),vm=require('vm');
const html=fs.readFileSync(__dirname+'/../index.html','utf8');
const scripts=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);
class FixedDate extends Date{constructor(...a){super(...(a.length?a:['2026-09-28T10:30:00-03:00']))}static now(){return Date.parse('2026-09-28T10:30:00-03:00')}}
class MockStorage{constructor(raw){this.m=new Map(raw==null?[]:[['imperio-demo-v1',raw]]);this.writeCount=0}getItem(k){return this.m.has(k)?this.m.get(k):null}setItem(k,v){this.writeCount++;this.m.set(k,String(v))}removeItem(k){this.m.delete(k)}clear(){this.m.clear()}}
function element(id=''){return {id,value:'',checked:false,innerHTML:'',outerHTML:'',textContent:'',style:{},dataset:{},children:[],options:[],selectedIndex:0,className:'',src:'',href:'',files:[],disabled:false,firstChild:null,parentNode:null,classList:{add(){},remove(){},toggle(){return false},contains(){return false}},appendChild(x){this.children.push(x);x.parentNode=this;return x},insertBefore(x){this.children.unshift(x);x.parentNode=this;return x},remove(){},click(){},focus(){},select(){},insertAdjacentElement(){},insertAdjacentHTML(pos,h){this.innerHTML+=h},addEventListener(){},removeEventListener(){},querySelector(){return null},querySelectorAll(){return[]},closest(){return null},contains(){return false},setAttribute(){},getAttribute(){return null}}}
function run(raw){const els=new Map(),qsAll=new Map();const doc={body:element('body'),documentElement:element('html'),_qsAll:qsAll,getElementById(id){if(!els.has(id))els.set(id,element(id));return els.get(id)},querySelector(){return null},querySelectorAll(sel){return qsAll.get(sel)||[]},createElement(tag){return element(tag)},addEventListener(){},removeEventListener(){}};const ls=new MockStorage(raw),ss=new MockStorage(null);const ctx={console,localStorage:ls,sessionStorage:ss,document:doc,window:null,navigator:{clipboard:{writeText:async()=>{}}},location:{},history:{},setTimeout:(f)=>{try{f()}catch{}},clearTimeout(){},setInterval(){return 1},clearInterval(){},structuredClone:global.structuredClone,Date:FixedDate,JSON,Math,Number,String,Array,Object,Map,Set,Intl,RegExp,Promise,Blob:function(){},FileReader:function(){},URL:{createObjectURL:()=>'',revokeObjectURL(){}},confirm:()=>true,prompt:()=>'',alert:()=>{},fetch:async()=>({ok:false,json:async()=>({})}),event:{target:null}};ctx.window=ctx;vm.createContext(ctx);const errors=[];for(let i=0;i<scripts.length;i++){try{vm.runInContext(scripts[i],ctx,{filename:`script${i}.js`})}catch(e){errors.push(`script ${i}: ${e.stack||e}`);break}}return {ctx,ls,ss,els,doc,errors}}
function ev(ctx,code){return vm.runInContext(code,ctx)}
function assert(c,m){if(!c)throw new Error(m)}let tests=0;function ok(c,m){tests++;assert(c,m)}function eq(a,b,m){ok(JSON.stringify(a)===JSON.stringify(b),`${m}: ${JSON.stringify(a)} != ${JSON.stringify(b)}`)}
function hist(){return ['v58-legacy-commission-unit-tip-money-hardening','v59-reports-services-stock','v60-reports-finance-dre','v61-finance-dre-stabilization','v62-reports-marketing','v63-settings-users-operators','v64-audit-core-critical-events','v65-executive-overview','v66-notifications-management-tasks','v67-custom-user-permissions','v68-fiscal-foundation','v69-nfse-national-direct','v70-agenda-operational-metrics','v71-configurable-fields-options-clients','v72-configurable-fields-options-agenda-commands','v73-configurable-fields-options-professionals-stock','v74-configurable-fields-options-finance','v75-dre-combo-profitability-allocation','v76-fiscal-payments-booking-authorship','v77-workstations-physical-capacity'].map(id=>({id}))}
function sch(start='09:00',end='20:00'){let x={};for(let i=0;i<7;i++)x['u1-'+i]={work:true,start,end},x['u2-'+i]={work:true,start,end};return x}
function baseDb(){return {schemaVersion:77,migrationHistory:hist(),units:[{id:'u1',name:'Big Shopping',active:true,show:true,online:true},{id:'u2',name:'Shopping Contagem',active:true,show:true,online:true}],categories:[{id:'c_man',name:'Manicure',active:true},{id:'c_long',name:'Alongamento',active:true},{id:'c_hair',name:'Cabelo',active:true}],services:[{id:'s_man',name:'Manicure',category:'c_man',price:40,duration:40,active:true,show:true,online:true,proRules:{}},{id:'s_long',name:'Alongamento',category:'c_long',price:120,duration:60,active:true,show:true,online:true,proRules:{}},{id:'s_hair',name:'Cabelo',category:'c_hair',price:80,duration:40,active:true,show:true,online:true,proRules:{}}],pros:Array.from({length:8},(_,i)=>({id:'p'+(i+1),name:'Pro '+(i+1),active:true,show:true,online:true,units:['u1'],services:['s_man'],schedule:sch()})),clients:[{id:'cl1',name:'Cliente 1',phone:'3199999999',source:'Instagram',origin:'Presencial',registrationUnit:'u1'},{id:'cl2',name:'Cliente 2',phone:'3188888888',source:'Google',origin:'Presencial',registrationUnit:'u1'}],bookings:[],clientAppointments:[],clientCommands:[],paymentMethods:[],financialAccounts:[],demoCashMovements:[],demoFinancialEntries:[],cashSessions:[],cashAudits:[],auditEvents:[],clientCreditMovements:[],clientReceivables:[],clientReceivablePayments:[],commissionEvents:[],remunerationRules:[],tipMovements:[],tipDeductionRules:[],demoProducts:[],demoPackageCatalog:[],clientPackages:[],clientReturns:[],combos:[],financeCategories:[],companyEntities:[],financeGoals:[],stockProducts:[],stockBalances:[],stockPurchases:[],stockRequests:[],stockTransfers:[],stockMovements:[],stockInputCosts:[],stockFamilies:[],stockSubstitutions:[],commissionSettlements:[],commissionPayments:[],commissionAdjustments:[],professionalCommissionAdjustments:[],professionalDailyWork:[],managementTasks:[],notificationAlertStates:{},notificationSettings:{},fiscalDocuments:[],fiscalSettings:{},reportSettings:{inactiveDays:90,returnLateGraceDays:7,capacityProductivityFactor:95},commissionSettings:{discountsReduceBase:true,directPaymentReducesSettlement:true,comboAllocation:'proportional'},storageMeta:{dataMode:'real',createdAt:'2026-09-01T00:00:00.000Z',storageSafetyVersion:1},userAccounts:[{id:'usr_admin',name:'Admin',username:'admin',password:'x',role:'admin',active:true,allUnits:true,unitIds:[]},{id:'usr_mgr',name:'Gerente Big',username:'mgr',password:'x',role:'manager',active:true,allUnits:false,unitIds:['u1']},{id:'usr_mgr2',name:'Gerente Contagem',username:'mgr2',password:'x',role:'manager',active:true,allUnits:false,unitIds:['u2']}],systemSettings:{settingsVersion:1,formFields:{},optionSets:{}},communicationSettings:{whatsapp:{mode:'manual_link',version:1,unitNumbers:{},templates:{confirmation:'',reminder:'',reactivation:'',monthly_receivable:''}}},workstations:[]}}
function setup(r,user='usr_mgr'){for(const id of ['adminTabs','unitPicker','subbar','adminPage','loginUser','loginPass','modalHost','ebDate','ebStatus','ebNotes','rDate','rStatus','rNotes'])r.ctx[id]=r.doc.getElementById(id);r.doc.getElementById('unitPicker').value='u1';r.ctx.unitPicker=r.doc.getElementById('unitPicker');r.ctx.page='agenda';r.ctx.agendaDate='2026-09-28';r.doc.getElementById('ebDate').value='2026-09-28';r.doc.getElementById('ebStatus').value='Agendado';r.doc.getElementById('ebNotes').value='';r.doc.getElementById('rDate').value='2026-09-28';r.doc.getElementById('rStatus').value='Agendado';r.doc.getElementById('rNotes').value='';ev(r.ctx,`__imperioV63.sessionSet('${user}')`)}
function stations(n,cat='c_man',unit='u1'){return Array.from({length:n},(_,i)=>({id:`ws${i+1}`,unitId:unit,name:`Est ${i+1}`,allowedCategoryIds:[cat],active:true,createdAt:'x',updatedAt:'x'}))}
function bookings(n,time='10:00',service='s_man',unit='u1',date='2026-09-28'){return Array.from({length:n},(_,i)=>({id:`b${i+1}`,unit,date,clientId:'cl1',client:'Cliente '+(i+1),status:'Agendado',items:[{serviceId:service,service,pro:`p${(i%8)+1}`,time,duration:40,price:40}]}))}
let r=run(JSON.stringify(baseDb()));setup(r);ok(!r.errors.length,'runtime sem erro');ok(scripts.length===61,'41 scripts');ok(ev(r.ctx,'db.schemaVersion')===97,'schema 78');ok(ev(r.ctx,"db.migrationHistory.filter(x=>(typeof x==='string'?x:x.id)==='v78-physical-capacity-alerts').length")===1,'migração V78 única');ok(ev(r.ctx,"typeof __imperioV78.physicalAlerts==='function'&&typeof evaluatePhysicalCapacity==='function'"),'V78 reutiliza motor V77');
// 1 NORMAL
r.ctx.st=stations(6);ev(r.ctx,'db.workstations=st');r.ctx.bks=bookings(5);ev(r.ctx,'db.bookings=bks;__imperioV78.invalidate()');let im=ev(r.ctx,"__imperioV78.indicatorModel('u1','2026-09-28')");ok(im.state==='normal'&&im.day.maxConcurrent===5&&!im.day.hasConflict,'C1 indicador normal 5 demandas / 6 estações');
ev(r.ctx,"adminPage.innerHTML='<div class=\"agenda-toolbar\"><div class=\"toolbar-spacer\"></div></div>';page='agenda';agendaDate='2026-09-28';unitPicker.value='u1'");ok(ev(r.ctx,'__imperioV78.injectAgendaIndicator()')===true&&r.doc.getElementById('adminPage').innerHTML.includes('todas alocáveis'),'C1 indicador visual normal');
// 2 CONFLITO REAL
r.ctx.bks=bookings(7);ev(r.ctx,'db.bookings=bks;__imperioV78.invalidate()');im=ev(r.ctx,"__imperioV78.indicatorModel('u1','2026-09-28')");ok(im.state==='conflict'&&im.day.maxUnallocated===1,'C2 conflito real indicador');let real=ev(r.ctx,'__imperioV78.physicalRealAlerts()');ok(real.length===1&&real[0].unallocated===1&&real[0].physicalType==='real','C2 alerta real criado');ok(real[0].recipients.some(x=>x.id==='usr_mgr')&&!real[0].recipients.some(x=>x.id==='usr_mgr2'),'C2 alerta roteado por unidade');
// 3 SUFICIENTE NUMERICAMENTE MAS INCOMPATÍVEL
ev(r.ctx,"db.workstations=[{id:'m1',unitId:'u1',name:'M1',allowedCategoryIds:['c_man'],active:true},{id:'m2',unitId:'u1',name:'M2',allowedCategoryIds:['c_man'],active:true}];db.bookings=[{id:'bm',unit:'u1',date:'2026-09-28',client:'A',status:'Agendado',items:[{serviceId:'s_man',service:'Manicure',pro:'p1',time:'11:00',duration:40}]},{id:'bh',unit:'u1',date:'2026-09-28',client:'B',status:'Agendado',items:[{serviceId:'s_hair',service:'Cabelo',pro:'p2',time:'11:00',duration:40}]}];__imperioV78.invalidate()");im=ev(r.ctx,"__imperioV78.indicatorModel('u1','2026-09-28')");ok(im.state==='conflict'&&im.day.maxConcurrent===2&&im.day.maxUnallocated===1,'C3 matching real detecta incompatibilidade apesar de 2 estações');
// 4 ESTAÇÃO VERSÁTIL
ev(r.ctx,"db.workstations=[{id:'m1',unitId:'u1',name:'M1',allowedCategoryIds:['c_man'],active:true},{id:'v1',unitId:'u1',name:'Vers',allowedCategoryIds:['c_man','c_long'],active:true}];db.bookings=[{id:'bm',unit:'u1',date:'2026-09-28',client:'A',status:'Agendado',items:[{serviceId:'s_man',service:'Manicure',pro:'p1',time:'12:00',duration:40}]},{id:'bl',unit:'u1',date:'2026-09-28',client:'B',status:'Agendado',items:[{serviceId:'s_long',service:'Alongamento',pro:'p2',time:'12:00',duration:40}]}];__imperioV78.invalidate()");im=ev(r.ctx,"__imperioV78.indicatorModel('u1','2026-09-28')");ok(im.state==='normal'&&!im.day.hasConflict,'C4 estação versátil não gera falso alerta');
// 5 CANCELAMENTO RESOLVE
ev(r.ctx,"db.workstations="+JSON.stringify(stations(1))+";db.bookings="+JSON.stringify(bookings(2,'13:00'))+";__imperioV78.invalidate()");ok(ev(r.ctx,'__imperioV78.physicalRealAlerts().length')===1,'C5 conflito inicial');ev(r.ctx,"db.bookings[1].status='Cancelado';__imperioV78.invalidate()");ok(ev(r.ctx,'__imperioV78.physicalRealAlerts().length')===0,'C5 cancelamento remove alerta ativo');
// 6 REAGENDAMENTO CRIA CONFLITO E É PERMITIDO
ev(r.ctx,"db.workstations="+JSON.stringify(stations(1))+";db.bookings=[{id:'e1',unit:'u1',date:'2026-09-28',clientId:'cl1',client:'A',status:'Agendado',items:[{serviceId:'s_man',service:'Manicure',pro:'p1',time:'14:00',duration:40,price:40}],createdByUserId:'usr_mgr',createdBy:'Gerente Big'},{id:'e2',unit:'u1',date:'2026-09-28',clientId:'cl2',client:'B',status:'Agendado',items:[{serviceId:'s_man',service:'Manicure',pro:'p2',time:'15:00',duration:40,price:40}],createdByUserId:'usr_mgr',createdBy:'Gerente Big'}];editBookingId='e2';editBookingDraft=structuredClone(db.bookings[1]);editBookingDraft.items[0].time='14:10'");let out=ev(r.ctx,'saveExistingBooking()');ok(out!==false&&ev(r.ctx,"db.bookings.find(x=>x.id==='e2').items[0].time")==='14:10','C6 reagendamento permitido');ok(ev(r.ctx,'__imperioV78.physicalRealAlerts().length')===1,'C6 reagendamento gera alerta real');
// 7 SEM CONFIGURAÇÃO
ev(r.ctx,'db.workstations=[];__imperioV78.invalidate()');im=ev(r.ctx,"__imperioV78.indicatorModel('u1','2026-09-28')");ok(im.state==='not-configured','C7 indicador não configurado');ok(ev(r.ctx,'__imperioV78.physicalRealAlerts().length')===0,'C7 sem falso alerta');
// 8 MULTIUNIDADE
ev(r.ctx,"db.workstations="+JSON.stringify(stations(1,'c_man','u1'))+";db.bookings="+JSON.stringify(bookings(2,'15:00','s_man','u1'))+";__imperioV78.invalidate()");real=ev(r.ctx,'__imperioV78.physicalRealAlerts()');ok(real.length===1&&real[0].unitId==='u1','C8 conflito não contamina outra unidade');
// 9 RISCO DE ESCALA sem conflito real
ev(r.ctx,"db.bookings=[];db.workstations="+JSON.stringify(stations(2))+";db.pros=db.pros.slice(0,3);db.pros.forEach(p=>{p.services=['s_man'];p.units=['u1'];p.schedule="+JSON.stringify(sch())+"});__imperioV78.invalidate()");let prev=ev(r.ctx,'__imperioV78.preventiveAlerts()');ok(prev.length>=1&&prev[0].physicalType==='preventive'&&prev[0].unallocated===1,'C9 alerta preventivo pela escala');ok(ev(r.ctx,'__imperioV78.physicalRealAlerts().length')===0,'C9 preventivo não vira conflito real');
// 10 DEDUPLICAÇÃO
let a1=ev(r.ctx,'__imperioV78.physicalAlerts()'),a2=ev(r.ctx,'__imperioV78.physicalAlerts()');eq(a1.map(x=>x.key),a2.map(x=>x.key),'C10 mesmas avaliações geram mesmas chaves');ok(new Set(a1.map(x=>x.key)).size===a1.length,'C10 sem duplicidade lógica');
// 11 INATIVAÇÃO CRIA RISCO/CONFLITO
ev(r.ctx,"db.pros=db.pros.slice(0,2);db.bookings="+JSON.stringify(bookings(2,'16:00'))+";db.workstations="+JSON.stringify(stations(2))+";__imperioV78.invalidate()");ok(ev(r.ctx,'__imperioV78.physicalRealAlerts().length')===0,'C11 antes da inativação sem conflito');ev(r.ctx,"db.workstations[1].active=false;db.workstations[1].updatedAt=new Date().toISOString();__imperioV78.invalidate()");ok(ev(r.ctx,'__imperioV78.physicalRealAlerts().length')===1,'C11 inativação recalcula e cria alerta');
// 12 REATIVAÇÃO RESOLVE
ev(r.ctx,"db.workstations[1].active=true;db.workstations[1].updatedAt=new Date().toISOString();__imperioV78.invalidate()");ok(ev(r.ctx,'__imperioV78.physicalRealAlerts().length')===0,'C12 reativação resolve alerta');
// 13 NÃO BLOQUEIO NOVO AGENDAMENTO
ev(r.ctx,"db.workstations="+JSON.stringify(stations(1))+";db.bookings="+JSON.stringify(bookings(1,'17:00'))+";db.pros=[{id:'p1',name:'P1',active:true,units:['u1'],services:['s_man'],schedule:"+JSON.stringify(sch())+"},{id:'p2',name:'P2',active:true,units:['u1'],services:['s_man'],schedule:"+JSON.stringify(sch())+"}];resDraft={date:'2026-09-28',clientId:'cl2',status:'Agendado',notes:'',items:[{serviceId:'s_man',service:'Manicure',pro:'p2',time:'17:00',duration:40,price:40,preference:false,forceFit:false}]};unitPicker.value='u1'");let n0=ev(r.ctx,'db.bookings.length');out=ev(r.ctx,'saveReservation()');ok(out!==false&&ev(r.ctx,'db.bookings.length')===n0+1,'C13 agendamento salva apesar do conflito físico');ok(ev(r.ctx,'__imperioV78.physicalRealAlerts().length')===1,'C13 sistema apenas informa após salvar');
// Estados e Central V66 reutilizados.
let key=ev(r.ctx,'__imperioV78.physicalRealAlerts()[0].key');ok(ev(r.ctx,`__imperioV78.setAlertState('${key}','SEEN')`)===true&&ev(r.ctx,`db.notificationAlertStates['${key}'].status`)==='SEEN','estado Visto usa notificationAlertStates existente');ok(ev(r.ctx,`__imperioV78.setAlertState('${key}','ANALYSIS')`)===true&&ev(r.ctx,`db.notificationAlertStates['${key}'].status`)==='ANALYSIS','estado Em análise persistido');
ev(r.ctx,"page='actions';adminPage.innerHTML='<div class=\"v66-filter\"></div>'");ok(ev(r.ctx,'__imperioV78.patchActions()')===true&&r.doc.getElementById('adminPage').innerHTML.includes('Capacidade física'),'Central de Ações recebe seção física');
// Migração idempotente.
let writes=r.ls.writeCount;ok(ev(r.ctx,'__imperioV78.migrate()')===false,'migração V78 segunda execução no-op');ok(r.ls.writeCount===writes,'migração idempotente sem escrita');
console.log(JSON.stringify({ok:true,scripts:scripts.length,tests,normal:true,realConflict:true,matching:true,versatile:true,cancelResolve:true,reschedule:true,notConfigured:true,multiunit:true,preventive:true,dedupe:true,stationToggle:true,nonBlocking:true,states:true,idempotent:true}));
