const fs=require('fs'),vm=require('vm');
const html=fs.readFileSync(__dirname+'/../index.html','utf8');
const scripts=[...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);
const code=scripts.find(s=>s.includes('CORREÇÃO AUDITADA'));
if(!code)throw new Error('Bloco V83 corrigido não encontrado');
const ctx={console,setTimeout:()=>{},structuredClone:global.structuredClone};ctx.window=ctx;ctx.document={getElementById:()=>null};
ctx.db={schemaVersion:83,migrationHistory:[{id:'v83-booking-author-performance-audit'}],units:[{id:'u1',name:'Big',active:true},{id:'u2',name:'Centro',active:true}],userAccounts:[{id:'r1',name:'Recepção A',role:'reception',active:true,unitIds:['u1']},{id:'r2',name:'Recepção B',role:'reception',active:true,unitIds:['u1']},{id:'r3',name:'Recepção C',role:'reception',active:true,unitIds:['u2']}],services:[{id:'s1',name:'Manicure'},{id:'s3',name:'Pedicure'}],pros:[{id:'p1',name:'Ana',active:true,units:['u1']},{id:'p2',name:'Outra',active:true,units:['u2']}],clients:[{id:'c1',name:'Juliana'},{id:'c2',name:'Maria'}],bookings:[{id:'b1',unit:'u1',date:'2026-10-03',clientId:'c1',client:'Juliana',status:'Agendado',createdAt:'2026-09-29T02:30:00.000Z',createdByUserId:'r1',createdBy:'Recepção A',sourceType:'internal_booking',items:[{serviceId:'s1',service:'Manicure',pro:'p1',time:'15:00',duration:45,price:40},{serviceId:'s3',service:'Pedicure',pro:'p1',time:'16:00',duration:45,price:40}]},{id:'b2',unit:'u1',date:'2026-10-04',clientId:'c2',client:'Maria',status:'Cancelado',createdAt:'2026-09-28T15:00:00.000Z',createdByUserId:'r1',createdBy:'Recepção A',sourceType:'internal_booking',items:[{serviceId:'s1',service:'Manicure',pro:'p1',time:'15:00',duration:45,price:100}]},{id:'b3',unit:'u2',date:'2026-10-05',clientId:'c2',client:'Maria',status:'Agendado',createdAt:'2026-09-28T15:00:00.000Z',createdByUserId:'r3',createdBy:'Recepção C',sourceType:'internal_booking',items:[{serviceId:'s1',service:'Manicure',pro:'p2',time:'15:00',duration:45,price:999}]}]};
ctx.save=()=>{};ctx.escapeHtml=s=>String(s);ctx.money=n=>`R$ ${Number(n).toFixed(2)}`;ctx.formatDateBR=s=>s.split('-').reverse().join('/');ctx.localDateISO=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;ctx.normalizeBooking=b=>b;ctx.bookingAttribution=b=>({userId:b.createdByUserId||'',name:b.createdBy||'',origin:b.sourceType||'',createdAt:b.createdAt||'',reliability:b.createdByUserId?'captured_user':'legacy_unknown'});ctx.comboApplicationsFromEntries=entries=>{const a=entries.find(e=>e.serviceId==='s1'),b=entries.find(e=>e.serviceId==='s3');return a&&b?[{name:'Mão + Pé',discount:15,picks:[a.key,b.key]}]:[]};const current={id:'mgr',role:'manager',unitIds:['u1'],active:true};ctx.__imperioV63={currentUser:()=>current,allowedUnits:()=>ctx.db.units.filter(u=>u.id==='u1')};
vm.createContext(ctx);vm.runInContext(code,ctx);const api=ctx.__imperioV83;let tests=0;function ok(v,m){tests++;if(!v)throw new Error(m)}
const rows=api.allRows(),b1=rows.filter(r=>r.bookingId==='b1');ok(rows.length===3,'unidade restrita');ok(b1.length===2,'dois serviços');ok(Math.abs(b1.reduce((s,r)=>s+r.commercialPrice,0)-65)<1e-9,'combo total 65');ok(b1.every(r=>Math.abs(r.commercialPrice-32.5)<1e-9),'rateio combo');ok(b1[0].createdDate==='2026-09-28','data local');ok(b1[0].createdTime==='23:30','hora local');let f=api.filtered(),m=api.metrics(f);ok(f.length===2,'status válido padrão');ok(m.value===65&&m.services===2&&m.clients===1&&m.bookings===1,'métricas válidas');ctx.__v83Filters.status='all';f=api.filtered();m=api.metrics(f);ok(f.length===3,'todos os status');ok(m.value===165,'valor com cancelado auditável');ctx.__v83Filters.status='valid';ctx.__v83Filters.createdFrom='2026-09-28';ctx.__v83Filters.createdTo='2026-09-28';f=api.filtered();ok(f.length===2,'filtro data local');let groups=api.receiverGroups(f);ok(groups.some(g=>g.key==='r2'&&g.rows.length===0)&&!groups.some(g=>g.key==='r3'),'zero visível e unidade proibida oculta');console.log(JSON.stringify({ok:true,tests,comboTotal:65,localTimestamp:'28/09/2026 23:30',permission:true,defaultStatus:true,zeroReception:true}));
