const fs=require('fs'),vm=require('vm');
const html=fs.readFileSync(__dirname+'/../index.html','utf8');
const scripts=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);
class FixedDate extends Date{constructor(...a){super(...(a.length?a:['2026-09-28T18:30:00-03:00']))}static now(){return Date.parse('2026-09-28T18:30:00-03:00')}}
class MockStorage{constructor(raw){this.m=new Map(raw==null?[]:[['imperio-demo-v1',raw]]);this.writeCount=0}getItem(k){return this.m.has(k)?this.m.get(k):null}setItem(k,v){this.writeCount++;this.m.set(k,String(v))}removeItem(k){this.m.delete(k)}}
function el(id=''){return {id,value:'',checked:false,innerHTML:'',textContent:'',style:{},dataset:{},children:[],classList:{add(){},remove(){},toggle(){return false}},appendChild(){},remove(){},focus(){},click(){},querySelector(){return null},querySelectorAll(){return[]},closest(){return null},insertAdjacentHTML(p,h){this.innerHTML+=h},addEventListener(){},removeEventListener(){},removeAttribute(){},setAttribute(){},getAttribute(){return null}}}
function run(raw){const els=new Map(),doc={body:el('body'),documentElement:el('html'),getElementById(id){if(!els.has(id))els.set(id,el(id));return els.get(id)},querySelector(){return null},querySelectorAll(){return[]},createElement:t=>el(t),addEventListener(){},removeEventListener(){}};const ls=new MockStorage(raw);const ctx={console,document:doc,localStorage:ls,sessionStorage:new MockStorage(),window:null,navigator:{clipboard:{writeText:async()=>{}}},location:{},history:{},Date:FixedDate,JSON,Math,Number,String,Array,Object,Map,Set,Intl,RegExp,Promise,structuredClone:global.structuredClone,setTimeout:f=>{try{f()}catch{}},clearTimeout(){},setInterval(){return 1},clearInterval(){},confirm:()=>true,prompt:()=>'',alert:()=>{},fetch:async()=>({ok:false,json:async()=>({})}),Blob:function(){},FileReader:function(){},URL:{createObjectURL:()=>'',revokeObjectURL(){}},event:{target:null}};ctx.window=ctx;vm.createContext(ctx);let errors=[];for(let i=0;i<scripts.length;i++){try{vm.runInContext(scripts[i],ctx,{filename:'s'+i+'.js'})}catch(e){errors.push(e.stack||String(e));break}}return {ctx,ls,doc,els,errors}}
function ev(r,c){return vm.runInContext(c,r.ctx)}
let tests=0;function ok(c,m){tests++;if(!c)throw new Error(m)}function eq(a,b,m){ok(JSON.stringify(a)===JSON.stringify(b),m+': '+JSON.stringify(a)+' != '+JSON.stringify(b))}
function db(){return {schemaVersion:89,migrationHistory:[{id:'v89-structural-configurability-phase1'}],units:[{id:'u1',name:'U1',active:true}],categories:[{id:'c1',name:'Manicure',active:true,order:10,configVersion:1}],services:[{id:'s1',name:'Manicure',category:'c1',clientArea:'hands',mustFinishBeforeSameArea:false,active:true,price:45,duration:45,show:true,online:true,proRules:{}}],pros:[{id:'p1',name:'Ana',publicName:'Ana',specialty:'Manicure e Pedicure',agendaColor:'',units:['u1'],services:['s1'],active:true,show:true,online:true,schedule:{},accountType:'Corrente',pixType:'CPF'}],clients:[{id:'cl1',name:'Cliente',phone:'31999999999',source:'Instagram',origin:'Presencial',registrationUnit:'u1'}],bookings:[{id:'blk1',unit:'u1',date:'2026-09-29',client:'Bloqueado',status:'Bloqueado',notes:'Almoço',items:[{serviceId:'',service:'Almoço',pro:'p1',time:'12:00',duration:60,price:0}]},{id:'b1',unit:'u1',date:'2026-09-29',clientId:'cl1',client:'Cliente',status:'Cancelado',cancellationReason:'Imprevisto',items:[{serviceId:'s1',service:'Manicure',pro:'p1',time:'10:00',duration:45,price:45}]}],workstations:[],acquisitionSources:[{id:'a1',name:'Instagram',active:true}],paymentMethods:[],financialAccounts:[],demoCashMovements:[{id:'cm1',amount:10}],demoFinancialEntries:[{id:'fe1',amount:10}],cashSessions:[],cashAudits:[],auditEvents:[],clientAppointments:[],clientCommands:[],demoProducts:[],demoPackageCatalog:[],clientCreditMovements:[],clientPackages:[],clientReturns:[],combos:[],financeCategories:[],companyEntities:[],financeGoals:[],stockProducts:[{id:'sp1',name:'Shampoo',type:'INPUT',unit:'un',baseUnit:'un',group:'Capilar',allocations:{c1:100}}],stockBalances:[],stockPurchases:[],stockRequests:[],stockTransfers:[],stockMovements:[],stockInputCosts:[],stockFamilies:[],stockSubstitutions:[],commissionSettlements:[],commissionPayments:[],professionalCommissionAdjustments:[],tipMovements:[],remunerationRules:[],professionalDailyWork:[],clientReceivables:[],clientReceivablePayments:[],commissionEvents:[],tipDeductionRules:[],managementTasks:[],notificationAlertStates:{},notificationSettings:{},fiscalDocuments:[],fiscalSettings:{},reportSettings:{},commissionSettings:{},userAccounts:[{id:'adm',name:'Admin',username:'a',password:'x',role:'admin',active:true,allUnits:true,unitIds:[]}],systemSettings:{settingsVersion:1,formFields:{clients:{},professionals:{},agenda:{},stock:{}},optionSets:{}},communicationSettings:{whatsapp:{unitNumbers:{},templates:{}}},agendaFillSnapshots:[],agendaFillTrendSettings:{historyWindowDays:180,maxSamples:8,minSamples:4,thresholdPp:8},waitlistRequests:[],waitlistOpportunities:[]}}
let r=run(JSON.stringify(db()));ok(!r.errors.length,'runtime sem erro');ok(scripts.length===61,'54 scripts');ok(ev(r,'db.schemaVersion')===97,'schema 90');ok(ev(r,'__imperioV90.schema')===90,'API V90');ok(ev(r,"db.migrationHistory.filter(x=>(typeof x==='string'?x:x.id)==='v90-structural-configurability-phase2').length")===1,'migration V90 única');
for(const k of ['clients.tags','professionals.specialty','agenda.blockReason','agenda.cancellationReason','stock.productGroup'])ok(ev(r,`!!db.systemSettings.optionSets['${k}']`),'catálogo '+k);
ok(ev(r,"db.systemSettings.formFields.clients.tags.optionSet==='clients.tags'"),'tags ligadas ao catálogo');ok(ev(r,"db.systemSettings.formFields.professionals.specialty.optionSet==='professionals.specialty'"),'especialidade ligada ao catálogo');ok(ev(r,"db.systemSettings.formFields.agenda.blockReason.optionSet==='agenda.blockReason'"),'motivo bloqueio ligado ao catálogo');ok(ev(r,"db.systemSettings.formFields.agenda.cancellationReason.optionSet==='agenda.cancellationReason'"),'motivo cancelamento ligado ao catálogo');ok(ev(r,"db.systemSettings.formFields.stock.group.optionSet==='stock.productGroup'"),'grupo estoque ligado ao catálogo');
ok(ev(r,"__imperioV90.getSet('professionals.specialty').options.some(o=>o.value==='Manicure e Pedicure')"),'especialidade histórica sem perda');ok(ev(r,"__imperioV90.getSet('agenda.blockReason').options.some(o=>o.value==='Almoço')"),'motivo de bloqueio histórico sem perda');ok(ev(r,"__imperioV90.getSet('agenda.cancellationReason').options.some(o=>o.value==='Imprevisto')"),'motivo cancelamento histórico sem perda');ok(ev(r,"__imperioV90.getSet('stock.productGroup').options.some(o=>o.value==='Capilar')"),'grupo de estoque histórico sem perda');
ok(ev(r,"Array.isArray(db.clients[0].tagIds)&&db.clients[0].tagIds.length===0"),'clientes normalizados com tagIds');ok(ev(r,"typeof db.bookings[0].cancellationReason==='string'&&typeof db.bookings[1].cancellationReason==='string'"),'bookings normalizados com cancellationReason');
ok(/^#[0-9a-f]{6}$/i.test(ev(r,"db.pros[0].agendaColor")),'cor atual congelada explicitamente');ok(ev(r,"defaultAgendaColor({specialty:'Cabelo'})===__imperioV90.neutralAgendaColor"),'nova cor não depende de texto da especialidade');
let finBefore=ev(r,"JSON.stringify({cash:db.demoCashMovements,fin:db.demoFinancialEntries,com:db.commissionEvents,recv:db.clientReceivables})");ev(r,"db.systemSettings.formFields.agenda.blockReason.required=true");let finAfter=ev(r,"JSON.stringify({cash:db.demoCashMovements,fin:db.demoFinancialEntries,com:db.commissionEvents,recv:db.clientReceivables})");eq(finAfter,finBefore,'configurabilidade residual é financeiramente neutra');
ok(ev(r,"__imperioV90.protectedSemantics.includes('booking.status')&&__imperioV90.protectedSemantics.includes('finance.entryNature')"),'semânticas críticas protegidas');ok(ev(r,"__imperioV90.catalogPolicy.includes('non_blocking')"),'política não bloqueante explícita');ok(ev(r,'__imperioV90.integrity().ok'),'integridade V90 válida');
ev(r,"db.clients[0].tagIds=['missing_tag']");ok(ev(r,'__imperioV90.integrity().orphanClientTags.length')===1,'detecta tag órfã');ev(r,"db.clients[0].tagIds=[]");
let raw=r.ls.getItem('imperio-demo-v1'),r2=run(raw);ok(!r2.errors.length,'reabertura sem erro');ok(ev(r2,'db.schemaVersion')===97,'schema permanece 90');ok(ev(r2,"db.migrationHistory.filter(x=>(typeof x==='string'?x:x.id)==='v90-structural-configurability-phase2').length")===1,'migration idempotente');ok(r2.ls.writeCount===0,'reabertura limpa não regrava');
ok(html.includes('data-v90-client-tag'),'UI tags presente');ok(html.includes("attachDatalist('pfSpec'"),'especialidade usa catálogo sem bloquear texto');ok(html.includes("attachDatalist('spGroup'"),'grupo estoque usa catálogo');ok(html.includes("injectBlockReason('blkReason')"),'bloqueio usa catálogo');ok(html.includes('injectExistingCancelReason'),'cancelamento captura motivo');
console.log(JSON.stringify({ok:true,tests,scripts:scripts.length,schema:90,feature:'structural_configurability_phase2'}));
