const fs=require('fs');
const html=fs.readFileSync(__dirname+'/../index.html','utf8');
let tests=0;const ok=(v,m)=>{tests++;if(!v)throw new Error(m)};
const opens=(html.match(/<script\b/gi)||[]).length, closes=(html.match(/<\/script>/gi)||[]).length;
ok(opens===55&&closes===55,'55 script tags balanced');
const scripts=[...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);
ok(scripts.length===55,'49 parsed scripts');
const staticHtml=html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,'');
const ids=[...staticHtml.matchAll(/\bid=["']([^"']+)["']/gi)].map(m=>m[1]);
const dupeIds=ids.filter((x,i)=>ids.indexOf(x)!==i);
ok(ids.length===17,'17 static IDs'); ok(dupeIds.length===0,'no duplicate static IDs');
const visible=staticHtml.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ');
for(const bad of [/\bfunction\s+[A-Za-z_$]/,/\bconst\s+[A-Za-z_$]/,/\blet\s+[A-Za-z_$]/,/\bwindow\./,/addEventListener\s*\(/,/=>/,/\$\{[^}]+\}/]) ok(!bad.test(visible),`no visible JS leak ${bad}`);
ok(scripts.reduce((n,s)=>n+(s.match(/addEventListener\s*\(/g)||[]).length,0)===1,'single historical addEventListener total');
ok(scripts.slice(42,50).every(s=>!s.includes('addEventListener(')),'V80-V87 add no event listeners');
ok(scripts.every(s=>!s.includes('DOMContentLoaded')),'no repeated DOMContentLoaded');
ok(scripts.filter(s=>s.includes('const V81_SCHEMA=81')).length===1,'single V81 functional block');
ok(scripts.filter(s=>s.includes('const V80_SCHEMA=80')).length===1,'single V80 functional block');
ok(scripts.filter(s=>s.includes('const V82_SCHEMA=82')).length===1,'single V82 functional block');
ok(scripts.filter(s=>s.includes('const V83_SCHEMA=83')).length===1,'single V83 functional block');
ok(scripts.filter(s=>s.includes('const V84_SCHEMA=84')).length===1,'single V84 functional block');
ok(scripts.filter(s=>s.includes('const V85_SCHEMA=85')).length===1,'single V85 functional block');
ok(scripts.filter(s=>s.includes('const V86_SCHEMA=86')).length===1,'single V86 block');
ok(scripts.filter(s=>s.includes('const V87_SCHEMA=87')).length===1,'single V87 block');
const allCode=scripts.join('\n');
ok((allCode.match(/id=\"v87WaitlistRecovery\"/g)||[]).length===2,'V87 recovery panel template + injection guard');
ok((allCode.match(/waitlistOpportunities/g)||[]).length>=1,'V87 history collection referenced');
ok((allCode.match(/id="v85Performance"/g)||[]).length===2,'V85 panel template + injection guard');
ok((allCode.match(/id="v83BookingAudit"/g)||[]).length===3,'V83 audit shell template + integration guards');
ok((allCode.match(/class="v82-trend"/g)||[]).length===2,'V82 trend template + injection guard');
ok((allCode.match(/class="v79-queue/g)||[]).length>=1,'waitlist template retained');
// Historical V81 incident guard: commission receipt region must not contain any later-version script/template insertion.
const receiptScript=scripts.find(s=>s.includes('function openCommissionReceipt'))||scripts.find(s=>s.includes('openCommissionReceipt=function')); const ri=receiptScript?receiptScript.indexOf('openCommissionReceipt'):-1;
ok(ri>=0,'commission receipt function exists');
let receipt=(receiptScript||'').slice(ri, ri+12000);
ok(!/<script\b/i.test(receipt),'no script tag in receipt function region');
for(const marker of ['V80_SCHEMA','V81_SCHEMA','V82_SCHEMA','V83_SCHEMA','V84_SCHEMA','V85_SCHEMA','V86_SCHEMA']) ok(!receipt.includes(marker),`no ${marker} inside receipt region`);
for(const s of scripts) ok(!/<script\b/i.test(s),'no nested script literal inside JS block');
console.log(JSON.stringify({ok:true,tests,scripts:scripts.length,staticIds:ids.length,listeners:1,visibleJsLeak:false}));
