const fs=require('fs'),vm=require('vm');
const html=fs.readFileSync(__dirname+'/../index.html','utf8');
const scripts=[...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);
const get=m=>scripts.find(s=>s.includes(m)); let tests=0; const ok=(v,m)=>{tests++;if(!v)throw new Error(m)};
// V83: one booking, one client, three services; combo keeps commercial total; metrics are financially inert.
{
 const code=get('const V83_SCHEMA=83'); let saves=0;
 const db={schemaVersion:82,migrationHistory:[],units:[{id:'u1',name:'Big',active:true}],services:[{id:'s1',name:'Manicure'},{id:'s2',name:'Pedicure'},{id:'s3',name:'Sobrancelha'}],pros:[{id:'p1',name:'Ana',active:true,units:['u1']}],clients:[{id:'c1',name:'Cliente'}],userAccounts:[{id:'r1',name:'Maria',role:'reception',active:true,allUnits:true}],bookings:[{id:'b1',unit:'u1',date:'2026-10-10',status:'Agendado',clientId:'c1',createdAt:'2026-09-28T13:00:00-03:00',createdByUserId:'r1',createdByUserName:'Maria',items:[{serviceId:'s1',service:'Manicure',pro:'p1',time:'10:00',duration:30,price:40},{serviceId:'s2',service:'Pedicure',pro:'p1',time:'10:30',duration:30,price:40},{serviceId:'s3',service:'Sobrancelha',pro:'p1',time:'11:00',duration:20,price:20}]}],demoCashMovements:[{id:'cash'}],demoFinancialEntries:[{id:'fin'}],clientReceivables:[{id:'rec'}],commissionEvents:[{id:'comm'}]};
 const ctx={console,db,window:null,Date,save:()=>saves++,escapeHtml:String,money:n=>String(n),formatDateBR:s=>s,localDateISO:d=>{d=d||new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`},normalizeBooking:x=>x,bookingAttribution:b=>({userId:b.createdByUserId,name:b.createdByUserName,origin:'internal_booking',createdAt:b.createdAt,reliability:'captured_user'}),comboApplicationsFromEntries:entries=>[{name:'Mani+Pedi',discount:15,picks:[entries[0].key,entries[1].key]}],__imperioV63:{currentUser:()=>db.userAccounts[0],allowedUnits:()=>db.units},renderReportAgendaV52:()=>'',renderAdmin:()=>{},setTimeout:f=>f(),document:{getElementById:()=>null}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(code,ctx);const api=ctx.__imperioV83;
 const before=JSON.stringify({cash:db.demoCashMovements,fin:db.demoFinancialEntries,rec:db.clientReceivables,comm:db.commissionEvents}); const rows=api.allRows(),m=api.metrics(rows);
 ok(m.bookings===1,'one booking');ok(m.services===3,'three services');ok(m.clients===1,'one unique client');ok(Math.abs(m.value-85)<1e-9,'commercial value uses combo 65 + third service 20');ok(Math.abs(m.referenceValue-100)<1e-9,'reference list value remains 100');ok(Math.abs(m.comboDiscount-15)<1e-9,'combo discount analytical only 15');ok(rows.filter(r=>r.bookingId==='b1').length===3,'three item facts from one booking');ok(JSON.stringify({cash:db.demoCashMovements,fin:db.demoFinancialEntries,rec:db.clientReceivables,comm:db.commissionEvents})===before,'reception metrics do not mutate financial facts');
}
// V84: goal calculation consumes V83 rows/metrics and remains financially inert.
{
 const code=get('const V84_SCHEMA=84');let saves=0;const fin={cash:[{id:'c'}],entries:[{id:'e'}],rec:[{id:'r'}],comm:[{id:'m'}]};
 const rows=[{bookingId:'b1',creatorId:'r1',createdDate:'2026-10-02',unitId:'u1',status:'Agendado',clientId:'c1',commercialPrice:65},{bookingId:'b1',creatorId:'r1',createdDate:'2026-10-02',unitId:'u1',status:'Agendado',clientId:'c1',commercialPrice:20},{bookingId:'b2',creatorId:'r1',createdDate:'2026-10-03',unitId:'u1',status:'Cancelado',clientId:'c2',commercialPrice:100}];
 const db={schemaVersion:83,migrationHistory:[],units:[{id:'u1',name:'Big',active:true}],userAccounts:[{id:'adm',name:'Admin',role:'admin',active:true,allUnits:true},{id:'r1',name:'Maria',role:'reception',active:true,unitIds:['u1']}],demoCashMovements:fin.cash,demoFinancialEntries:fin.entries,clientReceivables:fin.rec,commissionEvents:fin.comm};const ctx={console,db,window:null,Date,save:()=>saves++,structuredClone:global.structuredClone,escapeHtml:String,money:n=>String(n),formatDateBR:s=>s,localDateISO:()=> '2026-09-28',IMPERIO_ARRAY_COLLECTIONS:['units','bookings','migrationHistory'],__imperioV63:{currentUser:()=>db.userAccounts[0],canManageSettings:()=>true,allowedUnits:()=>db.units},__imperioV83:{allowedUnitsV83:()=>db.units,allRows:()=>rows,metrics:rs=>({bookings:new Set(rs.map(r=>r.bookingId)).size,services:rs.length,clients:new Set(rs.map(r=>r.clientId)).size,value:rs.reduce((s,r)=>s+r.commercialPrice,0)})},__imperioV64:{persistEvent:()=>{}},document:{getElementById:()=>null,querySelectorAll:()=>[]},setTimeout:()=>{},confirm:()=>true};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(code,ctx);let g={id:'g1',receptionUserId:'r1',unitIds:['u1'],periodFrom:'2026-10-01',periodTo:'2026-10-31',targetValue:100,targetServices:4,targetClients:2,status:'ACTIVE'};let before=JSON.stringify({cash:db.demoCashMovements,fin:db.demoFinancialEntries,rec:db.clientReceivables,comm:db.commissionEvents}),m=ctx.__imperioV84.goalMetrics(g);
 ok(m.bookings===1&&m.services===2&&m.clients===1&&m.value===85,'goal uses valid V83 facts');ok(JSON.stringify({cash:db.demoCashMovements,fin:db.demoFinancialEntries,rec:db.clientReceivables,comm:db.commissionEvents})===before,'goal calculation no financial fact');ok(Array.isArray(db.receptionBookingGoals),'goal collection initialized');
}
// V80: repeated reevaluation must not duplicate a notification; advisory conflict does not suppress opportunity.
{
 const code=get('const V80_SCHEMA=80');let saves=0;const db={schemaVersion:79,migrationHistory:[],waitlistRequests:[{id:'w1',clientId:'c1',clientNameSnapshot:'Cliente',unitId:'u1',serviceId:'s1',serviceNameSnapshot:'Manicure',availabilityDate:'2026-10-03',availabilityStartTime:'10:00',availabilityEndTime:'11:00',professionalPreferenceMode:'any',status:'WAITING',createdAt:'2026-09-01T10:00:00Z'}],bookings:[],services:[{id:'s1',name:'Manicure'}],pros:[{id:'p1',name:'Ana'}],units:[{id:'u1'}],categories:[]};
 const v66={generatedAlerts:()=>[{key:'base'}],activeCount:()=>1}; const ctx={console,db,window:null,Date,structuredClone:global.structuredClone,save:()=>saves++,localDateISO:()=> '2026-09-28',timeToMin:t=>{let[a,b]=t.split(':').map(Number);return a*60+b},minToTime:m=>`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`,availabilityEligiblePros:()=>[{id:'p1',name:'Ana'}],availabilityServiceDuration:()=>60,availabilityPlacement:()=>({proId:'p1',serviceId:'s1',start:'10:00',end:'11:00',startMin:600,endMin:660,duration:60}),availabilityClientCompatible:()=>true,normalizeBooking:x=>x,itemDuration:()=>60,__imperioV77:{physicalDemandsForDate:()=>[],evaluatePhysicalCapacity:()=>({configured:true,hasConflict:true,unallocated:1})},__imperioV66:v66,__imperioV63:{allowedUnits:()=>db.units},__imperioV64:{persistEvent:()=>{}},__imperioV79:{refreshAgendaButton:()=>{}},toast:()=>{},document:{getElementById:()=>null},renderAgenda:()=>{},renderAdmin:()=>{},closeModal:()=>{},openReservation:()=>{},defaultReservationItem:()=>({}),renderReservationModal:()=>{},availabilityServicePrice:()=>40,saveExistingBooking:()=>{},saveBlockTime:()=>{},saveBlockEdit:()=>{},deleteBlock:()=>{},agendaDrop:()=>{},saveReservation:()=>{},v79SaveQueueRequest:()=>{},v79MarkQueueContacted:()=>{},finishBooking:()=>{},savePro:()=>{},togglePro:()=>{},saveService:()=>{},toggleService:()=>{},v77SaveWorkstation:()=>{}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(code,ctx);const api=ctx.__imperioV80;
 ok(db.waitlistRequests[0].opportunityActive===true,'physical conflict does not block opportunity');ok(db.waitlistRequests[0].opportunityPhysicalConflict===true,'physical conflict exposed as advisory');ok(db.bookings.length===0,'opportunity no ghost booking');let a1=ctx.__imperioV66.generatedAlerts(),a2=ctx.__imperioV66.generatedAlerts();ok(a1.length===2&&a2.length===2,'repeated notification rendering stable');ok(new Set(a2.map(x=>x.key)).size===2,'notification keys deduplicated');let w=saves;api.reevaluate('repeat');api.reevaluate('repeat');let a3=ctx.__imperioV66.generatedAlerts();ok(a3.filter(x=>x.key==='waitlist_opportunity:w1').length===1,'repeated reevaluation keeps one opportunity alert');ok(db.bookings.length===0,'repeated reevaluation remains financially/operationally nonbooking');
}
console.log(JSON.stringify({ok:true,tests}));
