const fs=require('fs'),vm=require('vm');
const html=fs.readFileSync(__dirname+'/../index.html','utf8');
const scripts=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);
class FixedDate extends Date{constructor(...a){super(...(a.length?a:['2026-09-28T19:30:00-03:00']))}static now(){return Date.parse('2026-09-28T19:30:00-03:00')}}
class MockStorage{constructor(raw){this.m=new Map(raw==null?[]:[['imperio-demo-v1',raw]]);this.writeCount=0}getItem(k){return this.m.has(k)?this.m.get(k):null}setItem(k,v){this.writeCount++;this.m.set(k,String(v))}removeItem(k){this.m.delete(k)}}
function el(id=''){return {id,value:'',checked:false,innerHTML:'',textContent:'',title:'',style:{},dataset:{},children:[],options:[],selectedIndex:0,classList:{add(){},remove(){},toggle(){return false},contains(){return false}},appendChild(){},remove(){},focus(){},click(){},querySelector(){return null},querySelectorAll(){return[]},closest(){return null},insertAdjacentHTML(p,h){this.innerHTML+=h},insertAdjacentElement(){},addEventListener(){},removeEventListener(){},removeAttribute(){},setAttribute(){},getAttribute(){return null}}}
function run(raw){const els=new Map(),doc={body:el('body'),documentElement:el('html'),getElementById(id){if(!els.has(id))els.set(id,el(id));return els.get(id)},querySelector(){return null},querySelectorAll(){return[]},createElement:t=>el(t),addEventListener(){},removeEventListener(){}};const ls=new MockStorage(raw);const ctx={console,document:doc,localStorage:ls,sessionStorage:new MockStorage(),window:null,navigator:{clipboard:{writeText:async()=>{}}},location:{},history:{},innerWidth:1440,Date:FixedDate,JSON,Math,Number,String,Array,Object,Map,Set,Intl,RegExp,Promise,structuredClone:global.structuredClone,setTimeout:f=>{try{f()}catch{}},clearTimeout(){},setInterval(){return 1},clearInterval(){},confirm:()=>true,prompt:()=>'',alert:()=>{},fetch:async()=>({ok:false,json:async()=>({})}),Blob:function(){},FileReader:function(){},URL:{createObjectURL:()=>'',revokeObjectURL(){}},event:{target:null},addEventListener(){},removeEventListener(){}};ctx.window=ctx;vm.createContext(ctx);let errors=[];for(let i=0;i<scripts.length;i++){try{vm.runInContext(scripts[i],ctx,{filename:'s'+i+'.js'})}catch(e){errors.push(e.stack||String(e));break}}return {ctx,ls,doc,els,errors}}
function ev(r,c){return vm.runInContext(c,r.ctx)}
let tests=0;function ok(c,m){tests++;if(!c)throw new Error(m)}function eq(a,b,m){ok(JSON.stringify(a)===JSON.stringify(b),m+': '+JSON.stringify(a)+' != '+JSON.stringify(b))}
function db(){return {schemaVersion:90,migrationHistory:[{id:'v90-structural-configurability-phase2'}],units:[{id:'u1',name:'Big Shopping',active:true,show:true,online:true}],categories:[{id:'c1',name:'Manicure',active:true,order:10,configVersion:1}],services:[{id:'s1',name:'Manicure',category:'c1',clientArea:'hands',mustFinishBeforeSameArea:false,active:true,price:45,duration:45,show:true,online:true,proRules:{}}],pros:[{id:'p1',name:'Ana',publicName:'Ana',specialty:'Manicure',agendaColor:'#704578',units:['u1'],services:['s1'],active:true,show:true,online:true,schedule:{}}],clients:[{id:'cl1',name:'Cliente',phone:'31999999999',source:'Instagram',origin:'Presencial',registrationUnit:'u1',tagIds:[]}],bookings:[{id:'b1',unit:'u1',date:'2026-09-29',clientId:'cl1',client:'Cliente',status:'Confirmado',items:[{serviceId:'s1',service:'Manicure',pro:'p1',time:'10:00',duration:45,price:45}],cancellationReason:''}],workstations:[],acquisitionSources:[{id:'a1',name:'Instagram',active:true}],paymentMethods:[],financialAccounts:[],demoCashMovements:[{id:'cm1',amount:10}],demoFinancialEntries:[{id:'fe1',amount:10}],cashSessions:[],cashAudits:[],auditEvents:[],clientAppointments:[],clientCommands:[],demoProducts:[],demoPackageCatalog:[],clientCreditMovements:[],clientPackages:[],clientReturns:[],combos:[],financeCategories:[],companyEntities:[],financeGoals:[],stockProducts:[],stockBalances:[],stockPurchases:[],stockRequests:[],stockTransfers:[],stockMovements:[],stockInputCosts:[],stockFamilies:[],stockSubstitutions:[],commissionSettlements:[],commissionPayments:[],professionalCommissionAdjustments:[],tipMovements:[],remunerationRules:[],professionalDailyWork:[],clientReceivables:[],clientReceivablePayments:[],commissionEvents:[],tipDeductionRules:[],managementTasks:[],notificationAlertStates:{},notificationSettings:{},fiscalDocuments:[],fiscalSettings:{},reportSettings:{},commissionSettings:{},userAccounts:[{id:'adm',name:'Admin',username:'a',password:'x',role:'admin',active:true,allUnits:true,unitIds:[]}],systemSettings:{settingsVersion:1,formFields:{clients:{},professionals:{},agenda:{},stock:{}},optionSets:{}},communicationSettings:{whatsapp:{unitNumbers:{},templates:{}}},agendaFillSnapshots:[],agendaFillTrendSettings:{historyWindowDays:180,maxSamples:8,minSamples:4,thresholdPp:8},waitlistRequests:[],waitlistOpportunities:[]}}
const initial=db();
let r=run(JSON.stringify(initial));ok(!r.errors.length,'runtime sem erro');ok(scripts.length===55,'55 scripts');ok(ev(r,'db.schemaVersion')===91,'schema 91');ok(ev(r,'__imperioV91.schema')===91,'API V91');ok(ev(r,"db.migrationHistory.filter(x=>(typeof x==='string'?x:x.id)==='v91-ux-responsive-foundation').length")===1,'migration V91 única');
ok(ev(r,'__imperioV91.businessRulesChanged')===false,'sem mudança de regra de negócio');ok(ev(r,"__imperioV91.financialImpact==='none'"),'impacto financeiro nulo');ok(ev(r,"__imperioV91.agendaPolicy.includes('no_business_rule_change')"),'Agenda preservada');
let stableBefore=ev(r,"JSON.stringify({units:db.units,categories:db.categories,services:db.services,pros:db.pros,clients:db.clients,bookings:db.bookings,cash:db.demoCashMovements,fin:db.demoFinancialEntries})");ok(ev(r,'__imperioV91.migrate()')===false,'segunda migration V91 é no-op');let stableAfter=ev(r,"JSON.stringify({units:db.units,categories:db.categories,services:db.services,pros:db.pros,clients:db.clients,bookings:db.bookings,cash:db.demoCashMovements,fin:db.demoFinancialEntries})");eq(stableAfter,stableBefore,'V91 não altera dados operacionais em reaplicação');
ok(typeof ev(r,'v91OpenMobileNav')==='function','API abrir menu móvel');ok(typeof ev(r,'v91CloseMobileNav')==='function','API fechar menu móvel');ok(ev(r,'v871OpenMobileNav===v91OpenMobileNav'),'botão móvel legado redirecionado para V91');
ok(html.includes('.v91-mobile-drawer'),'drawer móvel presente');ok(html.includes('@media(max-width:800px)'),'breakpoint móvel presente');ok(html.includes('.modal{width:100%;max-width:none;max-height:94dvh'),'modal móvel adaptado');ok(html.includes('.table-card{overflow:auto'),'tabelas genericamente roláveis');ok(html.includes('.agenda .time{position:sticky;left:0'),'coluna de horário sticky no celular');ok(html.includes('data-v91-agenda-hint'),'hint de rolagem da Agenda');ok(html.includes('prefers-reduced-motion'),'acessibilidade de movimento');ok(html.includes(':focus-visible'),'foco visível');ok(html.includes('--v91-touch:44px'),'token de toque');
ok(ev(r,'typeof evaluatePhysicalCapacity')==='function','motor de capacidade preservado');ok(ev(r,'typeof __imperioV88')==='object','V88 preservada');ok(ev(r,'typeof __imperioV90')==='object','V90 preservada');
let raw=r.ls.getItem('imperio-demo-v1'),r2=run(raw);ok(!r2.errors.length,'reabertura sem erro');ok(ev(r2,'db.schemaVersion')===91,'schema 91 após reabrir');ok(ev(r2,"db.migrationHistory.filter(x=>(typeof x==='string'?x:x.id)==='v91-ux-responsive-foundation').length")===1,'migration idempotente');ok(r2.ls.writeCount===0,'reabertura limpa não regrava');
console.log(JSON.stringify({ok:true,tests,scripts:scripts.length,schema:91,feature:'ux_responsive_foundation'}));
