const fs=require('fs'),vm=require('vm');
const html=fs.readFileSync(__dirname+'/../index.html','utf8');
const scripts=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);
global.vm=vm;global.scripts=scripts;
const helperLines=fs.readFileSync(__dirname+'/V88_TEST_AGENDA_FILL_TREND.js','utf8').split('\n').slice(3,17).join('\n');
vm.runInThisContext(helperLines,{filename:'v88-fixture-helpers.js'});
let tests=0;function check(c,m){tests++;if(!c)throw new Error(m)}
let r=start();
check(scripts.length===54,'expected 52 scripts');
check(ev(r.ctx,'db.schemaVersion')===90,'current schema 88');
check(ev(r.ctx,"__imperioV871.release==='87.1'"),'V87.1 API preserved');
check(ev(r.ctx,"__imperioV871.migrationId==='v87-1-technical-stabilization'"),'V87.1 migration id preserved');
check(ev(r.ctx,"db.migrationHistory.filter(x=>(typeof x==='string'?x:x.id)==='v87-1-technical-stabilization').length")===1,'V87.1 migration unique');
check(ev(r.ctx,"IMPERIO_ARRAY_COLLECTIONS.includes('agendaFillSnapshots')")===true,'snapshot registry preserved');
check(ev(r.ctx,'Array.isArray(db.agendaFillSnapshots)')===true,'snapshot collection exists');
check(JSON.stringify(ev(r.ctx,'__imperioV871.checkpoints'))==='[0,1,3,7,14,30]','checkpoint set preserved');
check(ev(r.ctx,"db.agendaFillSnapshots.every(x=>String(x.targetDate)>=String(x.observedDate))")===true,'no past snapshot fabrication');
check(ev(r.ctx,'db.agendaFillSnapshots.every(x=>Number(x.leadDays)>=0)')===true,'no negative lead snapshots');
let before=ev(r.ctx,'db.agendaFillSnapshots.length'),writesBefore=r.ls.writeCount;
ev(r.ctx,"__imperioV871.captureCheckpoints('repeat-test')");
check(ev(r.ctx,'db.agendaFillSnapshots.length')===before,'repeat capture does not duplicate');
check(r.ls.writeCount===writesBefore,'repeat unchanged capture does not write');
let preOne=ev(r.ctx,'db.agendaFillSnapshots.length');
ev(r.ctx,"__imperioV871.captureOne('u1','2026-10-02','manual-test')");
let afterOne=ev(r.ctx,'db.agendaFillSnapshots.length');
ev(r.ctx,"__imperioV871.captureOne('u1','2026-10-02','manual-test')");
check(afterOne===preOne+1,'new snapshot captured once');
check(ev(r.ctx,'db.agendaFillSnapshots.length')===afterOne,'same-key capture idempotent');
ev(r.ctx,"window.__v871Seen=0;window.__v871Off=__imperioV871.eventBus.on('agenda.changed',()=>window.__v871Seen++);__imperioV871.eventBus.emit('agenda.changed',{test:true});window.__v871Off()");
check(ev(r.ctx,'window.__v871Seen')===1,'event bus on/emit/off works');
ev(r.ctx,"window.__v871Saved=0;window.__v871Off2=__imperioV871.eventBus.on('agenda.changed',()=>window.__v871Saved++);db.bookings.push({id:'v871-test-booking',unit:'u1',date:'2026-10-01',clientId:'cl1',client:'Juliana',status:'Agendado',items:[{serviceId:'s_man',service:'Manicure',pro:'p1',time:'10:00',duration:40,price:40}]});save({render:false,reason:'v871-event-test'})");
check(ev(r.ctx,'window.__v871Saved')===1,'material agenda save emits agenda.changed');
ev(r.ctx,"save({render:false,reason:'v871-event-test-repeat'})");
check(ev(r.ctx,'window.__v871Saved')===1,'unchanged repeat save does not duplicate agenda event');
ev(r.ctx,'window.__v871Off2()');
check(ev(r.ctx,'Array.isArray(__imperioV871.integrity().critical)')===true,'integrity result available');
ev(r.ctx,'db.units.push({...db.units[0]})');
check(ev(r.ctx,"__imperioV871.integrity().critical.some(x=>x.code==='DUPLICATE_ID')")===true,'duplicate IDs detected');
ev(r.ctx,'db.units.pop()');
ev(r.ctx,"db.bookings.push({id:'orphan-v871',unit:'missing-unit',date:'2026-10-01',clientId:'cl1',client:'Juliana',status:'Agendado',items:[{serviceId:'s_man',service:'Manicure',pro:'missing-pro',time:'11:00',duration:40,price:40}]})");
check(ev(r.ctx,"__imperioV871.integrity().critical.some(x=>x.code==='BOOKING_UNIT_ORPHAN')")===true,'booking unit orphan detected');
check(ev(r.ctx,"__imperioV871.integrity().critical.some(x=>x.code==='BOOKING_PRO_ORPHAN')")===true,'booking professional orphan detected');
check(ev(r.ctx,"typeof v871OpenMobileNav==='function'")===true,'mobile nav function preserved');
check(html.includes('.v871-mobile-menu{display:none')&&html.includes('@media(max-width:800px)')&&html.includes('.v871-mobile-menu{display:inline-flex'),'mobile nav CSS preserved');
check(ev(r.ctx,"__imperioV871.financialImpact==='none'")===true,'financial neutrality preserved');
check(ev(r.ctx,"__imperioV871.historicalPolicy==='prospective_only_no_backfill'")===true,'no-backfill policy preserved');
console.log(JSON.stringify({ok:true,tests,scripts:scripts.length,feature:'v87_1_stabilization_preserved'}));
