const fs=require('fs'),vm=require('vm');
const html=fs.readFileSync(__dirname+'/../index.html','utf8');
const scripts=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);
class MockStorage{constructor(raw){this.m=new Map(raw==null?[]:[['imperio-demo-v1',raw]]);this.writeCount=0}getItem(k){return this.m.has(k)?this.m.get(k):null}setItem(k,v){this.writeCount++;this.m.set(k,String(v))}removeItem(k){this.m.delete(k)}clear(){this.m.clear()}}
function element(id=''){return {id,value:'',checked:false,innerHTML:'',textContent:'',style:{},dataset:{},children:[],options:[],selectedIndex:0,className:'',src:'',href:'',files:[],disabled:false,firstChild:null,parentNode:null,classList:{add(){},remove(){},toggle(){return false},contains(){return false}},appendChild(x){this.children.push(x);x.parentNode=this;return x},insertBefore(x){this.children.unshift(x);x.parentNode=this;return x},remove(){},click(){},focus(){},select(){},insertAdjacentElement(){},insertAdjacentHTML(){},addEventListener(){},removeEventListener(){},querySelector(){return null},querySelectorAll(){return[]},closest(){return null},contains(){return false},setAttribute(){},getAttribute(){return null}}}
function run(raw){const els=new Map(),qsAll=new Map();const doc={body:element('body'),documentElement:element('html'),_qsAll:qsAll,getElementById(id){if(!els.has(id))els.set(id,element(id));return els.get(id)},querySelector(){return null},querySelectorAll(sel){return qsAll.get(sel)||[]},createElement(tag){return element(tag)},addEventListener(){},removeEventListener(){}};const ls=new MockStorage(raw),ss=new MockStorage(null);const ctx={console,localStorage:ls,sessionStorage:ss,document:doc,window:null,navigator:{clipboard:{writeText:async()=>{}}},location:{},history:{},setTimeout:(f)=>{try{f()}catch{}},clearTimeout(){},setInterval(){return 1},clearInterval(){},structuredClone:global.structuredClone,Date,JSON,Math,Number,String,Array,Object,Map,Set,Intl,RegExp,Promise,Blob:function(){},FileReader:function(){},URL:{createObjectURL:()=>'',revokeObjectURL(){}},confirm:()=>true,prompt:()=>'',alert:()=>{},fetch:async()=>({ok:false,json:async()=>({})}),event:{target:null}};ctx.window=ctx;vm.createContext(ctx);const errors=[];for(let i=0;i<scripts.length;i++){try{vm.runInContext(scripts[i],ctx,{filename:`script${i}.js`})}catch(e){errors.push(`script ${i}: ${e.stack||e}`);break}}return {ctx,ls,ss,els,doc,errors}}
function ev(ctx,code){return vm.runInContext(code,ctx)}
function assert(c,m){if(!c)throw new Error(m)}let tests=0;function ok(c,m){tests++;assert(c,m)}
function setup(r){for(const id of ['adminTabs','unitPicker','subbar','adminPage','loginUser','loginPass','modalHost','v73NewOption'])r.ctx[id]=r.doc.getElementById(id);r.doc.getElementById('unitPicker').value='u1';let admin=ev(r.ctx,"(db.userAccounts||[]).find(u=>u.role==='admin'&&u.active!==false)?.id||''");if(admin)ev(r.ctx,`__imperioV63.sessionSet(${JSON.stringify(admin)})`)}
function input(r,id,value='',checked=false){let e=r.doc.getElementById(id);e.value=String(value);e.checked=!!checked;return e}
function row(qtyClass,qty){let q=element();q.value=String(qty);return {querySelector(sel){if(sel.includes('number')||sel.includes(qtyClass))return q;return null}}}
let r=run(null);setup(r);
ok(!r.errors.length,'A runtime sem erros');
ok(scripts.length===59,'A 36 blocos JavaScript');
ok(ev(r.ctx,'db.schemaVersion')===95,'A schema 73');
ok(ev(r.ctx,"db.migrationHistory.filter(x=>(typeof x==='string'?x:x.id)==='v73-configurable-fields-options-professionals-stock').length")===1,'A migração V73 única');
ok(ev(r.ctx,"typeof __imperioV73==='object'&&__imperioV73.schema===73"),'A API V73 exposta');
ok(ev(r.ctx,'db.systemSettings.formConfigModulesVersion')===4,'A versão modular 3');
// Central / módulos.
ok(ev(r.ctx,"v73OpenFieldsSettings('professionals')")===true,'B abre Profissionais');let h=r.doc.getElementById('adminPage').innerHTML;
ok(h.includes('Profissionais')&&h.includes('Estoque')&&h.includes('Financeiro'),'B módulos visíveis');
ok(h.includes('Bancário / Pix')&&h.includes('Obrigatório pelo sistema'),'B grupos e proteção profissional');
ok(ev(r.ctx,"v73OpenFieldsSettings('stock')")===true,'B abre Estoque');h=r.doc.getElementById('adminPage').innerHTML;
ok(h.includes('Produtos')&&h.includes('Compras')&&h.includes('Inventário')&&h.includes('Consumo'),'B grupos de Estoque renderizados');
ok(h.includes('Motivo do ajuste de inventário')&&h.includes('Gerenciar opções'),'B motivo de inventário configurável');
// Profissionais: proteção / obrigatoriedade.
ok(ev(r.ctx,"__imperioV73.isRequired('professionals','name')")===true,'C nome profissional obrigatório');
ok(ev(r.ctx,"__imperioV73.getField('professionals','name').systemRequired")===true,'C nome protegido');
ok(ev(r.ctx,"v73SetFieldRequired('professionals','name',false)")===false,'C não desativa nome');
ok(ev(r.ctx,"v73SetFieldRequired('professionals','phone',true)")===true,'C telefone pode virar obrigatório');
// Preparar DOM profissional e validar.
for(const [id,val] of Object.entries({pfName:'Ana',pfPublicName:'Ana',pfSpec:'Nail designer',pfAgendaColor:'#aa88bb',pfBio:'',pfCpf:'',pfBirth:'',pfPhone:'',pfEmail:'',pfNotes:'',pfCnpj:'',pfLegalName:'',pfTradeName:'',pfContractEnd:'',pfBank:'',pfHolder:'',pfAgency:'',pfAccount:'',pfAccountType:'',pfPixType:'',pfPixKey:''}))input(r,id,val);
input(r,'pfHasCompany','',false);let unit=element();unit.value='u1';unit.checked=true;r.doc._qsAll.set('.pfUnit:checked',[unit]);
let pv=ev(r.ctx,'__imperioV73.validateProfessional()');ok(pv.ok===false&&pv.missing.some(x=>x.field==='phone'),'C telefone vazio bloqueia');input(r,'pfPhone','3199999999');pv=ev(r.ctx,'__imperioV73.validateProfessional()');ok(pv.ok===true,'C telefone preenchido libera');
ok(ev(r.ctx,"v73SetFieldRequired('professionals','phone',false)")===true,'C telefone volta opcional');
// PJ condicional: obrigatório só quando possui empresa.
ok(ev(r.ctx,"v73SetFieldRequired('professionals','cnpj',true)")===true,'D CNPJ configurável como obrigatório');input(r,'pfHasCompany','',false);input(r,'pfCnpj','');pv=ev(r.ctx,'__imperioV73.validateProfessional()');ok(pv.ok===true,'D sem PJ não exige CNPJ');input(r,'pfHasCompany','',true);pv=ev(r.ctx,'__imperioV73.validateProfessional()');ok(pv.ok===false&&pv.missing.some(x=>x.field==='cnpj'),'D com PJ exige CNPJ');input(r,'pfCnpj','12.345.678/0001-00');pv=ev(r.ctx,'__imperioV73.validateProfessional()');ok(pv.ok===true,'D CNPJ preenchido libera');
// Opções bancárias flexíveis e histórico.
let accSet=ev(r.ctx,"__imperioV73.getSet('professionals.accountType')");ok(accSet.options.some(x=>x.value==='Corrente'),'E tipos de conta migrados');r.doc.getElementById('v73NewOption').value='Conta salário';ok(ev(r.ctx,"v73AddOption('professionals.accountType')")===true,'E adiciona tipo de conta');let salaryId=ev(r.ctx,"__imperioV73.getSet('professionals.accountType').options.find(x=>x.value==='Conta salário').id");ok(!!salaryId,'E nova opção persistida');ok(ev(r.ctx,`v73RenameOption('professionals.accountType',${JSON.stringify(salaryId)},'Conta folha')`)===true,'E renomeia tipo de conta futura');
ev(r.ctx,"db.pros.push({id:'pHist73',name:'Histórica',active:false,units:['u1'],accountType:'Conta salário',pixType:'CPF'})");ok(ev(r.ctx,"__imperioV73.optionsHtml('professionals.accountType','Conta salário',true).includes('Conta salário')"),'E valor histórico anterior continua disponível');ok(ev(r.ctx,`v73ToggleOption('professionals.accountType',${JSON.stringify(salaryId)})`)===true,'E desativa opção sem apagar histórico');ok(ev(r.ctx,"db.pros.find(x=>x.id==='pHist73').accountType")==='Conta salário','E profissional histórica não reescrita');
// Pix canônico protegido.
let pix=ev(r.ctx,"__imperioV73.getSet('professionals.pixType')");ok(pix.lockedValues===true&&pix.options.some(x=>x.value==='CNPJ'),'F Pix canônico protegido com CNPJ');r.doc.getElementById('v73NewOption').value='Usuário Pix';ok(ev(r.ctx,"v73AddOption('professionals.pixType')")===false,'F não cria tipo Pix arbitrário');let pixCpf=ev(r.ctx,"__imperioV73.getSet('professionals.pixType').options.find(x=>x.value==='CPF').id");ok(ev(r.ctx,`v73RenameOption('professionals.pixType',${JSON.stringify(pixCpf)},'Documento')`)===false,'F não renomeia valor técnico Pix');
// Estoque: campos e opções.
ok(ev(r.ctx,"__imperioV73.isRequired('stock','name')")===true,'G nome do produto protegido');ok(ev(r.ctx,"__imperioV73.isRequired('stock','inventoryReason')")===true,'G motivo do inventário protegido');ok(ev(r.ctx,"v73SetFieldRequired('stock','inventoryReason',false)")===false,'G não desativa motivo do inventário');
ok(ev(r.ctx,"__imperioV73.getSet('stock.productType').lockedValues")===true,'G tipo de produto protegido');ok(ev(r.ctx,"__imperioV73.getSet('stock.unit').options.some(x=>x.value==='un')"),'G unidades de estoque migradas');
r.doc.getElementById('v73NewOption').value='bisnaga';ok(ev(r.ctx,"v73AddOption('stock.unit')")===true,'G adiciona unidade de estoque');let bis=ev(r.ctx,"__imperioV73.getSet('stock.unit').options.find(x=>x.value==='bisnaga').id");ok(ev(r.ctx,`v73SetDefaultOption('stock.unit',${JSON.stringify(bis)})`)===true,'G define unidade padrão');
// Produto: validação central e apropriação protegida.
for(const [id,val] of Object.entries({spName:'Gel teste',spType:'INPUT',spUnit:'un',spSku:'GT',spFamily:'',spBrand:'Marca',spPackQty:'30',spBaseUnit:'g',spGroup:'',spCost:'50',spSale:'0',spMin:'2',spSupplier:''}))input(r,id,val);
let alloc=element();alloc.value='100';alloc.dataset={cat:'c1'};r.doc._qsAll.set('.stock-alloc',[alloc]);let sv=ev(r.ctx,'__imperioV73.validateStockProduct()');ok(sv.ok===true,'H produto insumo válido com apropriação 100%');alloc.value='90';sv=ev(r.ctx,'__imperioV73.validateStockProduct()');ok(sv.ok===false&&sv.missing.some(x=>x.field==='allocations'),'H apropriação incompleta bloqueia');alloc.value='100';
ok(ev(r.ctx,"v73SetFieldRequired('stock','supplier',true)")===true,'H fornecedor pode virar obrigatório');sv=ev(r.ctx,'__imperioV73.validateStockProduct()');ok(sv.ok===false&&sv.missing.some(x=>x.field==='supplier'),'H fornecedor obrigatório bloqueia vazio');input(r,'spSupplier','Fornecedor X');sv=ev(r.ctx,'__imperioV73.validateStockProduct()');ok(sv.ok===true,'H fornecedor preenchido libera');ok(ev(r.ctx,"v73SetFieldRequired('stock','supplier',false)")===true,'H fornecedor volta opcional');
// Inventário: catálogo gerenciável e histórico intacto.
let reasonSet=ev(r.ctx,"__imperioV73.getSet('stock.inventoryReason')");ok(reasonSet.options.some(x=>x.value==='Inventário físico')&&reasonSet.options.some(x=>x.value==='Quebra'),'I motivos estruturados existentes');r.doc.getElementById('v73NewOption').value='Avaria no transporte';ok(ev(r.ctx,"v73AddOption('stock.inventoryReason')")===true,'I adiciona motivo');let rid=ev(r.ctx,"__imperioV73.getSet('stock.inventoryReason').options.find(x=>x.value==='Avaria no transporte').id");ok(ev(r.ctx,`v73RenameOption('stock.inventoryReason',${JSON.stringify(rid)},'Avaria logística')`)===true,'I renomeia motivo para usos futuros');ev(r.ctx,"db.stockMovements.push({id:'smHist73',type:'INVENTORY_ADJUSTMENT',note:'Avaria no transporte',productId:'sp_gel',locationId:'u1',qty:-1,unitCost:1})");ok(ev(r.ctx,"db.stockMovements.find(x=>x.id==='smHist73').note")==='Avaria no transporte','I movimento histórico preservado');
// Render do inventário troca campo livre por catálogo.
ev(r.ctx,"renderStockInventory()");h=r.doc.getElementById('adminPage').innerHTML;ok(h.includes('<select id="stockInvReason">'),'I inventário usa catálogo central');ok(!h.includes('<input id="stockInvReason"'),'I input livre antigo removido');
// Compras / solicitações / transferências / consumo: obrigatoriedade configurável das observações.
ok(ev(r.ctx,"v73SetFieldRequired('stock','purchaseNote',true)")===true,'J observação de compra configurável');input(r,'stockBuyDate','2026-09-28');input(r,'stockBuySupplier','Fornecedor');input(r,'stockBuyDest','central');input(r,'stockBuyFreight','0');input(r,'stockBuyNote','');r.doc._qsAll.set('#stockPurchaseLines .stock-line',[row('stk-buy-qty',1)]);let vv=ev(r.ctx,'__imperioV73.validatePurchase()');ok(vv.ok===false&&vv.missing.some(x=>x.field==='purchaseNote'),'J compra sem observação bloqueia');input(r,'stockBuyNote','NF 123');vv=ev(r.ctx,'__imperioV73.validatePurchase()');ok(vv.ok===true,'J compra com observação libera');
ok(ev(r.ctx,"v73SetFieldRequired('stock','transferNote',true)")===true,'J observação de transferência configurável');input(r,'stockTrSource','central');input(r,'stockTrDest','u1');input(r,'stockTrNote','');r.doc._qsAll.set('#stockTransferLines .stock-line',[row('stk-req-qty',2)]);vv=ev(r.ctx,'__imperioV73.validateTransfer()');ok(vv.ok===false&&vv.missing.some(x=>x.field==='transferNote'),'J transferência sem observação bloqueia');input(r,'stockTrNote','Reposição');vv=ev(r.ctx,'__imperioV73.validateTransfer()');ok(vv.ok===true,'J transferência com observação libera');
ok(ev(r.ctx,"v73SetFieldRequired('stock','consumptionNote',true)")===true,'J observação de consumo configurável');input(r,'stkConsDate','2026-09-28');input(r,'stkConsUnit','u1');input(r,'stkConsProduct','sp_gel');input(r,'stkConsQty','1');input(r,'stkConsNote','');vv=ev(r.ctx,'__imperioV73.validateConsumption()');ok(vv.ok===false&&vv.missing.some(x=>x.field==='consumptionNote'),'J consumo sem observação bloqueia');input(r,'stkConsNote','Uso operacional');vv=ev(r.ctx,'__imperioV73.validateConsumption()');ok(vv.ok===true,'J consumo com observação libera');
// Clientes/Agenda/Comandas seguem acessíveis pela mesma central.
ok(ev(r.ctx,"v73OpenFieldsSettings('clients')")===true,'K Clientes segue acessível');h=r.doc.getElementById('adminPage').innerHTML;ok(h.includes('Como conheceu')&&h.includes('Origem do cadastro'),'K Clientes preservado');ok(ev(r.ctx,"v73OpenFieldsSettings('agenda')")===true,'K Agenda segue acessível');h=r.doc.getElementById('adminPage').innerHTML;ok(h.includes('Status')&&h.includes('Observações da reserva'),'K Agenda preservada');ok(ev(r.ctx,"v73OpenFieldsSettings('commands')")===true,'K Comandas segue acessível');h=r.doc.getElementById('adminPage').innerHTML;ok(h.includes('Observações da comanda'),'K Comandas preservadas');
// Auditoria e idempotência.
ok(ev(r.ctx,"(db.auditEvents||[]).some(x=>x.module==='settings'&&['UPDATE_FIELD_REQUIRED','ADD_OPTION','RENAME_OPTION','DEACTIVATE_OPTION','SET_DEFAULT_OPTION'].includes(x.action))"),'L alterações B3 auditadas');
let w0=r.ls.writeCount;ok(ev(r.ctx,'__imperioV73.migrate()')===false,'M segunda migração não altera dados');ok(r.ls.writeCount===w0,'M segunda migração gera zero gravações');let raw=r.ls.getItem('imperio-demo-v1');let r2=run(raw);setup(r2);ok(!r2.errors.length,'M reinicialização sem erro');ok(ev(r2.ctx,'db.schemaVersion')===95,'M schema permanece 73');ok(ev(r2.ctx,"db.migrationHistory.filter(x=>(typeof x==='string'?x:x.id)==='v73-configurable-fields-options-professionals-stock').length")===1,'M migração V73 única após reinício');
console.log(JSON.stringify({ok:true,scripts:scripts.length,tests,professionals:true,stock:true,historicalPreservation:true,centralValidation:true,audit:true,idempotent:true}));
