const fs=require('fs'),vm=require('vm');
const html=fs.readFileSync(__dirname+'/../index.html','utf8');
const scripts=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);
class FixedDate extends Date{constructor(...a){super(...(a.length?a:['2026-09-28T11:30:00-03:00']))}static now(){return Date.parse('2026-09-28T11:30:00-03:00')}}
class MockStorage{constructor(raw){this.m=new Map(raw==null?[]:[['imperio-demo-v1',raw]]);this.writeCount=0}getItem(k){return this.m.has(k)?this.m.get(k):null}setItem(k,v){this.writeCount++;this.m.set(k,String(v))}removeItem(k){this.m.delete(k)}clear(){this.m.clear()}}
function element(id=''){return {id,value:'',checked:false,innerHTML:'',outerHTML:'',textContent:'',style:{},dataset:{},children:[],options:[],selectedIndex:0,className:'',src:'',href:'',files:[],disabled:false,firstChild:null,parentNode:null,classList:{add(){},remove(){},toggle(){return false},contains(){return false}},appendChild(x){this.children.push(x);x.parentNode=this;return x},insertBefore(x){this.children.unshift(x);x.parentNode=this;return x},remove(){},click(){},focus(){},select(){},insertAdjacentElement(){},insertAdjacentHTML(pos,h){this.innerHTML+=h},addEventListener(){},removeEventListener(){},querySelector(){return null},querySelectorAll(){return[]},closest(){return null},contains(){return false},setAttribute(){},getAttribute(){return null}}}
function run(raw){const els=new Map(),qsAll=new Map();const doc={body:element('body'),documentElement:element('html'),_qsAll:qsAll,getElementById(id){if(!els.has(id))els.set(id,element(id));return els.get(id)},querySelector(){return null},querySelectorAll(sel){return qsAll.get(sel)||[]},createElement(tag){return element(tag)},addEventListener(){},removeEventListener(){}};const ls=new MockStorage(raw),ss=new MockStorage(null);const opened=[];const ctx={console,localStorage:ls,sessionStorage:ss,document:doc,window:null,navigator:{clipboard:{writeText:async()=>{}}},location:{},history:{},setTimeout:(f)=>{try{f()}catch{}},clearTimeout(){},setInterval(){return 1},clearInterval(){},structuredClone:global.structuredClone,Date:FixedDate,JSON,Math,Number,String,Array,Object,Map,Set,Intl,RegExp,Promise,Blob:function(){},FileReader:function(){},URL:{createObjectURL:()=>'',revokeObjectURL(){}},confirm:()=>true,prompt:()=>'',alert:()=>{},fetch:async()=>({ok:false,json:async()=>({})}),event:{target:null},open:(url)=>{opened.push(url);return null}};ctx.window=ctx;vm.createContext(ctx);const errors=[];for(let i=0;i<scripts.length;i++){try{vm.runInContext(scripts[i],ctx,{filename:`script${i}.js`})}catch(e){errors.push(`script ${i}: ${e.stack||e}`);break}}return {ctx,ls,ss,els,doc,errors,opened}}
function ev(ctx,code){return vm.runInContext(code,ctx)}
function assert(c,m){if(!c)throw new Error(m)}let tests=0;function ok(c,m){tests++;assert(c,m)}function eq(a,b,m){ok(JSON.stringify(a)===JSON.stringify(b),`${m}: ${JSON.stringify(a)} != ${JSON.stringify(b)}`)}
function hist(){return ['v58-legacy-commission-unit-tip-money-hardening','v59-reports-services-stock','v60-reports-finance-dre','v61-finance-dre-stabilization','v62-reports-marketing','v63-settings-users-operators','v64-audit-core-critical-events','v65-executive-overview','v66-notifications-management-tasks','v67-custom-user-permissions','v68-fiscal-foundation','v69-nfse-national-direct','v70-agenda-operational-metrics','v71-configurable-fields-options-clients','v72-configurable-fields-options-agenda-commands','v73-configurable-fields-options-professionals-stock','v74-configurable-fields-options-finance','v75-dre-combo-profitability-allocation','v76-fiscal-payments-booking-authorship','v77-workstations-physical-capacity','v78-physical-capacity-alerts'].map(id=>({id}))}
function sch(start='09:00',end='20:00'){let x={};for(let i=0;i<7;i++)x['u1-'+i]={work:true,start,end},x['u2-'+i]={work:true,start,end};return x}
function baseDb(){return {schemaVersion:78,migrationHistory:hist(),units:[{id:'u1',name:'Big Shopping',active:true,show:true,online:true},{id:'u2',name:'Shopping Contagem',active:true,show:true,online:true}],categories:[{id:'c_man',name:'Manicure',active:true},{id:'c_long',name:'Alongamento',active:true}],services:[{id:'s_man',name:'Manicure',category:'c_man',price:40,duration:40,active:true,show:true,online:true,proRules:{}},{id:'s_long',name:'Alongamento',category:'c_long',price:120,duration:60,active:true,show:true,online:true,proRules:{}}],pros:[{id:'p1',name:'Ana',active:true,show:true,online:true,units:['u1'],services:['s_man','s_long'],schedule:sch()},{id:'p2',name:'Camila',active:true,show:true,online:true,units:['u1'],services:['s_man'],schedule:sch()},{id:'p3',name:'Bia',active:true,show:true,online:true,units:['u2'],services:['s_man'],schedule:sch()}],clients:[{id:'cl1',name:'Juliana',phone:'31999999999',cpf:'',source:'Instagram',origin:'Presencial',registrationUnit:'u1'},{id:'cl2',name:'Marina',phone:'31888888888',cpf:'',source:'Google',origin:'Presencial',registrationUnit:'u1'}],bookings:[],clientAppointments:[],clientCommands:[],paymentMethods:[],financialAccounts:[],demoCashMovements:[],demoFinancialEntries:[],cashSessions:[],cashAudits:[],auditEvents:[],clientCreditMovements:[],clientReceivables:[],clientReceivablePayments:[],commissionEvents:[],remunerationRules:[],tipMovements:[],tipDeductionRules:[],demoProducts:[],demoPackageCatalog:[],clientPackages:[],clientReturns:[],combos:[],financeCategories:[],companyEntities:[],financeGoals:[],stockProducts:[],stockBalances:[],stockPurchases:[],stockRequests:[],stockTransfers:[],stockMovements:[],stockInputCosts:[],stockFamilies:[],stockSubstitutions:[],commissionSettlements:[],commissionPayments:[],commissionAdjustments:[],professionalCommissionAdjustments:[],professionalDailyWork:[],managementTasks:[],notificationAlertStates:{},notificationSettings:{},fiscalDocuments:[],fiscalSettings:{},reportSettings:{inactiveDays:90,returnLateGraceDays:7,capacityProductivityFactor:95},commissionSettings:{discountsReduceBase:true,directPaymentReducesSettlement:true,comboAllocation:'proportional'},storageMeta:{dataMode:'real',createdAt:'2026-09-01T00:00:00.000Z',storageSafetyVersion:1},userAccounts:[{id:'usr_admin',name:'Admin',username:'admin',password:'x',role:'admin',active:true,allUnits:true,unitIds:[]},{id:'usr_mgr',name:'Gerente Big',username:'mgr',password:'x',role:'manager',active:true,allUnits:false,unitIds:['u1']},{id:'usr_mgr2',name:'Gerente Contagem',username:'mgr2',password:'x',role:'manager',active:true,allUnits:false,unitIds:['u2']}],systemSettings:{settingsVersion:1,formFields:{},optionSets:{}},communicationSettings:{whatsapp:{mode:'manual_link',version:1,unitNumbers:{},templates:{confirmation:'',reminder:'',reactivation:'',monthly_receivable:''}}},workstations:[{id:'ws1',unitId:'u1',name:'Mesa 1',allowedCategoryIds:['c_man'],active:true,createdAt:'x',updatedAt:'x'}]}}
function setup(r,user='usr_mgr'){for(const id of ['adminTabs','unitPicker','subbar','adminPage','loginUser','loginPass','modalHost','rDate','rStatus','rNotes','v79Unit','v79Service','v79Date','v79Start','v79End','v79ProMode','v79PreferredPro','v79Notes'])r.ctx[id]=r.doc.getElementById(id);r.doc.getElementById('unitPicker').value='u1';r.ctx.unitPicker=r.doc.getElementById('unitPicker');r.ctx.page='agenda';r.ctx.agendaDate='2026-10-03';r.doc.getElementById('rDate').value='2026-10-03';r.doc.getElementById('rStatus').value='Agendado';r.doc.getElementById('rNotes').value='';ev(r.ctx,`__imperioV63.sessionSet('${user}')`)}
function form(r,{client='cl1',service='s_man',unit='u1',date='2026-10-03',start='13:00',end='18:00',mode='any',pro='',notes=''}={}){r.ctx.__v79QueueDraft={clientId:client};r.doc.getElementById('v79Unit').value=unit;r.doc.getElementById('v79Service').value=service;r.doc.getElementById('v79Date').value=date;r.doc.getElementById('v79Start').value=start;r.doc.getElementById('v79End').value=end;r.doc.getElementById('v79ProMode').value=mode;r.doc.getElementById('v79PreferredPro').value=pro;r.doc.getElementById('v79Notes').value=notes}
let r=run(JSON.stringify(baseDb()));setup(r);ok(!r.errors.length,'runtime V80 sem erro');ok(scripts.length===59,'43 scripts');ok(ev(r.ctx,'db.schemaVersion')===95,'schema 80');
function addReq(id,client,mode='any',pref='',created='2026-09-28T12:00:00.000Z'){ev(r.ctx,`db.waitlistRequests.push({id:'${id}',clientId:'${client}',clientNameSnapshot:'${client}',unitId:'u1',unitPreferenceMode:'required',acceptedUnitIds:['u1'],serviceId:'s_man',serviceNameSnapshot:'Manicure',serviceDurationSnapshot:40,availabilityDate:'2026-10-03',availabilityStartTime:'13:00',availabilityEndTime:'16:00',professionalPreferenceMode:'${mode}',preferredProfessionalId:'${pref}',status:'WAITING',createdAt:'${created}'})`)}
addReq('q1','cl1','preferred','p1');ok(ev(r.ctx,"__imperioV80.reevaluate('test').found")>=1,'detecta oportunidade');ok(ev(r.ctx,"db.waitlistRequests.find(x=>x.id==='q1').status")==='OPPORTUNITY','WAITING vira OPPORTUNITY');ok(ev(r.ctx,"db.waitlistRequests.find(x=>x.id==='q1').opportunityClass")==='IDEAL','preferida disponível gera IDEAL');ok(ev(r.ctx,"db.waitlistRequests.find(x=>x.id==='q1').opportunityProfessionalId")==='p1','IDEAL usa profissional preferida');ok(ev(r.ctx,'db.bookings.length')===0,'detecção não cria booking');
// Bloqueia a preferida em toda a janela: preferred aceita alternativa.
ev(r.ctx,"db.bookings.push({id:'blk1',unit:'u1',date:'2026-10-03',client:'Bloqueado',status:'Bloqueado',blockAllDay:false,items:[{serviceId:'',service:'Bloqueio',pro:'p1',time:'13:00',duration:180}]})");ev(r.ctx,"__imperioV80.reevaluate('block')");ok(ev(r.ctx,"db.waitlistRequests.find(x=>x.id==='q1').opportunityClass")==='ALTERNATIVE','preferred cai para ALTERNATIVE');ok(ev(r.ctx,"db.waitlistRequests.find(x=>x.id==='q1').opportunityProfessionalId")==='p2','alternativa usa outra habilitada');
// Required nunca aceita p2.
addReq('qreq','cl2','required','p1','2026-09-28T11:00:00.000Z');ev(r.ctx,"__imperioV80.reevaluate('required')");ok(!ev(r.ctx,"db.waitlistRequests.find(x=>x.id==='qreq').opportunityActive"),'required sem preferida não recebe alternativa');
// Removendo bloqueio devolve oportunidade à required.
ev(r.ctx,"db.bookings=db.bookings.filter(x=>x.id!=='blk1')");ev(r.ctx,"__imperioV80.reevaluate('unblock')");ok(ev(r.ctx,"db.waitlistRequests.find(x=>x.id==='qreq').opportunityActive")===true,'desbloqueio gera oportunidade');ok(ev(r.ctx,"db.waitlistRequests.find(x=>x.id==='qreq').opportunityProfessionalId")==='p1','required fica na exigida');
// Uma mesma faixa/profissional não é atribuída a duas solicitações concorrentes quando só há uma profissional elegível.
ev(r.ctx,"db.waitlistRequests=[]; db.pros.find(x=>x.id==='p2').active=false");addReq('old','cl1','any','','2026-09-28T10:00:00.000Z');addReq('new','cl2','any','','2026-09-28T11:00:00.000Z');ev(r.ctx,"db.waitlistRequests.forEach(x=>x.availabilityEndTime='13:40')");ev(r.ctx,"__imperioV80.reevaluate('collision')");ok(ev(r.ctx,"db.waitlistRequests.filter(x=>x.opportunityActive).length")===1,'não oferece mesma vaga simultaneamente a duas solicitações');ok(ev(r.ctx,"db.waitlistRequests.find(x=>x.id==='old').opportunityActive")===true,'ordem de entrada desempata');
// Capacidade física é aviso, não bloqueio: estação de manicure ocupada por outro atendimento simultâneo.
ev(r.ctx,"db.waitlistRequests=[]; db.pros.find(x=>x.id==='p2').active=true; db.bookings=[{id:'bcap',unit:'u1',date:'2026-10-03',clientId:'other',client:'Outra',status:'Agendado',items:[{serviceId:'s_man',service:'Manicure',pro:'p1',time:'13:00',duration:40}]}]");addReq('qcap','cl1','required','p2');ev(r.ctx,"__imperioV80.reevaluate('capacity')");ok(ev(r.ctx,"db.waitlistRequests.find(x=>x.id==='qcap').opportunityActive")===true,'conflito físico não esconde oportunidade');ok(ev(r.ctx,"db.waitlistRequests.find(x=>x.id==='qcap').opportunityPhysicalConflict")===true,'oportunidade sinaliza atenção à capacidade física');
// Alerta gerencial integrado.
ok(ev(r.ctx,"__imperioV66.generatedAlerts().some(x=>x.sourceType==='waitlist_opportunity'&&x.sourceId==='qcap')"),'oportunidade aparece em Notificações/Tarefas');
// Revalidação no clique deve respeitar a arbitragem atual da fila, não apenas a disponibilidade bruta da Agenda.
ev(r.ctx,"db.bookings=[]; db.waitlistRequests=[]; db.pros.find(x=>x.id==='p2').active=false");addReq('late','cl2','any','','2026-09-28T11:00:00.000Z');ev(r.ctx,"db.waitlistRequests.find(x=>x.id==='late').availabilityEndTime='13:40'");ev(r.ctx,"__imperioV80.reevaluate('race_seed')");ok(ev(r.ctx,"db.waitlistRequests.find(x=>x.id==='late').opportunityActive")===true,'solicitação posterior recebe vaga antes da concorrente existir');addReq('early','cl1','any','','2026-09-28T10:00:00.000Z');ev(r.ctx,"db.waitlistRequests.find(x=>x.id==='early').availabilityEndTime='13:40'");ok(ev(r.ctx,"__imperioV80.beginBooking('late')")===false,'clique aborta quando arbitragem atual reatribuiu a vaga');ok(ev(r.ctx,"db.waitlistRequests.find(x=>x.id==='early').opportunityActive")===true,'reavaliação entrega vaga à solicitação prioritária');ok(ev(r.ctx,"db.waitlistRequests.find(x=>x.id==='late').opportunityActive")===false,'oportunidade obsoleta é retirada da solicitação posterior');

console.log(JSON.stringify({ok:true,tests,opportunity:true,idealAlternative:true,required:true,collisionProtection:true,physicalAdvisory:true,notifications:true,noAutoBooking:true}));
